### ISSUE TITLE
Python 3.8 incompatibility: test_enum_to_int failure in pybind versions 2.2.4, 2.3.0 and 2.4.0

### ISSUE THREAD

**Issue by susilehtola** [pybind/pybind11#1780] opened 2019-05-04 18:47 UTC
Fedora build of pybind-2.2.4 for Python 3.8 with patch for e7ef34f23f194cfa40bdbf967c6d34712261a4ee fails the test phase with 
```
    def test_enum_to_int():
>       m.test_enum_to_int(m.Flags.Read)
E       TypeError: test_enum_to_int(): incompatible function arguments. The following argument types are supported:
E           1. (arg0: int) -> None
E       
E       Invoked with: Flags.Read
```
Full log at https://copr-be.cloud.fedoraproject.org/results/@python/python3.8/fedora-rawhide-x86_64/00903558-pybind11/builder-live.log

**Comment by eacousineau** [comment] 2019-05-05 12:49
Confirmed this on Ubuntu 18.04, building CPython 3.8.0a3 (9a448855b5) from source (but using `--with-pydebug`):

```
install_prefix=~/.local/python/3.8.0a3
./configure \
   --with-pydebug --enable-shared CFLAGS=-O3 \
   --prefix=${install_prefix} LDFLAGS=-Wl,-rpath=${install_prefix}/lib \
   --with-ensurepip=upgrade
```

Not sure if this is an upstream issue, since 3.8 is alpha, though?

Trying without `--with-pydebug CFLAGS=...`, adding in `--enable-optimizations`...

**Comment by susilehtola** [comment] 2019-07-11 09:43
Same problem with pybind-2.3.0.

**Comment by susilehtola** [comment] 2019-09-20 06:48
And also with pybind-2.4.0.

**Comment by susilehtola** [comment] 2019-09-20 06:51
This is getting to be a huge problem, since the next release of Fedora is going to ship with Python 3.8, and if pybind11 doesn't build it will be withdrawn from the distribution.

**Comment by wjakob** [comment] 2019-09-20 07:39
It's not a problem of pybind11, just a behavioral change of Python 3.8.

Fixed in https://github.com/pybind/pybind11/commit/21d0eb460f3d6932cbf9544d636d22080bf386b6 by just disabling that test.

**Closed by wjakob** 2019-09-20 07:39 UTC

**Comment by sizmailov** [comment] 2019-09-20 08:16
@wjakob  I think you refer to next paragraphs from [release notes](https://docs.python.org/3.8/whatsnew/3.8.html)

 > Functions that convert Python number to C integer like PyLong_AsLong() and argument parsing functions like PyArg_ParseTuple() with integer converting format units like 'i' will now use the __index__() special method instead of __int__(), if available. The deprecation warning will be emitted for objects with the __int__() method but without the __index__() method (like Decimal and Fraction). PyNumber_Check() will now return 1 for objects implementing __index__(). PyNumber_Long(), PyNumber_Float() and PyFloat_AsDouble() also now use the __index__() method if available. (Contributed by Serhiy Storchaka in bpo-36048 and bpo-20092.)

> Constructors of int, float and complex will now use the __index__() special method, if available and the corresponding method __int__(), __float__() or __complex__() is not available. (Contributed by Serhiy Storchaka in bpo-20092.)

And  https://docs.python.org/3.8/reference/datamodel.html#object.__index__ :

> Presence of __index__ method indicates that the numeric object is an integer type. Must return an integer.

This patch fixes the test

```diff
--- a/include/pybind11/pybind11.h
+++ b/include/pybind11/pybind11.h
@@ -1566,6 +1566,9 @@ public:
         #if PY_MAJOR_VERSION < 3
             def("__long__", [](Type value) { return (Scalar) value; });
         #endif
+        #if (PY_MAJOR_VERSION >= 3) && (PY_MINOR_VERSION >= 8)
+                def("__index__", [](Type value) { return (int   ) value; });
+        #endif
```

**Comment by wjakob** [comment] 2019-09-20 09:06
Indeed, that is a much nicer fix -- thank you. I made one change and cast to `Scalar` instead of `int` (the enum type might e.g. be a 64 bit integer, it's best to let C++ decide)

**Comment by wjakob** [comment] 2019-09-20 09:07
I will push out v2.4.1 with this fix.
