### ISSUE TITLE
Autocomplete method names not displaying in IDE/ PyCharm.

### ISSUE THREAD

**Issue by bugcy013** [pybind/pybind11#1504] opened 2018-08-28 15:56 UTC
Hi Guys,

We tried following example https://blog.conan.io/2016/04/12/Extending-python-with-C-or-C++-with-pybind11.html

we are able to run the example program. The issue is the method name autocomplete not happening. 

```
import sys
sys.path.append("/home/dhanasekaran/conan-pybind11/test_package")
import example
example.
```
when I press the tab method names not displaying. can you please guide me how to fix this.

```
$ ipython2 

In [1]: import example

In [2]: example.
                 example.add 
                 example.cpp 
                 example.so  


```
note:: when I try for ipython interpreter method names are getting displayed, for PyCharm not displaying

**Comment by bstaletic** [comment] 2018-09-10 09:32
Take a look at this: https://github.com/pybind/pybind11/pull/1405

**Comment by sizmailov** [comment] 2018-09-11 17:18
@bugcy013 PyCharm *can* investigate binary modules out of box, but there are two limitations:
 - PyCharm scans binary modules only at startup and builds so-called "stubs" (files with extension `.pyi`). So your module should be already in PYTHONPATH / site-packages / installed by pip / etc. 
 - It can't extract actual functions signatures (all functions/methods are parsed as `func(*args, **kwargs)`)

A workaround would be to write/generate `.pyi` files by yourself and mark directory with them as "Sources Root" (Right click on directory with stubs in project tree > "Mark Directory as" > "Sources Root").

Wring stubs by hand is cumbersome and error-prone. Fortunately pybind11 automatically generate descriptive docstrings. In my I have a script which generates stubs from docstrings and makes PyCharm (partially) understand my extension module. 

My poor script to generate stubs from pybind11 docstrings:(https://github.com/sizmailov/pyxmolpp2/blob/master/write_type_hints.py).

While pybind11 docstrings are good, but not perfect for this particular use case, so you may observe glitches in `.pyi` files generated by the (limited) script. Both could be sufficiently improved. 

At the same time PyCharm interpretation of .pyi files is not 100% complete, so some PyCharm functionality might be disabled for this reason. 

Hope you'll find this information helpful.

**Comment by felaugmar** [comment] 2019-01-17 04:06
I would like to set a behavior that is happening related to this issue:

Using the function `def_submodule` of the main module doesn't make the new module visible from PyCharm (it's like the new module does not even exist, but it's there).

PyCharm apparently only generates the stubs files for the main module 🤔.

**Comment by lonestarr** [comment] 2019-09-03 21:23
In my project, stubs for submodules all work now with the very last PyCharm version (**2019.2.1**), I tested with a recent previous version (2019.1.3) and it failed.

**Comment by pantaryl** [comment] 2019-09-24 22:58
I can additionally add that `enum_` was causing my PyCharm skeleton to fail its parsing. If I make a new class for each enum, add `static const uint32_t` variables, and use `class_` instead, the autocomplete works. This is running pybind11(v2.3.0) and PyCharm Community 2019.2.2

```
2019-09-24 18:10:16,625 [  12814]   INFO - .skeletons.PySkeletonGenerator - Skeleton for MyModule failed on C:\Python36\python.exe. stderr: --
Failed to process 'MyModule' while nothing yet: int() argument must be a string, a bytes-like object or a number, not 'dict'
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.2\helpers\generator3.py", line 856, in <module>
    if process_one(name, mod_file_name, False, subdir) == GenerationStatus.FAILED:
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.2\helpers\generator3.py", line 615, in process_one
    redo_module(name, mod_file_name, doing_builtins, mod_cache_dir, sdk_skeletons_dir)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.2\helpers\generator3.py", line 69, in redo_module
    r.redo(module_name, ".".join(mod_path[:-1]) in MODULES_INSPECT_DIR)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.2\helpers\pycharm_generator_utils\module_redeclarator.py", line 1041, in redo
    self.redo_class(out, item, item_name, 0, p_modname=p_name, seen=seen_classes, inspect_dir=inspect_dir)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.2\helpers\pycharm_generator_utils\module_redeclarator.py", line 784, in redo_class
    self.fmt_value(out, item, indent + 1, prefix=item_name + " = ")
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.2\helpers\pycharm_generator_utils\module_redeclarator.py", line 299, in fmt_value
    seen_values=seen_values)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.2\helpers\pycharm_generator_utils\module_redeclarator.py", line 262, in fmt_value
    if value in seen_values:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
-- 
```

My enum was declared as: 
```c++
    // Definition for MyType.
    pybind11::enum_<MyType>(m, "MyType")
        .value("Unknown", MyType_Unknown)
        .value("A",  MyType_A)
        .value("B",  MyType_B)
        .export_values();
```

When failing in the module_redeclarator.py of PyCharm, I printed out the following:
```
    seen_values = [{'Unknown': (MyType.Unknown, None), 'A': (MyType.A, None), 'B': (MyType.B, None)}, (MyType.Unknown, None)]
    p_value = (MyType.Unknown, None)
    CODE: for value in p_value:
        value = MyType.Unknown
    ... Exception!
```

It looks like however pybind11 is generating its enums is not playing nice with PyCharm.

**Comment by lonestarr** [comment] 2019-09-25 10:28
Maybe that's a regression: I use pybind 2.2.4, PyCharm 2019.2.1, with a virtual env based on Python 3.7.2, and my enums have correct stubs generated by PyCharm.
Also note that on the C++ side, all my enums are declared in the simplest way: `enum MyEnum { first =0, second, third };` (I mean no class or typedef keyword).

**Comment by pantaryl** [comment] 2019-09-25 15:50
Mine were using `typedef`.

I updated to pybind11 `v2.4.2` and now autocomplete is working without a problem, no additional changes on my side.

**Comment by YannickJadoul** [comment] 2020-07-07 18:11
Given that there's no further reaction to @sizmailov's extended answer (thanks for that!), and that I'm reading things are better after pybind11 and PyCharm updates, I'm closing this.

Please open a new issue if for some cases, this still goes wrong with recent PyCharm/pybind11 versions.

**Closed by YannickJadoul** 2020-07-07 18:11 UTC
