### ISSUE TITLE
Not possible to return unique pointer to pure virtual class

### ISSUE THREAD

**Issue by Munken** [pybind/pybind11#641] opened 2017-02-03 11:03 UTC
If I try to return a unique pointer to a pure virtual class it fails due to 
> return_value_policy = move, but the object is neither movable nor copyable!

However it if the class is not _pure_ virtual it works fine. Same for returning a shared pointer to it. 

Below is a minimal working example based on the [docs](http://pybind11.readthedocs.io/en/master/advanced/classes.html#overriding-virtual-functions-in-python)

```c++
#include <pybind11/pybind11.h>
namespace py = pybind11;

class Animal {
public:
    virtual ~Animal() { }
    virtual std::string go(int n_times) = 0;
};

class Dog : public Animal {
public:
    std::string go(int n_times) override {
        std::string result;
        for (int i=0; i<n_times; ++i)
            result += "woof! ";
        return result;
    }
};

class PyAnimal : public Animal {
public:
    /* Inherit the constructors */
    using Animal::Animal;

    /* Trampoline (need one for each virtual function) */
    std::string go(int n_times) override {
        PYBIND11_OVERLOAD_PURE(
                std::string, /* Return type */
                Animal,      /* Parent class */
                go,          /* Name of function in C++ (must match Python name) */
                n_times      /* Argument(s) */
        );
    }
};

std::unique_ptr<Animal> build_dog() {
    return std::unique_ptr<Animal>(new Dog{});
}

std::shared_ptr<Animal> build_shared_dog() {
    return std::shared_ptr<Animal>(new Dog{});
}

PYBIND11_PLUGIN(PyAUSA) {


    py::module m("PyAUSA", "Python bindings for AUSAlib");

    py::class_<Animal, PyAnimal /* <--- trampoline*/> animal(m, "Animal");
    animal
            .def(py::init<>())
            .def("go", &Animal::go);

    py::class_<Dog>(m, "Dog", animal)
            .def(py::init<>());

    m.def("build_dog", &build_dog);
    m.def("build_shared_dog", &build_shared_dog);

    return m.ptr();
}
```

Output:
```
In [1]: import PyAUSA

In [2]: PyAUSA.build_shared_dog()
Out[2]: <PyAUSA.Dog at 0x7fab45d1d7e0>

In [3]: PyAUSA.build_dog()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-d86cdac6dbbe> in <module>()
----> 1 PyAUSA.build_dog()

RuntimeError: return_value_policy = move, but the object is neither movable nor copyable!
```

**Comment by jkhoogland** [comment] 2017-02-03 15:17
Having the same problem.

I tried to use [this](https://github.com/pybind/pybind11/pull/607) to solve the issue, but it doesn't.

**Comment by jagerman** [comment] 2017-02-04 05:12
Is this with current master?  I can't reproduce it (but I *can* with the commit just before PR #607 was merged).

**Comment by jkhoogland** [comment] 2017-02-04 06:09
I created a seperate branch/[release](https://github.com/jkhoogland/pybind11/releases/latest) for my own stuff from PR [#607](https://github.com/pybind/pybind11/pull/607).
With that PR I hoped the issue would be resolved, but it didn't help, sadly enough.

**Comment by jkhoogland** [comment] 2017-02-04 06:31
I merged the PR in seperate branch as it was not yet in master, but that didn't solve it.
Still would ge the above RuntimeError.

I just tried to use my [fork](https://github.com/jkhoogland/pybind11/tree/2.0.1-20170204) with the current master 20170204, but now I am getting seg fault ...

Digging further.

**Comment by jagerman** [comment] 2017-02-04 06:38
Yes, I saw that too; it happens during destruction of the instance returned via the shared_ptr.  (I didn't dig into why it's happening.)

**Comment by jkhoogland** [comment] 2017-02-04 06:53
I did a clean build of my project against my [fork](https://github.com/jkhoogland/pybind11/tree/2.0.1-20170204) of the current master, and it seems to work. 

I'll have a further look tommorrow.

**Comment by Munken** [comment] 2017-02-04 19:06
Updating to the latest master solved the issue. Feel free to close.

**Comment by jkhoogland** [comment] 2017-02-04 21:28
yep, i have been running various tests, it works. thanks.

**Closed** 2017-03-02 21:45 UTC
