### ISSUE TITLE
Segfault when calling inherited class function

### ISSUE THREAD

**Issue by ksmit799** [pybind/pybind11#2082] opened 2020-01-18 07:43 UTC
## Issue description

When attempting to call the function of an inherited class (virtual or otherwise), the program immediately terminates with a segfault. The problem persists even when switching the parent class around, leaving the problem only to be within the binding or the base class. However, the base class behaves appropriately when constructed by itself, therefore I believe something is going wrong during the binding process. I have tested this on the latest master commit (07e225932235ccb0db5271b0874d00f086f28423) on both Windows 10 and macOS Catalina.

## Reproducible example code

[Project link](https://github.com/ksmit799/PyPlayground/tree/events)

The issue centres around two particular classes, both of which can be compiled outside of the project (no internal/external dependencies). `src_cpp/event/event_emitter.h` and `src_cpp/event/event.h`. `event.h` is required by `event_emitter.h` which is the problem file. `src_cpp/render/container.h` and `src_cpp/render/container.cpp` are examples of inheritance where the generated bindings cause a segfault (bindings can be found at the bottom of container.h).

### C++ Inheritance
**container.h**
`class Container : public virtual EventEmitter`

**container.cpp**
```c++
py::class_<Container, EventEmitter>(container, "Container")
    // Constructors.
    .def(py::init<>())
    // Functions & variables.
    .def("destroy", &Container::Destroy, "")
    .def("set_active", &Container::SetActive, "")
    .def("add_child", &Container::AddChild, "")
    .def("remove_child", &Container::RemoveChild, "")
    .def_readwrite("active", &Container::active_);
```

**event_emitter.cpp**
```c++
py::class_<EventEmitter>(event_emitter, "EventEmitter")
    // Constructors.
    .def(py::init<>())
    // Functions & variables.
    .def("on", &EventEmitter::On, "")
    .def("off", &EventEmitter::Off, "")
    .def("once", &EventEmitter::Once, "")
    .def("add_listener", &EventEmitter::AddListener, "")
    .def("remove_listener", &EventEmitter::RemoveListener, "")
    .def("remove_all_listeners", &EventEmitter::RemoveAllListeners, "")
    .def("emit", &EventEmitter::Emit, "")
    .def("emit_now", &EventEmitter::EmitNow, "");
```

**Example Python Calls**
```python
# Prints first argument given.
def test(args):
    print(args[0])

# Works as expected.
self.emitter = EventEmitter()
self.emitter.on("test", test)
self.emitter.emit_now("test", "hello world")

# Crashes with segfault.
self.cont = Container()
self.cont.on("test", test)
self.cont.emit_now("test", "hello world")
```

**Comment by YannickJadoul** [comment] 2020-07-26 23:55
I believe the virtual inheritance makes it a duplicate of #1545. Try adding `py::multiple_inheritance()` int `py::class_<Container, EventEmitter>(container, "Container", py::multiple_inheritance())`.

If that doesn't solve it, please reopen the issue!

**Closed by YannickJadoul** 2020-07-26 23:55 UTC
