### ISSUE TITLE
Build issue on linux(centos)

### ISSUE THREAD

**Issue by srinivasavaradan** [pybind/pybind11#1159] opened 2017-10-27 21:42 UTC
Hello, 

I downloaded pybind11 and ran the following steps as mentioned in the document - http://pybind11.readthedocs.io/en/master/basics.html

After installing the prerequisites, I do - 

mkdir build
cd build
cmake ..
make check -j 4

After successfully completing the step 'cmake ..' I get the below errors after step 'make check -j 4'-
 
make[3]: * [tests/test_cmake_build/CMakeFiles/test_subdirectory_embed] Error 1 make[2]: * [tests/test_cmake_build/CMakeFiles/test_subdirectory_embed.dir/all] Error 2 make[2]: *** Waiting for unfinished jobs....

make[1]: * [tests/CMakeFiles/check.dir/rule] Error 2 make: * [check] Error 2

I am not sure what this means or how to fix this. Can someone point me in the right direction or explain what is happening here?. 

Below is the complete log when I run 'make check -j 4'
"
Scanning dependencies of target test_subdirectory_embed Scanning dependencies of target test_subdirectory_target Scanning dependencies of target mock_install Scanning dependencies of target test_subdirectory_function -- Install configuration: "MinSizeRel" -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11 -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/detail -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/detail/internals.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/detail/class.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/detail/typeid.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/detail/descr.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/detail/common.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/detail/init.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/pybind11.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/cast.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/common.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/attr.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/iostream.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/eigen.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/options.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/pytypes.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/stl_bind.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/buffer_info.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/chrono.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/eval.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/stl.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/embed.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/numpy.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/operators.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/functional.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/include/pybind11/complex.h -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/share/cmake/pybind11/pybind11Config.cmake -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/share/cmake/pybind11/pybind11ConfigVersion.cmake -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/share/cmake/pybind11/FindPythonLibsNew.cmake -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/share/cmake/pybind11/pybind11Tools.cmake -- Installing: /mnt/home/srinivasa/python3_env/pybind11/build/mock_install/share/cmake/pybind11/pybind11Targets.cmake [ 0%] Built target mock_install Scanning dependencies of target pybind11_tests [ 2%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/pybind11_tests.cpp.o [ 5%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_buffers.cpp.o [ 8%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_builtin_casters.cpp.o [ 11%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_call_policies.cpp.o [ 14%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_callbacks.cpp.o [ 17%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_chrono.cpp.o [ 17%] Built target test_subdirectory_target Scanning dependencies of target pybind11_cross_module_tests [ 20%] Building CXX object tests/CMakeFiles/pybind11_cross_module_tests.dir/pybind11_cross_module_tests.cpp.o make[3]: * [tests/test_cmake_build/CMakeFiles/test_subdirectory_embed] Error 1 make[2]: [tests/test_cmake_build/CMakeFiles/test_subdirectory_embed.dir/all] Error 2 make[2]: Waiting for unfinished jobs.... [ 22%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_class.cpp.o [ 22%] Built target test_subdirectory_function [ 25%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_constants_and_functions.cpp.o [ 28%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_copy_move.cpp.o [ 31%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_docstring_options.cpp.o [ 34%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_enum.cpp.o [ 37%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_eval.cpp.o [ 40%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_exceptions.cpp.o [ 42%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_factory_constructors.cpp.o [ 45%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_iostream.cpp.o [ 48%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_kwargs_and_defaults.cpp.o [ 51%] Linking CXX shared module ../../tests/pybind11_cross_module_tests.cpython-36m-x86_64-linux-gnu.so [ 54%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_local_bindings.cpp.o [ 57%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_methods_and_attributes.cpp.o [ 60%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_modules.cpp.o [ 60%] Built target pybind11_cross_module_tests [ 62%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_multiple_inheritance.cpp.o [ 65%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_numpy_array.cpp.o [ 68%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_numpy_dtypes.cpp.o [ 71%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_numpy_vectorize.cpp.o [ 74%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_opaque_types.cpp.o [ 77%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_operator_overloading.cpp.o [ 80%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_pickling.cpp.o [ 82%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_pytypes.cpp.o [ 85%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_sequences_and_iterators.cpp.o [ 88%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_smart_ptr.cpp.o [ 91%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_stl.cpp.o [ 94%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_stl_binders.cpp.o [ 97%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_virtual_functions.cpp.o [100%] Linking CXX shared module ../../tests/pybind11_tests.cpython-36m-x86_64-linux-gnu.so ------ pybind11_tests.cpython-36m-x86_64-linux-gnu.so file size: 1807600 [100%] Built target pybind11_tests make[1]: * [tests/CMakeFiles/check.dir/rule] Error 2 make: *** [check] Error 2
"

**Comment by jagerman** [comment] 2017-10-28 00:32
It's a bit hard to tell from that output what's happening--it looks either truncated or reformatted.  Can you post the cmake invocation from a clean build directory, too (so that we can see how the project gets configured).

You can also try using `make VERBOSE=1` which will show the compilation commands being invoked; building without `-j 4` might also help figure out where the error is coming from.

**Comment by srinivasavaradan** [comment] 2017-10-28 01:20
So, I tried `make VERBOSE=1` and it builds without errors. Thanks. So the documentation recommends building with `make check -j 4`. I understand that `check` is the target to be built. But just by invoking `make VERBOSE=1` how does it know what to build? Thanks much.

**Comment by jagerman** [comment] 2017-10-28 01:32
Oops, that should have been `make check VERBOSE=1`.  (the `VERBOSE=1` just tells the cmake-generated makefiles to be noisy).

**Comment by srinivasavaradan** [comment] 2017-10-28 02:03
With `make check VERBOSE=1`  I still get errors. I'll post complete errors by tomorrow. I don't have email access on the server I am building and it is tedious to type in all the verbose text.

**Comment by srinivasavaradan** [comment] 2017-10-30 18:00
I'm using a python virtual environment. Below is the logs of cmake invocation and the verbose build logs:
 
**1. Cmake invocation logs :**

> 
(python3_env1) [user@lnxdev02 build]$ cmake ..
-- The CXX compiler identification is GNU 6.2.1
-- Check for working CXX compiler: /opt/rh/devtoolset-6/root/usr/bin/g++
-- Check for working CXX compiler: /opt/rh/devtoolset-6/root/usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /mnt/home/user/python3_env1/bin/python (found version "3.6.2")
-- Found PythonLibs: /usr/local/python-3.6.2/lib/libpython3.6m.a
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- Setting tests build type to MinSizeRel as none was specified
-- Building tests WITHOUT Eigen
-- Could NOT find Boost
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Catch not detected. Interpreter tests will be skipped. Install Catch headers manually or use `cmake -DDOWNLOAD_CATCH=1` to fetch them automatically.
-- pybind11 v2.3.dev0
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/lnxutil6/user/python3_env1/pybind11-master/build

 **I did  a Pytest download and here is the details for them -** 

> 
(python3_env1) [user@lnxdev02 build]$ /mnt/home/user/python3_env1/bin/python -m pip install pytest
Collecting pytest
  Downloading http://package_mirror.companyname.com/pypi/web/packages/fd/3e/d326a05d083481746a769fc051ae8d25f574ef140ad4fe7f809a2b63c0f0/pytest-3.1.3-py2.py3-none-any.whl (181kB)
    100% |████████████████████████████████| 184kB 39.8MB/s
Collecting py>=1.4.33 (from pytest)
  Downloading http://package_mirror.companyname.com/pypi/web/packages/53/67/9620edf7803ab867b175e4fd23c7b8bd8eba11cb761514dcd2e726ef07da/py-1.4.34-py2.py3-none-any.whl (84kB)
    100% |████████████████████████████████| 92kB 39.8MB/s
Requirement already satisfied: setuptools in /mnt/lnxutil6/user/python3_env1/lib/python3.6/site-packages (from pytest)
Installing collected packages: py, pytest
Successfully installed py-1.4.34 pytest-3.1.3

**2. Verbose make logs 'make check VERBOSE=1'**

> 
/usr/bin/cmake -H/mnt/lnxutil6/user/python3_env1/pybind11-master -B/mnt/lnxutil6/user/python3_env1/pybind11-master/build --check-build-system CMakeFiles/Makefile.cmake 0
make -f CMakeFiles/Makefile2 check
make[1]: Entering directory `/mnt/lnxutil6/user/python3_env1/pybind11-master/build'
/usr/bin/cmake -H/mnt/lnxutil6/user/python3_env1/pybind11-master -B/mnt/lnxutil6/user/python3_env1/pybind11-master/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /mnt/lnxutil6/user/python3_env1/pybind11-master/build/CMakeFiles 35
make -f CMakeFiles/Makefile2 tests/CMakeFiles/check.dir/all
make[2]: Entering directory `/mnt/lnxutil6/user/python3_env1/pybind11-master/build'
make -f tests/test_cmake_build/CMakeFiles/test_subdirectory_target.dir/build.make tests/test_cmake_build/CMakeFiles/test_subdirectory_target.dir/depend
make[3]: Entering directory `/mnt/lnxutil6/user/python3_env1/pybind11-master/build'
cd /mnt/lnxutil6/user/python3_env1/pybind11-master/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /mnt/lnxutil6/user/python3_env1/pybind11-master /mnt/lnxutil6/user/python3_env1/pybind11-master/tests/test_cmake_build /mnt/lnxutil6/user/python3_env1/pybind11-master/build /mnt/lnxutil6/user/python3_env1/pybind11-master/build/tests/test_cmake_build /mnt/lnxutil6/user/python3_env1/pybind11-master/build/tests/test_cmake_build/CMakeFiles/test_subdirectory_target.dir/DependInfo.cmake --color=
Dependee "/mnt/lnxutil6/user/python3_env1/pybind11-master/build/tests/test_cmake_build/CMakeFiles/test_subdirectory_target.dir/DependInfo.cmake" is newer than depender "/mnt/lnxutil6/user/python3_env1/pybind11-master/build/tests/test_cmake_build/CMakeFiles/test_subdirectory_target.dir/depend.internal".
Dependee "/mnt/lnxutil6/user/python3_env1/pybind11-master/build/tests/test_cmake_build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/mnt/lnxutil6/user/python3_env1/pybind11-master/build/tests/test_cmake_build/CMakeFiles/test_subdirectory_target.dir/depend.internal".
Scanning dependencies of target test_subdirectory_target
make[3]: Leaving directory `/mnt/lnxutil6/user/python3_env1/pybind11-master/build'
make -f tests/test_cmake_build/CMakeFiles/test_subdirectory_target.dir/build.make tests/test_cmake_build/CMakeFiles/test_subdirectory_target.dir/build
make[3]: Entering directory `/mnt/lnxutil6/user/python3_env1/pybind11-master/build'
cd /mnt/lnxutil6/user/python3_env1/pybind11-master/build/tests/test_cmake_build && /usr/bin/ctest --quiet --output-log subdirectory_target.log --build-and-test /mnt/lnxutil6/user/python3_env1/pybind11-master/tests/test_cmake_build/subdirectory_target /mnt/lnxutil6/user/python3_env1/pybind11-master/build/tests/test_cmake_build/subdirectory_target --build-config Release --build-noclean --build-generator Unix\ Makefiles  --build-makeprogram /usr/bin/gmake --build-target check --build-options -DCMAKE_PREFIX_PATH=/mnt/lnxutil6/user/python3_env1/pybind11-master/build/mock_install -DCMAKE_CXX_COMPILER=/opt/rh/devtoolset-6/root/usr/bin/g++ -DPYTHON_EXECUTABLE:FILEPATH=/mnt/home/user/python3_env1/bin/python -DPYBIND11_CPP_STANDARD=-std=c++14 -DPYBIND11_PROJECT_DIR=/mnt/lnxutil6/user/python3_env1/pybind11-master
make[3]: Leaving directory `/mnt/lnxutil6/user/python3_env1/pybind11-master/build'
[  0%] Built target test_subdirectory_target
make -f tests/test_cmake_build/CMakeFiles/test_subdirectory_embed.dir/build.make tests/test_cmake_build/CMakeFiles/test_subdirectory_embed.dir/depend
make[3]: Entering directory `/mnt/lnxutil6/user/python3_env1/pybind11-master/build'
cd /mnt/lnxutil6/user/python3_env1/pybind11-master/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /mnt/lnxutil6/user/python3_env1/pybind11-master /mnt/lnxutil6/user/python3_env1/pybind11-master/tests/test_cmake_build /mnt/lnxutil6/user/python3_env1/pybind11-master/build /mnt/lnxutil6/user/python3_env1/pybind11-master/build/tests/test_cmake_build /mnt/lnxutil6/user/python3_env1/pybind11-master/build/tests/test_cmake_build/CMakeFiles/test_subdirectory_embed.dir/DependInfo.cmake --color=
Dependee "/mnt/lnxutil6/user/python3_env1/pybind11-master/build/tests/test_cmake_build/CMakeFiles/test_subdirectory_embed.dir/DependInfo.cmake" is newer than depender "/mnt/lnxutil6/user/python3_env1/pybind11-master/build/tests/test_cmake_build/CMakeFiles/test_subdirectory_embed.dir/depend.internal".
Dependee "/mnt/lnxutil6/user/python3_env1/pybind11-master/build/tests/test_cmake_build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/mnt/lnxutil6/user/python3_env1/pybind11-master/build/tests/test_cmake_build/CMakeFiles/test_subdirectory_embed.dir/depend.internal".
Scanning dependencies of target test_subdirectory_embed
make[3]: Leaving directory `/mnt/lnxutil6/user/python3_env1/pybind11-master/build'
make -f tests/test_cmake_build/CMakeFiles/test_subdirectory_embed.dir/build.make tests/test_cmake_build/CMakeFiles/test_subdirectory_embed.dir/build
make[3]: Entering directory `/mnt/lnxutil6/user/python3_env1/pybind11-master/build'
cd /mnt/lnxutil6/user/python3_env1/pybind11-master/build/tests/test_cmake_build && /usr/bin/ctest --quiet --output-log subdirectory_embed.log --build-and-test /mnt/lnxutil6/user/python3_env1/pybind11-master/tests/test_cmake_build/subdirectory_embed /mnt/lnxutil6/user/python3_env1/pybind11-master/build/tests/test_cmake_build/subdirectory_embed --build-config Release --build-noclean --build-generator Unix\ Makefiles  --build-makeprogram /usr/bin/gmake --build-target check --build-options -DCMAKE_PREFIX_PATH=/mnt/lnxutil6/user/python3_env1/pybind11-master/build/mock_install -DCMAKE_CXX_COMPILER=/opt/rh/devtoolset-6/root/usr/bin/g++ -DPYTHON_EXECUTABLE:FILEPATH=/mnt/home/user/python3_env1/bin/python -DPYBIND11_CPP_STANDARD=-std=c++14 -DPYBIND11_PROJECT_DIR=/mnt/lnxutil6/user/python3_env1/pybind11-master
make[3]: *** [tests/test_cmake_build/CMakeFiles/test_subdirectory_embed] Error 1
make[3]: Leaving directory `/mnt/lnxutil6/user/python3_env1/pybind11-master/build'
make[2]: *** [tests/test_cmake_build/CMakeFiles/test_subdirectory_embed.dir/all] Error 2
make[2]: Leaving directory `/mnt/lnxutil6/user/python3_env1/pybind11-master/build'
make[1]: *** [tests/CMakeFiles/check.dir/rule] Error 2
make[1]: Leaving directory `/mnt/lnxutil6/user/python3_env1/pybind11-master/build'
make: *** [check] Error 2

**Comment by henryiii** [comment] 2017-10-30 18:34
Please surround multiline output with three tick-marks ```, that keeps the formatting easy to read. That's not a normal env for CentOS7, GCC 4.8 is the default.

Did you build it with make first? It looks to me like it's trying to run the test without building first - I don't think it's set up with the dependencies that way.

Also, finally, try `make pytest`. I've never tried `make check` with pybind11.

**Comment by henryiii** [comment] 2017-10-30 18:42
Ahh, I think that error comes from the fact you are in a virtual environment. Pybind11 can't detect a virtual environment when you are using the embedded interpreter, and `make check` does try to do the embedded test (which is the line that dies above).

**Comment by srinivasavaradan** [comment] 2017-10-30 18:47
Well, I did install this on a virtual environment and it did install file. However, I find this error in my work environment. I am not sure why.

**Comment by jagerman** [comment] 2017-10-30 21:43
My guess is that the issue is coming from:

> `Found PythonLibs: /usr/local/python-3.6.2/lib/libpython3.6m.a`

AFAICT we don't support linking in a static python; I've submitted PR #1162 that should hopefully avoid picking up the static libpython in the future.

It's either going to fix your build by finding the correct shared library or else break it, but at least if it breaks it it'll (hopefully) now be with a missing library error.

**Comment by jagerman** [comment] 2017-10-30 21:44
In the meantime, you can use `make -j4 pytest` to just run the ordinary module tests (without running the embedding tests, which are the part that is currently failing).

**Comment by srinivasavaradan** [comment] 2017-10-30 23:09
Thanks Jagerman. So, if we just maintain static lib, then would using pybin11 be a problem? Or is it specific to this embedded tests?

**Comment by jagerman** [comment] 2017-10-31 11:35
This only affects embedding. For regular module use everything should work fine (modules don't link to Python, but rather are built with missng symbols that get provided when the module is loaded by Python).

I don't know the answer to 2 if you want to embed statically.  I expect it is possible, but will take some effort.

**Comment by Jeff-avatar** [comment] 2020-07-12 05:05
Any solution to solve this issue? I have the same issue and I am on MacOs. @srinivasavaradan

**Comment by YannickJadoul** [comment] 2020-07-12 12:03
#1162 was closed because of complications (read further, there).

I'm closing this. Do reopen if this is still a problem (after almost 3 years without further discussion).

@Jeff-avatar Please open a new issue with a description of what goes wrong (and preferably a minimal example that we can try for ourselves). That's going to be easier to deal with.

**Closed by YannickJadoul** 2020-07-12 12:03 UTC

**Comment by Jeff-avatar** [comment] 2020-07-12 14:31
> #1162 was closed because of complications (read further, there).
> 
> I'm closing this. Do reopen if this is still a problem (after almost 3 years without further discussion).
> 
> @Jeff-avatar Please open a new issue with a description of what goes wrong (and preferably a minimal example that we can try for ourselves). That's going to be easier to deal with.

@YannickJadoul Thank you very much for your replay. I reopened an issue here, https://github.com/pybind/pybind11/issues/2295#issue-655411195.
