### ISSUE TITLE
[BUG] docs fail to build with sphinx 3.1/3.2

### ISSUE THREAD

**Issue by RizzerOnGitHub** [pybind/pybind11#2404] opened 2020-08-18 05:43 UTC
The pybind11 docs starting failing to build with Sphinx 3.1, and are still failing with sphinx 3.2

The problem was detected in Debian system builds and reported at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=963659
A build log is available at https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/pybind11.html or https://tests.reproducible-builds.org/debian/rbuild/unstable/amd64/pybind11_2.5.0-4.rbuild.log.gz

The docs build is launched with `make -C docs html` which triggers `sphinx-build -b html -d .build/doctrees   . .build/html`
The error might come from the definition of `str` in `include/pybind11/pytypes.h`, with a warning about "duplicate declaration" given.

The error message is

    /build/1st/pybind11-2.5.0/docs/reference.rst:52: WARNING: Duplicate C++ declaration, also defined in 'reference'.
    Declaration is 'str : public object'.
    /build/1st/pybind11-2.5.0/docs/reference.rst.rst:52: WARNING: C++ declarations inside functions are not supported. Parent function is str
    
    Exception occurred:
      File "/usr/lib/python3/dist-packages/breathe/renderer/sphinxrenderer.py", line 425, in run_directive
        rst_node = nodes[1]
    IndexError: list index out of range

A longer excerpt is

    /usr/bin/make -C docs html
    make[2]: Entering directory '/build/1st/pybind11-2.5.0/docs'
    sphinx-build -b html -d .build/doctrees   . .build/html
    Running Sphinx v3.2.1
    making output directory... done
    1.8.18
    /build/1st/pybind11-2.5.0/include/pybind11/operators.h:162: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
    /build/1st/pybind11-2.5.0/include/pybind11/pytypes.h:518: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
    /build/1st/pybind11-2.5.0/include/pybind11/detail/common.h:472: warning: Detected potential recursive class relation between class make_index_sequence_impl and base class make_index_sequence_impl< N - 1, N - 1, S... >!
    
    /build/1st/pybind11-2.5.0/include/pybind11/detail/common.h:472: warning: Detected potential recursive class relation between class make_index_sequence_impl and base class make_index_sequence_impl< N - 1, N - 1, S... >!
    
    /build/1st/pybind11-2.5.0/include/pybind11/detail/descr.h:57: warning: Detected potential recursive class relation between class int_to_str and base class int_to_str< Rem/10, Rem%10, Digits... >!
    
    /build/1st/pybind11-2.5.0/include/pybind11/detail/descr.h:57: warning: Detected potential recursive class relation between class int_to_str and base class int_to_str< Rem/10, Rem%10, Digits... >!
    
    /build/1st/pybind11-2.5.0/include/pybind11/cast.h:2164: warning: no uniquely matching class member found for 
      template < Derived >
      template < policy, Args >
      object object_api< Derived >::call(Args &&... args) const
    
    /build/1st/pybind11-2.5.0/include/pybind11/detail/common.h:588: warning: explicit link request to 'value' could not be resolved
    building [mo]: targets for 0 po files that are out of date
    building [html]: targets for 29 source files that are out of date
    updating environment: [new config] 29 added, 0 changed, 0 removed
    reading sources... [  3%] advanced/cast/chrono
    reading sources... [  6%] advanced/cast/custom
    reading sources... [ 10%] advanced/cast/eigen
    reading sources... [ 13%] advanced/cast/functional
    reading sources... [ 17%] advanced/cast/index
    reading sources... [ 20%] advanced/cast/overview
    reading sources... [ 24%] advanced/cast/stl
    reading sources... [ 27%] advanced/cast/strings
    reading sources... [ 31%] advanced/classes
    reading sources... [ 34%] advanced/embedding
    reading sources... [ 37%] advanced/exceptions
    reading sources... [ 41%] advanced/functions
    reading sources... [ 44%] advanced/misc
    reading sources... [ 48%] advanced/pycpp/index
    reading sources... [ 51%] advanced/pycpp/numpy
    reading sources... [ 55%] advanced/pycpp/object
    reading sources... [ 58%] advanced/pycpp/utilities
    reading sources... [ 62%] advanced/smart_ptrs
    reading sources... [ 65%] basics
    reading sources... [ 68%] benchmark
    reading sources... [ 72%] changelog
    reading sources... [ 75%] classes
    reading sources... [ 79%] compiling
    reading sources... [ 82%] faq
    reading sources... [ 86%] index
    reading sources... [ 89%] intro
    reading sources... [ 93%] limitations
    reading sources... [ 96%] reference
    /build/1st/pybind11-2.5.0/docs/reference.rst:52: WARNING: Duplicate C++ declaration, also defined in 'reference'.
    Declaration is 'str : public object'.
    /build/1st/pybind11-2.5.0/docs/reference.rst.rst:52: WARNING: C++ declarations inside functions are not supported. Parent function is str
    
    Exception occurred:
      File "/usr/lib/python3/dist-packages/breathe/renderer/sphinxrenderer.py", line 425, in run_directive
        rst_node = nodes[1]
    IndexError: list index out of range
    The full traceback has been saved in /tmp/sphinx-err-1ldwicyo.log, if you want to report the issue to the developers.
    Please also report this if it was a user error, so that a better error message can be provided next time.
    A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
    make[2]: *** [Makefile:55: html] Error 2
    make[2]: Leaving directory '/build/1st/pybind11-2.5.0/docs'

**Comment by RizzerOnGitHub** [comment] 2020-08-18 05:54
Attaching here a copy of the sphinx error log mentioned in the build log, though I'm not certain it shines much more light.

[sphinx-err-pybind11.log](https://github.com/pybind/pybind11/files/5088453/sphinx-err-pybind11.log)

**Comment by bstaletic** [comment] 2020-08-18 07:18
Hm... I could not reproduce the error locally.

```
Running Sphinx v3.2.0
making output directory... done
1.8.18
/home/bstaletic/work/pybind11/include/pybind11/operators.h:165: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
/home/bstaletic/work/pybind11/include/pybind11/pytypes.h:532: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
/home/bstaletic/work/pybind11/include/pybind11/detail/common.h:489: warning: Detected potential recursive class relation between class make_index_sequence_impl and base class make_index_sequence_impl< N - 1, N - 1, S... >!

/home/bstaletic/work/pybind11/include/pybind11/detail/common.h:489: warning: Detected potential recursive class relation between class make_index_sequence_impl and base class make_index_sequence_impl< N - 1, N - 1, S... >!

/home/bstaletic/work/pybind11/include/pybind11/detail/descr.h:57: warning: Detected potential recursive class relation between class int_to_str and base class
int_to_str< Rem/10, Rem%10, Digits... >!

/home/bstaletic/work/pybind11/include/pybind11/detail/descr.h:57: warning: Detected potential recursive class relation between class int_to_str and base class
int_to_str< Rem/10, Rem%10, Digits... >!

/home/bstaletic/work/pybind11/include/pybind11/cast.h:2195: warning: no uniquely matching class member found for
  template < Derived >
  template < policy, Args >
  object object_api< Derived >::call(Args &&... args) const

/home/bstaletic/work/pybind11/include/pybind11/detail/common.h:605: warning: explicit link request to 'value' could not be resolved
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 29 source files that are out of date
updating environment: [new config] 29 added, 0 changed, 0 removed
reading sources... [100%] upgrade
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] upgrade
generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [100%] pybind11-logo.png
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in .build/html.
```

**Comment by YannickJadoul** [comment] 2020-08-18 13:24
What version of Breathe are you both using?

**Comment by YannickJadoul** [comment] 2020-08-18 13:29
OK, according to the logs, @RizzerOnGitHub is using Breathe 4.19.2, which is the latest, but the crash seems to occur there.
Seems we are currently using 4.5.0: https://github.com/pybind/pybind11/blob/master/docs/requirements.txt

Could you give that a try, @RizzerOnGitHub?

**Comment by RizzerOnGitHub** [comment] 2020-08-18 14:54
No, the logs suggest breathe is not the problem, in the sense that the docs build successfully in the testing suite (bullseye) with pybind11 2.5.0-4, breathe 4.14.1-2 and sphinx 2.4.3-4.  Build log at https://tests.reproducible-builds.org/debian/rbuild/bullseye/amd64/pybind11_2.5.0-4.rbuild.log.gz

But forcing an installation of the same breathe 4.14.1-2 on the unstable suite with sphinx 3.2.1-1 get more or less the same error as with breathe 4.19.2-2:

    /usr/bin/make -C docs html
    make[2]: Entering directory '/home/projects/python/build/pybind11/docs'
    sphinx-build -b html -d .build/doctrees   . .build/html
    Running Sphinx v3.2.1
    making output directory... done
    1.8.18
    /home/projects/python/build/pybind11/include/pybind11/operators.h:162: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
    /home/projects/python/build/pybind11/include/pybind11/pytypes.h:518: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
    /home/projects/python/build/pybind11/include/pybind11/detail/common.h:472: warning: Detected potential recursive class relation between class make_index_sequence_impl and base class make_index_sequence_impl< N - 1, N - 1, S... >!
    
    /home/projects/python/build/pybind11/include/pybind11/detail/common.h:472: warning: Detected potential recursive class relation between class make_index_sequence_impl and base class make_index_sequence_impl< N - 1, N - 1, S... >!
    
    /home/projects/python/build/pybind11/include/pybind11/detail/descr.h:57: warning: Detected potential recursive class relation between class int_to_str and base class int_to_str< Rem/10, Rem%10, Digits... >!
    
    /home/projects/python/build/pybind11/include/pybind11/detail/descr.h:57: warning: Detected potential recursive class relation between class int_to_str and base class int_to_str< Rem/10, Rem%10, Digits... >!
    
    /home/projects/python/build/pybind11/include/pybind11/cast.h:2164: warning: no uniquely matching class member found for
      template < Derived >
      template < policy, Args >
      object object_api< Derived >::call(Args &&... args) const
    
    /home/projects/python/build/pybind11/include/pybind11/detail/common.h:588: warning: explicit link request to 'value' could not be resolved
    building [mo]: targets for 0 po files that are out of date
    building [html]: targets for 29 source files that are out of date
    updating environment: [new config] 29 added, 0 changed, 0 removed
    reading sources... [  3%] advanced/cast/chrono
    reading sources... [  6%] advanced/cast/custom
    reading sources... [ 10%] advanced/cast/eigen
    reading sources... [ 13%] advanced/cast/functional
    reading sources... [ 17%] advanced/cast/index
    reading sources... [ 20%] advanced/cast/overview
    reading sources... [ 24%] advanced/cast/stl
    reading sources... [ 27%] advanced/cast/strings
    reading sources... [ 31%] advanced/classes
    reading sources... [ 34%] advanced/embedding
    reading sources... [ 37%] advanced/exceptions
    reading sources... [ 41%] advanced/functions
    reading sources... [ 44%] advanced/misc
    reading sources... [ 48%] advanced/pycpp/index
    reading sources... [ 51%] advanced/pycpp/numpy
    reading sources... [ 55%] advanced/pycpp/object
    reading sources... [ 58%] advanced/pycpp/utilities
    reading sources... [ 62%] advanced/smart_ptrs
    reading sources... [ 65%] basics
    reading sources... [ 68%] benchmark
    reading sources... [ 72%] changelog
    reading sources... [ 75%] classes
    reading sources... [ 79%] compiling
    reading sources... [ 82%] faq
    reading sources... [ 86%] index
    reading sources... [ 89%] intro
    reading sources... [ 93%] limitations
    reading sources... [ 96%] reference
    
    Exception occurred:
      File "/usr/lib/python3/dist-packages/sphinx/domains/c.py", line 3166, in object_type
        raise NotImplementedError()
    NotImplementedError
    The full traceback has been saved in /tmp/sphinx-err-xgusinqw.log, if you want to report the issue to the developers.
    Please also report this if it was a user error, so that a better error message can be provided next time.
    A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
    make[2]: *** [Makefile:55: html] Error 2
    make[2]: Leaving directory '/home/projects/python/build/pybind11/docs'

Possibly the interplay between sphinx 3 and breathe is to blame.  I can't test breathe 4.5.0 directly (with sphinx 3.2.1) since it gives an error,

    Running Sphinx v3.2.1
    
    Exception occurred:
      File "/usr/lib/python3/dist-packages/breathe/node_factory.py", line 5, in <module>
        import sphinx.ext.mathbase
    ModuleNotFoundError: No module named 'sphinx.ext.mathbase'

**Comment by bstaletic** [comment] 2020-08-18 16:00
> What version of Breathe are you both using?

```
bstaletic@Gallifrey ~ % pacman -Qs sphinx | grep local | head -n2
local/python-breathe 4.19.2-1
local/python-sphinx 3.2.0-1
```

**Comment by RizzerOnGitHub** [comment] 2020-08-18 16:06
In principle same version of breathe here, 

    $ dpkg -l python3-breathe python3-sphinx
    Desired=Unknown/Install/Remove/Purge/Hold
    | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
    |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
    ||/ Name            Version      Architecture Description
    +++-===============-============-============-====================================================================
    ii  python3-breathe 4.19.2-2     all          Sphinx autodox support for languages with doxygen support (Python 3)
    ii  python3-sphinx  3.2.1-1      all          documentation generator for Python projects

**Comment by YannickJadoul** [comment] 2020-08-18 16:07
> No, the logs suggest breathe is not the problem, in the sense that the docs build successfully in the testing suite (bullseye) with pybind11 2.5.0-4, breathe 4.14.1-2 and sphinx 2.4.3-4. Build log at https://tests.reproducible-builds.org/debian/rbuild/bullseye/amd64/pybind11_2.5.0-4.rbuild.log.gz

In the log from this comment: https://github.com/pybind/pybind11/issues/2404#issuecomment-675268851, there's a lot of Breathe on the stack.

> But forcing an installation of the same breathe 4.14.1-2 on the unstable suite with sphinx 3.2.1-1 gives an error comparable to that with breathe 4.19.2-2:

OK, that's interesting.

> Possibly the interplay between sphinx 3 and breathe is to blame. I can't test breathe 4.5.0 directly (with sphinx 3.2.1) since it gives an error,

I've just updated sphinx and breathe through pip, and I get this error message, though:

`breathe 4.19.2 requires Sphinx<3.2,>=3.0, but you'll have sphinx 3.2.1 which is incompatible.`

**Comment by bstaletic** [comment] 2020-08-18 16:22
Interestingly, I've just tried sphinx 3.2.1 in a clean venv and the build still passed.

**Comment by RizzerOnGitHub** [comment] 2020-08-18 16:22
Curious. Debian's breathe was just recently updated to 4.19 in order to help the transition to sphinx 3. Debian applies patches from https://salsa.debian.org/sramacher/breathe/-/tree/master/debian/patches , but nothing special there about versions. It looks like the sphinx<3.2 requirement is just being ignored. Maybe the problem here is unforeseen collateral damage.

The breathe 4.14 error is known (NotImplementedError). It indicates the given version of sphinx is too new for the given version of breathe. Debian manages that by having sphinx 3.1.2-1 and later declare Breaks: python3-breathe (<< 4.15), with the issue raised in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=963653

**Comment by RizzerOnGitHub** [comment] 2020-08-18 16:28
A new release of breathe might clear the air, https://github.com/michaeljones/breathe/issues/565

**Comment by YannickJadoul** [comment] 2020-08-18 19:29
Have you tried like @bstaletic, with just a clean virtualenv? And maybe installing through pip?

> A fresh release of breathe might clear the air, [michaeljones/breathe#565](https://github.com/michaeljones/breathe/issues/565)

Not sure if intended, but great pun ;-)

**Comment by vermeeren** [comment] 2020-08-19 22:32
Hi, just letting you know breathe v4.20.0 was just released, you may want to try again.

**Comment by RizzerOnGitHub** [comment] 2020-08-20 02:37
Thanks @vermeeren , I've asked the Debian breathe maintainer to upload it for us.

**Comment by RizzerOnGitHub** [comment] 2020-08-21 02:51
No, still no good. A debian build still fails the same way with python3-breathe 4.20.0-1.

**Comment by henryiii** [comment] 2020-08-26 16:51
Everything is working on latest version (see docs/requirements.txt) now in CI, this should be fixed?

**Comment by RizzerOnGitHub** [comment] 2020-08-26 17:45
The latest version that is working, is that the pybind11 2.5.0 release version, or latest git head?  It's 2.5.0 that I've been testing.

**Comment by henryiii** [comment] 2020-08-26 18:44
Latest, 2.5.0 definitely didn't support the latests Breathe/sphinx back when it was released (never tried with 4.20, for example). There were lots of improvements during the CI work.

**Comment by bstaletic** [comment] 2020-08-26 19:37
For the record, I was trying with the latest master, instead of pybind11 2.5.0 above.

**Comment by RizzerOnGitHub** [comment] 2020-08-27 05:32
That makes more sense then: the issue has been fixed in master.
Are you expecting the next release soon, or should I push git HEAD to debian?

**Comment by YannickJadoul** [comment] 2020-08-27 10:25
There's still a few issues pending for the next release, as far as I know (definitely @henryiii will want to finish his rework of the build system, I expect).

Is there a reason the Debian package needs to urgently build pybind11's docs? Building the docs is mostly meant for development and readthedocs.org/, no?

**Comment by RizzerOnGitHub** [comment] 2020-08-27 16:49
It's not that the docs are urgent as such, just that it's standard practice to include them in packages where feasible. The motivation is to allow Debian systems to be able to be installed (e.g. installed using local copies of packages) and run self-contained without direct internet.  The build failure was flagged when sphinx 3.2.1 was recently packaged, and we treat build failures as Release Critical. Push come to shove we can disable the docs temporarily if necessary while waiting for your next release.

**Comment by YannickJadoul** [comment] 2020-08-27 18:18
@henryiii Is there a way to rebase the strictly necessary changes onto 2.5.0 (either to give to Debian as temporary patch, or to release 2.5.1) ?

**Comment by henryiii** [comment] 2020-08-27 18:55
I'm not totally sure what the strictly necessary changes were, actually - I was keeping it up with an old version of everything until recently, when I discovered it worked with latest. I can verify it is broken on v2.5.0 and not master.

However, if you want to just patch it to get ti to pass, what about just commenting out the api docs for pytypes for now?

```diff
-.. doxygengroup:: pytypes
-    :members:
+.. .. doxygengroup:: pytypes
+..     :members:
```

That lets it build, and 2.6.0 shouldn't be too far away, hopefully. (Possibly a note should be added that the patch is not needed for the next version).

**Comment by RizzerOnGitHub** [comment] 2020-08-28 02:46
Thanks Henry, I'll patch out pytypes for the time being as you suggest.

**Comment by bstaletic** [comment] 2020-09-12 22:12
This seems resolved. @RizzerOnGitHub feel free to open a new issue if you run into more troubles.

**Closed by bstaletic** 2020-09-12 22:12 UTC
