### ISSUE TITLE
[BUG] FindPythonLibsNew.cmake will not search for the interpreter if find_package(Python ...) has already been invoked

### ISSUE THREAD

**Issue by xinyazhang** [pybind/pybind11#2673] opened 2020-11-18 03:52 UTC
## Issue description

The following piece of CMake code will cause pybind11 to complain `Python3 was found without the Interpreter component.  Pybind11 requires this component.`
```
find_package(Python3 COMPONENTS Development)
add_subdirectory(third-party/pybind11/)
```
This issue occurs in v2.6.1.
The problem can be resolved by adding `Interpreter` at the first line.
However the error message is confusing and the resolution only gets clear after reading the code of `FindPythonLibsNew.cmake`.

## Reproducible example code

```
CMAKE_MINIMUM_REQUIRED(VERSION 3.12)

project(test CXX)
find_package(Python3 COMPONENTS Development)
add_subdirectory(third-party/pybind11/) # Requires v2.6.1
```

**Comment by YannickJadoul** [comment] 2020-11-18 12:08
How is this confusing? Doesn't this state exactly what the problem is, a missing component of the `Python3` package that pybind11 requires?

> Python3 was found without the Interpreter component. Pybind11 requires this component.

What more do you expect, then?

>  However the error message is confusing and the resolution only gets clear after reading the code of `FindPythonLibsNew.cmake`.

I don't think that's actually related. I think that file is related to the old CMake framework, and since you use the new `FindPython`, that file should be irrelevant (right, @henryiii?).

**Comment by henryiii** [comment] 2020-11-18 14:24
> the error message is confusing

to me, on reading "Python3 was found without the Interpreter component. Pybind11 requires this component", the natural resolution would be "The problem can be resolved by adding Interpreter at the first line.". I helped write that line, but it sounds to me like that's exactly what it is saying.

 > FindPythonLibsNew.cmake

This file has nothing at all to do with FindPython. It's a set of hacks sitting on top of FindPythonLibs, the classic search algorithm.

Be the way, before 2.6.2 is released you might have some issues with FindPython3 - see https://github.com/pybind/pybind11/pull/2662 . A solution would be to use `find_package(Python VERSION 3)` instead.

**Closed** 2020-11-18 14:47 UTC

**Comment by xinyazhang** [comment] 2020-11-25 04:27
> the natural resolution would be "The problem can be resolved by adding Interpreter at the first line.". I helped write that line, but it sounds to me like that's exactly what it is saying.

The problem is, when the project becomes larger, it is not that easy to locate a `find_package(Python3)` or `find_package(Python VERSION 3)` in a hierarchy of CMakeLists.txt.

Furthermore, if I removed the `find_package`, pybind11 will be able to locate Python Interpreter without any trouble, because pybind11 itself will [try to find Python Interpreter](https://github.com/pybind/pybind11/blob/f1abf5d9159b805674197f6bc443592e631c9130/tools/pybind11NewTools.cmake#L33), but this action will be cancelled if `Python_FOUND`, `Python3_FOUND` or `Python2_FOUND` is set.

This is confusing, because a perfectly working configuration for pybind11 may suddenly break because some other module in the build system called `find_package(Python3)` to serve its own dependencies.

A quick and dirty fix to this situation is to call `find_package(Python REQUIRED COMPONENTS Interpreter Development ${_pybind11_quiet})` unconditionally.

**Comment by henryiii** [comment] 2020-11-25 13:28
>  quick and dirty fix to this situation is to call find_package(Python REQUIRED COMPONENTS Interpreter Development ${_pybind11_quiet}) unconditionally.

This would _depend on CMake version_, as it was added in CMake 3.12 (we support 3.4+), and becomes drastically better at least till 3.18. So you'd be trading something you have control over (CMakeLists) to a user's CMake version. This would be awful and users would have indeterminate behavior based on CMake version.

> This is confusing, because a perfectly working configuration for pybind11 may suddenly break because some other module in the build system called find_package(Python3) to serve its own dependencies.

So you'd rather find two potentially different python versions? Re-calling `find_package(Python3)` is a) very slow, and b) repeats the search (which is why it is slow). It may find a different Python, for example PyPy instead since the second time it might have a different hints. If a package finds Python, then you should use that, and not repeat the search - which is exactly what we do. If Python is found, we reuse that.

The real problem is `find_package(X)` should not find Python globally as part of finding X - that should be controlled by the user directly with `find_package(Python ...)`. But the old FindPythonInterp/FindPythonLibs was so bad that pybind11 ended up needing to add hacks onto the discovery to be remotely usable. This is also why CMake completely redesigned it into FindPython. "Good" packages should respect the current "FindPython" result, and only search if they _have_ to.

**Comment by YannickJadoul** [comment] 2020-11-25 14:03
> A quick and dirty fix to this situation is to call `find_package(Python REQUIRED COMPONENTS Interpreter Development ${_pybind11_quiet})` unconditionally.

If it's that simple, you could just unconditionally call it yourself, before adding `pybind11` to the project. As you said, when they are set, pybind11 won't try to override a manually found Python installation.

So:
- If `find_package(Python)` can be called multiple times in your case: no problem, you can do it yourself, before `find_package(pybind11)` or `add_subdirectory(pybind11)`. The advice in the docs is also to do this explicitly (as I found out recently); pybind11 is a remainder from before the new `FindPython`.
- If `find_package(Python)` cannot be called multiple times, you have to unite them anyway, so pybind11 is doing the right thing by refusing.

(Does this reasoning make sense, @henryiii? I was already writing this before your answer appeared.)

**Comment by henryiii** [comment] 2020-11-25 14:37
Yes. If the first time you call it you don't have Development enabled, I bet you are okay with possibly finding a different Python later (just a guess, as it really depends on what you are doing with it). As a library, however, we can't make guesses like this.
