### ISSUE TITLE
Pybind always move objects of type std::optional

### ISSUE THREAD

**Issue by armandoeng** [pybind/pybind11#1919] opened 2019-09-11 12:13 UTC
If a container has an optional attribute, that attribute will always be moved.

In the code below, I found that the optional_caster override the policy. For reasons unknown to me, it is always overriding to move. Removing that line solves the problem.

## Example code

The custom_optional_caster is equals to the optional_caster, but with a removed line.
``` cpp
#include <pybind11/pybind11.h>
#include <pybind11/operators.h>

#include <optional>
//#undef PYBIND11_CPP17
#include <pybind11/stl.h>

namespace py = pybind11;

PYBIND11_MAKE_OPAQUE(std::vector<double>);

namespace pybind11{
namespace detail{

// This type caster is intended to be used for std::optional and std::experimental::optional
template<typename T> struct custom_optional_caster {
    using value_conv = make_caster<typename T::value_type>;

    template <typename T_>
    static handle cast(T_ &&src, return_value_policy policy, handle parent) {
        if (!src)
            return none().inc_ref();
//        policy = return_value_policy_override<typename T::value_type>::policy(policy);
        return value_conv::cast(*std::forward<T_>(src), policy, parent);
    }

    bool load(handle src, bool convert) {
        if (!src) {
            return false;
        } else if (src.is_none()) {
            return true;  // default-constructed value is already empty
        }
        value_conv inner_caster;
        if (!inner_caster.load(src, convert))
            return false;

        value.emplace(cast_op<typename T::value_type &&>(std::move(inner_caster)));
        return true;
    }

    PYBIND11_TYPE_CASTER(T, _("Optional[") + value_conv::name + _("]"));
};

#ifndef PYBIND11_CPP17
template<typename T> struct type_caster<std::optional<T>>
: public custom_optional_caster<std::optional<T>> {};

template<> struct type_caster<std::nullopt_t>
    : public void_caster<std::nullopt_t> {};

#endif

}
}

struct FooA{
    std::vector<double> my_vector {};
};

struct FooB {
    std::optional<FooA> my_container{};
};

void exportOptionalIssue(py::module &m) {
    py::class_<FooA>(m, "FooA")
        .def(py::init<>())
        .def_readwrite("my_vector", &FooA::my_vector);

    py::class_<FooB>(m, "FooB")
        .def(py::init<>())
        .def_readwrite("my_container", &FooB::my_container);
}
```

The tests were made to be used with pytest. This first shows that FooA works well.
``` python
def test_FooA():
    fooA = FooA()
    assert not fooA.my_vector
    my_vector = fooA.my_vector
    assert not my_vector

    my_vector.append(1)
    assert fooA.my_vector[0] == 1

    del my_vector
    assert fooA.my_vector[0] == 1

    my_vector = fooA.my_vector
    del fooA
    assert my_vector[0] == 1
```
This second test should work if using the custom_optional_caster.
``` python
def test_OptionalIssues():
    fooB = FooB()
    assert fooB.my_container is None
    fooB.my_container = FooA()
    assert fooB.my_container is not None
    fooB.my_container.my_vector.append(1)
    assert fooB.my_container.my_vector[0] == 1
    my_vector = fooB.my_container.my_vector
    assert my_vector[0] == 1
    assert fooB.my_container.my_vector[0] == 1
    del my_vector
    assert fooB.my_container.my_vector[0] == 1
    
    fooA = fooB.my_container
    del fooB
    assert fooA.my_vector[0] == 1
```

**Comment by potpath** [comment] 2019-11-23 10:11
I'm having the same issue with master, but cannot reproduce with the above code.
Here is a minimal reproducible example code that works for me.
```c++
#include <optional>
#include <vector>

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

struct Movable
{
  std::vector<int> vec;
};

struct Foo
{
  std::optional<Movable> member{{{1}}};  // this fails
  //Movable member{{1}};  // change to this works
  //std::optional<std::vector<int>> member{{1}};  // this also works
};

PYBIND11_MODULE(example, m)
{
  py::class_<Movable>(m, "Movable")
    .def("__len__", [](Movable& self){ return self.vec.size(); });

  py::class_<Foo>(m, "Foo")
    .def(py::init<>())
    .def_readonly("member", &Foo::member);  // this fails
    //.def_property_readonly("member", [](Foo& self){ return self.member; });  // change to this works
}
```
```python
import example

def test():
    foo = example.Foo()
    assert len(foo.member) == 1
    assert len(foo.member) == 1
```

Note that it is not reproducible with `std::optional<std::vector<int>>`.

Removing this line https://github.com/pybind/pybind11/blob/bd24155b8bf798f9f7022b39acd6d92e52d642d6/include/pybind11/stl.h#L269 also makes the test pass, as stated above.

**Comment by armandoeng** [comment] 2019-11-23 14:22
> I'm having the same issue with master, but cannot reproduce with the above code.
> Here is a minimal reproducible example code that works for me.
 
Yes, my posted code is not fully functional, as it is only a snippet of my original code. My bad to not mention it and to not post it fully. Thanks for your time and to put it on a simpler and easier form. 

I believe is lacking this on my code:
```
PYBIND11_MODULE(example, m)
{
   exportOptionalIssue(m);
}
```

> >  //.def_property_readonly("member", [](Foo& self){ return self.member; });  // change to this works

I'm using that hack on my original code on reaktoro to make it work. Well noticed.

**Comment by fatvlady** [comment] 2020-01-29 23:33
Hey
Having the same issue here.
It seems to me that `std::optional<std::vector<int>>` works despite vector being movable because there is a converter mechanism for vector instead of opaque type cast.

What seems to be a proper fix is not commenting out the line but the following:
```c++
if (!src)
    return none().inc_ref();
using dereference_type = decltype(*std::forward<T_>(src));
policy = return_value_policy_override<dereference_type>::policy(policy);
return value_conv::cast(*std::forward<T_>(src), policy, parent);
```
Should be easy fix. @armandoeng do you mind coming with a PR?

**Comment by YannickJadoul** [comment] 2020-07-07 18:53
Fixed on `master`, so a future patch release will contain these fixes.

**Closed by YannickJadoul** 2020-07-07 18:53 UTC
