### ISSUE TITLE
question on memory management, custom constructors

### ISSUE THREAD

**Issue by rhl-** [pybind/pybind11#182] opened 2016-04-27 22:17 UTC
Hi, in the documentation you have this: 

http://pybind11.readthedocs.org/en/latest/advanced.html#custom-constructors

I'm trying to debug some issues with my bindings, and something I don't understand are constructor bindings that look like this:

```
 py::class_<Example>(m, "Example")
     .def("__init__",
         [](Example &instance, int arg) {
             new (&instance) Example(arg);
         }
     );
```

What I don't understand is how/why ``Example& instance`` is an input to the constructor. In particular, this implies that you are constructing an instance of Example somewhere in the bindings, and then we overwrite that instance by explicitly calling `new.`

I don't understand why this is necessary, or what is happening behind the scenes. To try and understand on my own, I took one of my bindings, and started playing around with Example& instance, within the constructor binding. 

For example, on my simplex object I tried these things:
 ```
.def("__init__",
      [](Simplex &instance, const std::vector<v>& arg) {
          instance = s(std::begin(arg), std::end(arg));
     })
```
 ```
.def("__init__",
      [](Simplex &instance, const std::vector<v>& arg) {
          instance = std::move(s(std::begin(arg), std::end(arg)));
     })
```
Which seems to cause segmentation faults:
```
In [6]: ctl.Abstract_simplex([1,2,3])
python(21990,0x7fff78ac6000) malloc: *** error for object 0x3000000000000000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```
I can't understand why this happens?

For example, wouldn't this by safer, and do less instantiating: ?
```
[](int arg) {
     return Example(arg);
}
```

The documentation says this:

> In other words, init() creates an anonymous function that invokes an in-place constructor. Memory allocation etc. is already take care of beforehand within pybind11.

But, I don't understand it, because I clearly must call `new` myself, and if I don't, do exactly as documented, it seems there is a segmentation fault.

I'm struggling to find the implementations of these things in pybind11, maybe you can just point me at them? 

The reason I am asking is that in my project I have the following issue: 

```
In [7]: bd = ctl.Simplex_boundary()
In [8]: bd([1,2,3])
Out[8]: < at 0x103331458>
In [9]: x = bd([1,2,3])
In [11]: for elt in x:
....:     print elt #it doesn't seem to matter what happens here..
Segmentation fault: 11

```
The code for the call operator is:
```
   .def("__call__", [](const Boundary &bd, const Simplex& smplx) {
        return py::make_iterator(bd.begin(smplx), bd.end(smplx));
    }, py::keep_alive<0, 1>())
```

And I thought that by issuing ``py::keep_alive<0,1>()`` I tied the lifetime of the input to the output. Is this the wrong thing to do?

**Comment by rhl-** [comment] 2016-04-27 23:16
Ah, ok, to expand on my issue, I see two parts of my problem, which is that my iterators in this case are input iterators:

```
In [3]: bd = ctl.Simplex_boundary()
In [4]: s = ctl.Abstract_simplex([1,2,3])
In [5]: [x for x in bd(s)]
Out[5]:
[<ctl.Term_Simplex_Z2 at 0x10f909ce0>,
 <ctl.Term_Simplex_Z2 at 0x10f909ce0>,
 <ctl.Term_Simplex_Z2 at 0x10f909ce0>]``

namely, the range here:  `py::make_iterator(bd.begin(smplx), bd.end(smplx))`` it seems will reference the result of ``*it``` for ``itr = bd.begin(smplx).`` It seems that it sometimes one needs to copy the results explicitly. I'm not sure if it makes sense for the binding to detect iterator types, and do different things depending on what it finds. (I can try to make it do this if we understand the correct behaviour) 

Doing this myself I now see:
``In [6]: r = [ctl.Term_Simplex_Z2(x.cell(), x.coefficient()) for x in bd(s)]
In [7]: r
Out[7]: 
[<ctl.Term_Simplex_Z2 at 0x1066e2378>,
 <ctl.Term_Simplex_Z2 at 0x1066e24c8>,
 <ctl.Term_Simplex_Z2 at 0x1066e2500>]``

It appears that I further had a bug in my print code. Fixing this, I now see it prints out a list of empty lists.

```
In [1]: import ctl
In [2]: s = ctl.Abstract_simplex([1,2,3])
In [3]: bd =ctl.Simplex_boundary()
In [4]: r = [ctl.Term_Simplex_Z2(x.cell(), x.coefficient()) for x in bd(s)]
In [5]: r
Out[5]: 
[<ctl.Term_Simplex_Z2 at 0x10ad39c00>,
 <ctl.Term_Simplex_Z2 at 0x10ad39d88>,
 <ctl.Term_Simplex_Z2 at 0x10ad39dc0>]
In [6]: print r[0]
[[]]
In [7]: print r[1]
[[]]
In [8]: print r[2]
[[]]
```
The corresponding iterators work correctly on the C++ side, so something weird is happening in the bindings.

Also odd, when I iterate a second time over the object, something different happens:

```
In [9]: for x in bd(s):
   ...:     print x
   ...:     
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-be929ceaa501> in <module>()
----> 1 for x in bd(s):
      2     print x
      3 

TypeError: 'ctl.Term_Simplex_Z2' object is not iterable

In [10]: 
KeyboardInterrupt

In [10]: r = [ctl.Term_Simplex_Z2(x.cell(), x.coefficient()) for x in bd(s)]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-a16808ee6686> in <module>()
----> 1 r = [ctl.Term_Simplex_Z2(x.cell(), x.coefficient()) for x in bd(s)]

TypeError: 'ctl.Term_Simplex_Z2' object is not iterable
```
Any clue what I have done?

**Comment by rhl-** [comment] 2016-04-27 23:46
Ok, i'm not completely sure why, but, I made a small change to ``make_iterator`` in #183 which essentially calls the prefix operator of iterators, and this seems to make the bindings correctly return objects, and I seem to be able to call the function twice. Not sure if this is a bug in my iterator or the binding at the moment, however, either way, this should be more efficient, since postfix operators usually call the prefix operators..

**Comment by rhl-** [comment] 2016-04-28 04:06
Ok another update, I see now why you might need to use postfix operators, as python calls ``__next__()`` instantly, but, i'm not sure how this is supposed to work, since, usually postfix creates a temporary, and you originally used the ``return_value_policy::reference_internal`` policy.

**Comment by wjakob** [comment] 2016-04-28 06:02
Your first question is really a C++ one: when you write ``new Object()``, actually two things happen: 

1. C++ calls ::operator new () to allocate memory
2. C++ calls the in-place constructor to construct the instance in the allocated memory region

pybind11 does 1, and the code in __init__ has to do 2. Otherwise you have an instance that believes it is constructed, but it just contains uninitialized memory.

**Comment by wjakob** [comment] 2016-04-28 06:10
Regarding the other code, it's hard for me to say what is going on. I don't see a problem with the iterator code in pybind11, and I don't have access to your Simple class. Please provide a minimal and self-contained C++ example which reproduces the problem you are experiencing.

**Comment by rhl-** [comment] 2016-04-28 06:21
In regards to one, its been a long time since I thought about  ``placement new`` somehow the syntax went right past me. makes sense.

@wjakob ok, I can try to work on that. However, perhaps in the meantime the code is publically available: https://github.com/appliedtopology/ctl on a branch python_api_and_maxcliques

just do:

```
mkdir build
cd build
cmake ..
make ctl
```
ctl.so is created in build/python

but, you must see that an implementation of the postfix operator is usually:

```
Iterator operator++(int){
 Iterator tmp( *this);
 ++(*this);
 return tmp;
} 
```

I believe what is happening is that the ``tmp`` object gets destructed somewhere in the call stack back to python. Perhaps because its lifetime needs to also be tied to objects it iterates over (or vice versa)?

 I was trying to programmatically print the stacktrace, to try and find the exact place where this happens, but, the stacktrace cant be completely demangled for some reason.

However, If you switch to the prefix operator none of this can happen, as you track the lifetime of iterator_state see #185

**Comment by wjakob** [comment] 2016-04-28 06:44
The point of making a self-contained example is precisely not having to go through a bigger codebase -- please just crunch it down to a class Foo with some function f() that is causing your issue.

Here is an example on what I'd like a git tracker issue to look like:  https://github.com/pybind/pybind11/issues/169

**Comment by rhl-** [comment] 2016-04-28 17:40
I know what a minimal example is. I have a deadline coming up, and I dont know that I can create a minimal example in the next few days, but, when I can I will try. To prove to you that is is not a problem with my iterator, I print out the values of the copy and original iterator values in my post fix operator, before and after the call to the prefix operator, as well as what the value that is returned to python is, tmp and *this are as written in the small operator++ implementation in my previous comment.

```
tmp: [2, 3]⊗[4, 5, 6]
this: [1, 3]⊗[4, 5, 6]
tmp: [2, 3]⊗[4, 5, 6]
returned to python:  []⊗[] 

tmp: [1, 3]⊗[4, 5, 6]
this: [1, 2]⊗[4, 5, 6]
tmp: [1, 3]⊗[4, 5, 6]
returned to python:  []⊗[] 

tmp: [1, 2]⊗[4, 5, 6]
this: [1, 2, 3]⊗[5, 6]
tmp: [1, 2]⊗[4, 5, 6]
returned to python:  []⊗[] 

tmp: [1, 2, 3]⊗[5, 6]
this: [1, 2, 3]⊗[4, 6]
tmp: [1, 2, 3]⊗[5, 6]
returned to python:  []⊗[] 

tmp: [1, 2, 3]⊗[4, 6]
this: [1, 2, 3]⊗[4, 5]
tmp: [1, 2, 3]⊗[4, 6]
returned to python:  []⊗[] 

tmp: [1, 2, 3]⊗[4, 5]
this: []⊗[]
tmp: [1, 2, 3]⊗[4, 5]
returned to python:  []⊗[] 
```
This was compiled against top of trunk.

I also have a a unit test for my iterators (which I have essentially not modified in 5 years, which have been working, which I have published papers with).

I'm not saying its not a problem with my use of the bindings, but, sofar, I don't know what that could be. The only thing I can point to is what I said earlier, tmp is somehow being deallocated.

Instead of finding you a minimal example, I would rather find the bug. I can't figure out how to debug your bindings though. Do you have some kind of GDB/LLDB setup which allows you to debug the running shell? Or do you have a mock interface that stubs out the python bit?

**Comment by wjakob** [comment] 2016-05-26 18:29
Closing this for now as the issue is a month old now. Feel free to reopen/comment when there is some new information.

**Closed by wjakob** 2016-05-26 18:29 UTC
