### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by ianhbell** [pybind/pybind11#767] opened 2017-03-26 17:27 UTC
I've looked throughout the docs, but can't find a preferred citation for pybind11. I'm writing several publications presently that make heavy use of pybind11 as a shim layer between various C++ libraries that I have written and python.  Do you have a canonical reference for pybind11?

**Comment by wjakob** [comment] 2017-04-08 17:10
Given the current set of maintainers, I propose the following:

```bibtex
@misc{pybind11,
   Author = {Wenzel Jakob and Jason Rhinelander and Dean Moldovan},
   Year = {2016},
   Note = {https://github.com/pybind/pybind11},
   Title = {pybind11 — Seamless operability between C++11 and Python}
} 
```

**Comment by wjakob** [comment] 2017-04-08 17:11
If somebody has a better idea on how to cite software via bibtex, I'm all ears :)

**Comment by jagerman** [comment] 2017-04-08 17:14
2016 -> 2017, but otherwise good with me.

**Comment by jagerman** [comment] 2017-04-08 17:17
According to [this](https://superuser.com/questions/8743/how-to-cite-software-in-latex) BibLaTeX supports a `@software` with a `version`, but it's otherwise essentially just a `@misc` alias.

**Comment by ianhbell** [comment] 2017-05-27 22:01
Only change I might recommend is to use a -- instead of a —.  At least for me I use ASCII bibtex (only).

Somewhat related: is there a list of projects using pybind11?  I have a lot of projects using pybind11 now, and some are really simple demonstrations that might be appropriate to those just getting started.

**Comment by loriab** [comment] 2017-06-13 17:20
Thanks for the citation guidance. Since that sort of citation is hard to track and academic funding agencies like publications, here's a [doi](http://pubs.acs.org/doi/abs/10.1021/acs.jctc.7b00174).

**Comment by wjakob** [comment] 2017-11-17 17:45
Fixed in e7d304f

**Closed** 2017-11-17 17:44 UTC

**Comment by sbrodehl** [comment] 2023-01-17 14:20
Hi @wjakob and others,

is the citation in the docs still "valid"?
One can also add a [CITATION file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files), because the first thing I found was this issue, then, looking at the commit, the place in the docs, and after this I confirmed the citation in the docs.

Thanks!

**Comment by andrewfowlie** [comment] 2024-08-20 05:37
I was also wondering if the bibtex was out of date. FWIW, I think I will use this bibtex

```
@misc{pybind11,
   author = "{W. Jakob, J. Rhinelander, D. Moldovan and \href{https://github.com/pybind/pybind11/graphs/contributors}{others}}",
   year = {2017},
   title = "{\href{https://github.com/pybind/pybind11}{pybind11 -- Seamless operability between C++11 and Python}}"
}
```
