### ISSUE TITLE
Function taking Eigen::Ref matrix cannot be called with 1xN numpy array

### ISSUE THREAD

**Issue by stukowski** [pybind/pybind11#738] opened 2017-03-16 12:32 UTC
#### Issue description

I have a C++ function taking a ``const Eigen::Ref<const Eigen::MatrixXd>&`` input parameter. It accepts matrices of arbitrary dimensions. The pybind11-generated binding works fine when I pass NxM or Nx1 matrices. For example:

```
>>> my_function(numpy.zeros((4,3)))
>>> my_function(numpy.zeros((3,1)))
```

But I get an error when I try to pass a 1xN matrix:

```
>>> my_function(numpy.zeros((1,3)))

TypeError: my_function(): incompatible function arguments. The following argument types are supported:
    1. (numpy.ndarray[float64[m, n], flags.f_contiguous]) -> arg0: None

Invoked with: array([[ 0.,  0.,  0.]])
```

Is this behaviour intended? The "Vectors versus column/row matrices" section of the pybind11 documentation only speaks about automatic conversion of Numpy arrays to Eigen matrices and row/column vectors, but it seems that the case described above is not really covered in the discussion. Please note that, in my case, I am not dealing with vectors, only 2d matrices of arbitrary dimensions. 

When I change the signature of my c++ function to taking a ``const Eigen::MatrixXd&`` instead of an ``Eigen::Ref``, then it works for any 2d Numpy array including 1xN arrays. However, I would prefer the ``Eigen::Ref`` solution, because it avoids copying of data if certain conditions are met.

#### Reproducible example code

I have attached a minimal code example that demonstrates the problem:
[matrix_issue.zip](https://github.com/pybind/pybind11/files/847647/matrix_issue.zip)

**Comment by jagerman** [comment] 2017-03-17 16:29
Definitely a bug (and thanks for the example code!); I'm looking into it now.

**Comment by jagerman** [comment] 2017-03-17 18:33
Thanks for the report and test code!  This should be fixed now.

**Closed** 2017-03-17 18:32 UTC

**Comment by allanleal** [comment] 2019-12-27 01:11
I have a similar problem (using v2.4.3) in which passing an array with shape 0xN to a function expecting a `Ref<MatrixXd>` produces a similar error message:

~~~
E       TypeError: update(): incompatible function arguments. The following argument types are supported:
E           1. (self: optima.Canonicalizer, arg0: numpy.ndarray[float64[m, n], flags.f_contiguous]) -> None
E       
E       Invoked with: <optima.Canonicalizer object at 0x7feaa8c161b0>, array([], shape=(0, 15), dtype=float64))
~~~

Could you please check if this is intended behavior or bug?

**Comment by EricCousineau-TRI** [comment] 2020-01-27 21:42
@allanleal I believe we've ran into this behavior as well in https://github.com/RobotLocomotion/drake/issues/12633

Will open an issue, and try submitting a patch.
