### ISSUE TITLE
Import error for nested classes with the same name but in different scopes

### ISSUE THREAD

**Issue by jslee02** [pybind/pybind11#2187] opened 2020-04-26 23:45 UTC
## Issue description

Not sure if this is a pybind11 problem or not, but it fails to import when there are nested classes with the same name but in different scopes.

The following code builds fine with no errors, but only import error happens. If the second "Option" (for `Derived::Option`) is renamed to something else, then the import error disappears.

I believe this binding code is legitimate because it works in equivalent Python code.

```python
class Base:
    class Option:
        def __init__(self):
            print('Base.Option')

    def __init__(self):
        print('Base')


class Derived(Base):
    class Option(Base.Option):
        def __init__(self):
            print('Derived.Option')

    def __init__(self):
        print('Derived')


b = Base()
d = Derived()

o1 = Base.Option()
o2 = Derived.Option()

#---------
# Output:
#---------
# Base
# Derived
# Base.Option
# Derived.Option
```

## Reproducible example code

- compiler: GCC 9.2.1
- pybind11: v2.5
- Python: v3.5.2

```cpp
#include <pybind11/pybind11.h>

class Base {
public:
  Base() = default;
  class Option {
  public:
    Option() = default;
  };
};

class Derived : public Base {
public:
  Derived() = default;
  class Option : public Base::Option {
  public:
    Option() = default;
  };
};

namespace py = pybind11;

PYBIND11_MODULE(example, m) {
  auto base = py::class_<Base>(m, "Base").def(py::init<>());
  py::class_<Base::Option>(base, "Option").def(py::init<>());

  auto derived = py::class_<Derived, Base>(m, "Derived").def(py::init<>());
  py::class_<Derived::Option, Base::Option>(derived, "Option").def(py::init<>());
}
```

```python
Python 3.5.2 (default, Apr 16 2020, 17:47:17) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import example
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: generic_type: cannot initialize type "Option": an object with that name is already defined
```

**Comment by YannickJadoul** [comment] 2020-07-26 23:49
Duplicate of #1624. The problem is that pybind11 sees that `hasattr(Derived, "Option")` (namely in `Base`). Temporary (but ugly) workaround is the following:

```
  auto base = py::class_<Base>(m, "Base").def(py::init<>());
  auto derived = py::class_<Derived, Base>(m, "Derived").def(py::init<>());

  py::class_<Derived::Option, Base::Option>(derived, "Option").def(py::init<>());
  py::class_<Base::Option>(base, "Option").def(py::init<>());
```

I am thinking about/working on a fix. Closing this as duplicate; follow #1624 instead.

**Closed by YannickJadoul** 2020-07-26 23:49 UTC
