### ISSUE TITLE
Error passing a python bytes value to a py::bytes argument in Python 3

### ISSUE THREAD

**Issue by tomdz** [pybind/pybind11#908] opened 2017-06-19 23:45 UTC
When using this function: https://github.com/caffe2/caffe2/blob/master/caffe2/python/pybind_state.cc#L497-L499
in Python 3 with a `bytes` object (i.e. what you get when you call `encode('utf-8')` on a string), then I get this error:
```
TypeError: Incompatible function arguments. The following argument types are supported:
    1. (net_def : bytes, overwrite : bool = False) -> bool
    Invoked with: b'\n\tbuilder_0...', False
```
This is with Python 3.6.0, pybind11 1.8.1, and GCC.

**Comment by jagerman** [comment] 2017-06-20 01:58
I can't seem to reproduce this (even with pybind 1.8.1, to see whether it's fixed by later versions).  Can you give me the full Python-side invocation and values?

**Comment by tomdz** [comment] 2017-06-20 04:13
This doesn't quite help you because my changes to make Caffe2 run under Python 3 are not fully merged yet, but this is the traceback from one of the unit tests:
```
======================================================================
ERROR: test_builder_tuple (caffe2.caffe2.python.python_op_test.PythonOpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "caffe2/caffe2/python/python_op_test.py", line 78, in test_builder_tuple
    workspace.CreateNet(cloned_net)
  File "caffe2/python/workspace.py", line 140, in CreateNet
    return C.create_net(StringifyProto(net), overwrite)
TypeError: Incompatible function arguments. The following argument types are supported:
    1. (net_def : bytes, overwrite : bool = False) -> bool
    Invoked with: b'\n\tbuilder_0\x12\xe1\x01\n\x04iter\x1a\x00"\x06Python*\x15\n\x13grad_output_indic
es*\x14\n\x12grad_input_indices*t\n\x0fpickled_builder"a\x80\x03ccaffe2.caffe2.python.python_op_test\n
op_builder\nq\x00X\x04\x00\x00\x00nameq\x01K\x05\x86q\x02}q\x03X\x05\x00\x00\x00extraq\x04G@\x10\xcc\x
cc\xcc\xcc\xcc\xcds\x87q\x05.*\x18\n\x14pickled_grad_builder"\x00*\x12\n\x0epass_workspace\x18\x00\x12
\xe1\x01\n\x04iter\x1a\x00"\x06Python*\x15\n\x13grad_output_indices*\x14\n\x12grad_input_indices*t\n\x
0fpickled_builder"a\x80\x03ccaffe2.caffe2.python.python_op_test\nop_builder\nq\x00X\x04\x00\x00\x00nam
eq\x01K\x05\x86q\x02}q\x03X\x05\x00\x00\x00extraq\x04G@\x10\xcc\xcc\xcc\xcc\xcc\xcds\x87q\x05.*\x18\n\
x14pickled_grad_builder"\x00*\x12\n\x0epass_workspace\x18\x00:\x04iter', False
```
The Python wrapper code is here: https://github.com/caffe2/caffe2/blob/master/caffe2/python/workspace.py#L440-L444

Is there any way I can get some more info out of the `PyCapsule` object, e.g. see some generated Python or C++ code ?

**Comment by jagerman** [comment] 2017-06-20 04:44
Is `StringifyProto(net)` returning an actual `bytes` object?  To debug this, try defining a new function like this:
```C++
m.def("func", [](py::object o) { return (bool) PyBytes_Check(o.ptr()); });
```
and call it with the same argument from Python; I'm guessing that it is returning `False`.  The code that determines whether the input to the first argument is a valid `bytes` object is just calling that to see if the argument is a `bytes`; if it fails, it can't call that function because it can't create the `py::bytes` wrapper around it.

**Comment by tomdz** [comment] 2017-06-20 05:03
I printed its type in Python and it returned `bytes`, but let me try that.

**Comment by tomdz** [comment] 2017-06-20 06:18
Mhmm, so it is not actually the args or C++ function declaration. Adding this and calling it with the same args works just fine:
```
m.def("debug_bytes", [](py::bytes net_def, bool overwrite) { return true; });
```
The problem is somewhere within the method, but it is masked as the incompatible function argument error ?

**Comment by jagerman** [comment] 2017-06-20 15:19
I'm at a bit of a loss as to why this is happening; does it happen with current pybind (either 2.1, or, preferably, master)?  The function dispatcher was mostly rewritten in 2.1.

**Comment by tomdz** [comment] 2017-06-20 18:57
Updating to 2.1 is a little complicated for us (which is why we're still on 1.8). I'll revisit it when I have time to update and will try to fix the underlying error in our code first. Thanks for your help !

**Comment by jagerman** [comment] 2017-06-20 19:00
If you are trying to debug why this is happening, debugging the various steps of `dispatcher(PyObject *self, PyObject *args, PyObject *kwargs)` is the place to help figure out why, exactly, the arguments aren't being accepted.

**Comment by dean0x7d** [comment] 2017-08-30 20:16
Closing for bookkeeping since it's regarding an old version of pybind11 and it seems to have been worked around. Feel free to reopen if there's an update.

**Closed by dean0x7d** 2017-08-30 20:16 UTC
