### ISSUE TITLE
"no matching function for call to 'operator delete'" in projected targeting C++17, Clang 7.0

### ISSUE THREAD

**Issue by cosnxdx** [pybind/pybind11#1604] opened 2018-11-10 12:32 UTC
## Issue description
Build targeting C++17 with Clang version 7.0 fails with error:

> error: no matching function for call to 'operator delete' ::operator delete(p,s,std::align_val_t(a));
> 
> note: candidate function not viable: no known conversion from 'pybind11::size_t' (aka 'unsigned long') to 'ImNewDummy' for 2nd argument
> inline void  operator delete(void*, ImNewDummy, void*)

replacing operator delete(p, s, std::align_val_t(a)) with operator delete(p) solves the build issue

**Comment by wjakob** [comment] 2018-11-11 18:35
Looks like you are working with a class that defines a custom deletion operator. We'll need a minimal self-contained example before this issue can be discussed in more detail.

**Comment by jdumas** [comment] 2018-11-28 18:23
I can reproduce this by compiling the pybind11 repo in C++17 mode:
```
cmake -DCMAKE_CXX_COMPILER=clang++ -DPYBIND11_CPP_STANDARD=-std=c++17 ..
```

**Comment by ndoxx** [comment] 2018-12-01 01:13
Hi,
I think I solved this problem by enabling sized deallocation under Clang, which is not enabled by default (see https://bcain-llvm.readthedocs.io/projects/clang/en/release_37/ReleaseNotes/). 

Use the option -fsized-deallocation. The macro __cpp_sized_deallocation should then be defined in the C++ header "new", and the operator delete with signature void operator delete(void*, std::size_t, std::align_val_t) will be declared.

**Comment by NikolausDemmel** [comment] 2019-01-31 16:36
> Use the option -fsized-deallocation. 

Fixes it for me as well. Anyone know a cross-platform (cmake) way to check when this should be added?

**Comment by jquesnelle** [comment] 2019-02-01 17:13
I ran into this too. It might make sense to detect this (Clang/C++17) 
in the pybind cmake and add `-fsized-deallocation` to the build interface since pybind explicitly is invoking sized deallocation. More background on Clang: https://reviews.llvm.org/D8467

**Comment by jwnimmer-tri** [comment] 2019-06-14 17:26
There's a chance that my RobotLocomotion/pybind11#30 has resolved the problem.  (You are welcome to cherry-pick it here upstream, if you like.)

**Comment by e00E** [comment] 2019-06-25 11:47
I ran into this problem when compiling the first example in the documentation with clang:
```c++
#include <pybind11/pybind11.h>

int add(int i, int j) {
    return i + j;
}

PYBIND11_MODULE(example, m) {
    m.doc() = "pybind11 example plugin"; // optional module docstring

    m.def("add", &add, "A function which adds two numbers");
}
```

Indeed it works with `-fsized-deallocation`.

**Comment by aldanor** [comment] 2019-12-18 11:28
Should this be closed now?

(@wjakob cherry-picked a fix in 759221f5c56939f59d8f342a41f8e2d2cacbc8cf - maybe a 2.4.4 could be released so it's fixed in stable?)

**Comment by daskol** [comment] 2019-12-31 02:58
The issue looks solved. Should it be closed&

**Comment by wjakob** [comment] 2019-12-31 12:05
Indeed, closing.

**Closed by wjakob** 2019-12-31 12:05 UTC
