### ISSUE TITLE
error dereferencing nullptr

### ISSUE THREAD

**Issue by eirrgang** [pybind/pybind11#1187] opened 2017-11-16 18:19 UTC
https://github.com/pybind/pybind11/blob/0a0758ce3a8e62c1fcf0a32b9c2564aa59ee1fe8/include/pybind11/pybind11.h#L916

The pointer returned by get_type_info() can be null, here, but it is not checked before dereferencing on the following line.

I'm still trying to figure out the bug in my code that exposed this problem, but it seems like an easy segmentation fault to fix in pybind. I don't know what sort of error or diagnostic ought to be issued if the nullptr is detected, though.

**Comment by jagerman** [comment] 2017-11-16 18:31
My guess is that your bug is probably caused by specifying a base class which isn't pybind-registered, i.e. something like:
```C++
py::class_<Class, Base>(m, "Class");
```
where `Base` is a (C++) base class of `Class`, but isn't pybind-registered.

**Comment by jagerman** [comment] 2017-11-16 18:33
Actually, no, that's already detected and caught.

**Comment by jagerman** [comment] 2017-11-16 18:39
I'm at a loss as to how you could get a `nullptr` there; it shouldn't be possible for that `get_type_info` call to return a `nullptr` as far as I can see: we always check for that *before* we append the base class entry in `rec.bases`.

**Comment by eirrgang** [comment] 2017-11-16 19:39
Yes, it is from specifying a base class that isn't pybind-registered, but with the function argument version py::class_<Class>(m, "Class", base)
I was trying to use a base class imported from another module, and I think the problem was that they were compiled with different pybind minor versions, so that while initializing the base classes for "Class," it fails to find the type info in all_type_info_populate. The imported type has a bases array of size 1 but the type_dict is empty.

**Comment by bstaletic** [comment] 2020-07-23 11:35
> `py::class_(m, "Class", base)`

How can `base` not be registered, if `base` needs to be a `py::class_` object?

**Comment by bstaletic** [comment] 2020-09-12 22:15
Nobody yelled at me so far. Closing.

**Closed by bstaletic** 2020-09-12 22:15 UTC
