### ISSUE TITLE
Unable to import numpy from an embedded python script

### ISSUE THREAD

**Issue by ptumati-nvidia** [pybind/pybind11#1889] opened 2019-08-18 00:16 UTC
Hi,
Ubuntu 14.04; Anaconda 2.7
Install instructions: https://anaconda.org/conda-forge/pybind11 
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4

I have a Machine learning model that I would like to use for inferencing from my C++ app. I  started playing with pybind11; I notice that I get an error whenever I attempt to import numpy module from my python script. The whole thing works just fine if I comment out "import numpy"...  "import sys" seems to be ok... Am I missing something here?

calc.py
-------
```
#!/home/ats/anaconda2/bin/python
import numpy   #### <- comment this and everything works fine
import sys

def getString():
    return "hello,world";
```

c++ code
-----------
```
#include <pybind11/embed.h> 
namespace py = pybind11;
#include <iostream>
int main() {
	py::scoped_interpreter guard{};
	py::module sys = py::module::import("sys");
	py::print(sys.attr("path"));
	py::module calc = py::module::import("calc");
	py::object result1 = calc.attr("getString")();
	std::cout << ">>> " << result1.cast<std::string>() << std::endl;
}
```

Compilation
-------------
```
g++ -Wall -std=c++11 $(python2.7-config --includes) $(python2.7-config --cflags) ex.cpp -c
g++ ex.o $(python2.7-config --ldflags)
```

Error:
------
```
~/lab/pybind$ ./a.out
['/home/ats/anaconda2/lib/python2.7', '/home/ats/anaconda2/lib/python2.7/plat-x86_64-linux-gnu', '/home/ats/anaconda2/lib/python2.7/lib-tk', '/home/ats/anaconda2/lib/python2.7/lib-old', '/home/ats/anaconda2/lib/python2.7/lib-dynload', '/home/ats/anaconda2/lib/python2.7/site-packages', '/home/ats/anaconda2/lib/python2.7/site-packages', u'.']
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  ImportError: /home/ats/anaconda2/lib/python2.7/lib-dynload/_ctypes.so: undefined symbol: _PySlice_Unpack

At:
  /home/ats/anaconda2/lib/python2.7/ctypes/__init__.py(7): <module>
  /home/ats/anaconda2/lib/python2.7/site-packages/numpy/_distributor_init.py(18): __enter__
  /home/ats/anaconda2/lib/python2.7/site-packages/numpy/_distributor_init.py(33): <module>
  /home/ats/anaconda2/lib/python2.7/site-packages/numpy/__init__.py(140): <module>
  ./calc.py(1): <module>

Aborted (core dumped)
```

Note: I do get the same error when I attempt to import numpy in the C++ code using this:
```
    auto np = py::module::import("numpy");
    py::print(np.attr("version"));
```

**Comment by Himscipy** [comment] 2020-01-24 23:06
Hi @ptumati-nvidia Did you find any fix to your problem ?

**Comment by coley13** [comment] 2020-03-20 00:47
@ptumati-nvidia @Himscipy either one of you figure it out? I'm running into the same issue. 

I was able to import other 3rd party modules just to verify it was possible and not a path issue or something, but importing numpy keeps failing, both in the .cpp file and in any .py modules.

**Comment by Himscipy** [comment] 2020-03-20 19:13
@coley13 , So, at my end there are two case: 1) On my local unbuntu 19.04 machine every thing works fine. but in case 2) when I try to deploy my application on a cluster(HPC) I am getting an error if I try to load a numpy module. I did tried to understand this issue by analyzing my application with valgrid mem-check, since by doing debugging (gdb) my application it pointed me to some memory allocation issue. The valgrind reported some invalid access in memory but the application by passed it and continued, in case 2) when i run my application on cluster I suspect this is causing things to break. I don't have any fix for it yet. 
My suggestion would be for you will be to a gdb of your application and also perform some valgrind analysis for the .cpp case. I will be interested in hearing your findings. I hope this is a help to you in some sense..!

**Comment by coley13** [comment] 2020-03-20 20:39
Thanks @Himscipy, got it working
Starting to follow your advice I used the `traceback` module in my python script to see what was breaking around the `numpy` import. I'm using the zipped embedded python distribution for windows and while my path was correctly set to find `numpy`, `numpy` couldn't find the compiled `_ctypes.pyd` file included with the embedded python version. That explains why my other 3rd party module, with no other dependencies, wasn't having any issues being imported.
I added the entire embedded directory to my `._pth` file and now I'm good to go.

**from `main.cpp`**
```cpp
py::module test = py::module::import("test");
```

**`test.py`**
```python
import traceback
try:
    import numpy
except:
    traceback.print_exc()
```
So if yours is working locally but not on the cluster, perhaps it's a path issue as well. Thanks again for responding and good luck.

**Comment by YannickJadoul** [comment] 2020-07-22 17:00
I can't naively reproduce this. If anyone is running into this, do compare the `sys.path` between the program embedding Python and just running the Python interpreter as standalone.

I'll close this. Please reopen, or open another issue, if this is still a problem. Thanks, @coley13, for the methodology in debugging this!

**Closed by YannickJadoul** 2020-07-22 17:00 UTC

**Comment by Romit-Maulik** [comment] 2020-07-30 04:30
Hello - @Himscipy and I have been looking at this problem for a while now and I get similar behavior when I try to use the Python C API for this problem as well. When I compare `sys.path` between the cmd line interpreter and my program embedding - I get identical outcomes. 

I am also able to run my embedded python module (with NumPy) without any troubles on my local machine but see the same sorts of errors when trying this on any HPC (I have tried three cluster resources with no success). 

@coley13 - I tried your traceback method for catching the exception - but I still end up crashing my code with a not very helpful stacktrace (as follows).

```
Running from interpreter
#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::sigFpe::sigHandler(int) at ??:?
#2  ? in "/lib64/libc.so.6"
#3  ? at scalarmath.c:?
#4  PyNumber_Multiply in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#5  _PyEval_EvalFrameDefault in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#6  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#7  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#8  _PyEval_EvalFrameDefault in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#9  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#10  PyEval_EvalCodeEx in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#11  PyEval_EvalCode in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#12  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#13  PyCFunction_Call in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#14  _PyEval_EvalFrameDefault in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#15  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#16  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#17  _PyEval_EvalFrameDefault in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#18  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#19  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#20  _PyEval_EvalFrameDefault in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#21  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#22  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#23  _PyEval_EvalFrameDefault in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#24  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#25  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#26  _PyEval_EvalFrameDefault in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#27  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#28  _PyFunction_FastCallDict in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#29  _PyObject_FastCallDict in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#30  _PyObject_CallMethodIdObjArgs in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#31  PyImport_ImportModuleLevelObject in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#32  _PyEval_EvalFrameDefault in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#33  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#34  PyEval_EvalCodeEx in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#35  PyEval_EvalCode in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#36  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#37  PyCFunction_Call in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#38  _PyEval_EvalFrameDefault in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#39  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#40  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#41  _PyEval_EvalFrameDefault in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#42  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#43  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#44  _PyEval_EvalFrameDefault in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#45  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#46  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#47  _PyEval_EvalFrameDefault in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#48  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#49  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#50  _PyEval_EvalFrameDefault in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#51  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#52  _PyFunction_FastCallDict in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#53  _PyObject_FastCallDict in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#54  _PyObject_CallMethodIdObjArgs in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#55  PyImport_ImportModuleLevelObject in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#56  ? in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#57  PyCFunction_Call in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#58  PyObject_Call in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#59  PyObject_CallFunction in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#60  PyImport_Import in "/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/libpython3.6m.so.1.0"
#61  Foam::RASModels::Python_SA<Foam::IncompressibleMomentumTransportModel<Foam::transportModel> >::Python_SA(Foam::geometricOneField const&, Foam::geometricOneField const&, Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh> const&, Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh> const&, Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh> const&, Foam::transportModel const&, Foam::word const&) at ??:?
#62  Foam::RASModel<Foam::IncompressibleMomentumTransportModel<Foam::transportModel> >::adddictionaryConstructorToTable<Foam::RASModels::Python_SA<Foam::IncompressibleMomentumTransportModel<Foam::transportModel> > >::New(Foam::geometricOneField const&, Foam::geometricOneField const&, Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh> const&, Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh> const&, Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh> const&, Foam::transportModel const&) at ??:?
#63  Foam::RASModel<Foam::IncompressibleMomentumTransportModel<Foam::transportModel> >::New(Foam::geometricOneField const&, Foam::geometricOneField const&, Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh> const&, Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh> const&, Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh> const&, Foam::transportModel const&) at ??:?
#64  Foam::MomentumTransportModel<Foam::geometricOneField, Foam::geometricOneField, Foam::incompressibleMomentumTransportModel, Foam::transportModel>::adddictionaryConstructorToTable<Foam::RASModel<Foam::IncompressibleMomentumTransportModel<Foam::transportModel> > >::NewMomentumTransportModel(Foam::geometricOneField const&, Foam::geometricOneField const&, Foam::GeometricField<Foam::Vector<double>, Foam::fvPatchField, Foam::volMesh> const&, Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh> const&, Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh> const&, Foam::transportModel const&) at ??:?
#65  ? at ??:?
#66  ? at ??:?
#67  __libc_start_main in "/lib64/libc.so.6"
#68  ? at ??:?
Floating point exception (core dumped)
```

I am trying to run this snippet from another (rather large) C++ software (OpenFOAM):
```
    Py_Initialize();
    PyRun_SimpleString("import sys");
    PyRun_SimpleString("sys.path.append(\".\")");
    PyRun_SimpleString("print('Running from interpreter')");
    
    pName = PyUnicode_DecodeFSDefault("python_module"); // Python filename
    pModule = PyImport_Import(pName);
```
whereas my `python_module.py` file is
```
import traceback
import sys

f = open('test','w')
f.write('Hello world')
f.close()

try:
    import numpy
except:
    traceback.print_exc(file=open("errlog.txt","a"))
```
The file `test` (with the 'Hello world' inside it) is written out, but I do not get any errlog.txt file. Any assistance would be very helpful thanks!

**Comment by bstaletic** [comment] 2020-07-30 15:26
Does the following work?

```c++
py::scoped_interpreter g;
py::print("Running from interpreter");
auto pModule = py::module::import("python_module");
```

**Comment by Romit-Maulik** [comment] 2020-07-30 15:30
@bstaletic - if my module has an `import numpy` statement - it crashes with the same segfault. In fact, this line crashes too. In the Python C API:
```
PyRun_SimpleString("import numpy");
```

**Comment by bstaletic** [comment] 2020-07-30 15:46
If raw C API causes a segfault, it's definitely not a pybind issue. Check the interpreter. Check if you can load it from the interactive shell. I don't know what's going on in your environment.

**Comment by Romit-Maulik** [comment] 2020-07-30 15:57
Yes - I don't think this is a Pybind issue. I can load numpy from the interactive shell. My `sys.path` is exactly the same whether I print it from my C++ code or from the interpreter. On our HPC resource, we are encouraged to load prebuilt modules for Python and numpy (which I use a `module load package_name` command for). I build my C++ code (with the Python embeddings) by pointing to the include directories for Python and numpy (for instance):
```
-I/soft/anaconda3/5.0.0/envs/tensorflow_cpu/include/python3.6m \
-I/soft/anaconda3/5.0.0/envs/tensorflow_cpu/lib/python3.6/site-packages/numpy/core/include \
```
I link to Python with
```
-lpython3.6m
```
Do you think there might be some issues with numpy not finding something in the `LD_LIBRARY_PATH`?

**Comment by Romit-Maulik** [comment] 2020-07-30 18:44
Perhaps this might be some interesting information - when I have my own "hello world" program with my interpreter being initialized from my `int main()` function. I am not able to reproduce this issue. I have exactly the same environment and modules loaded, the same compilers used to build my small app but I am able to load numpy and basically do exactly what I want. Could this offer any leads?

**Comment by YannickJadoul** [comment] 2020-07-30 18:55
What numpy is being found? Is it the same as the one from tensorflow? Otherwise, there might be some issue there?
Anaconda or tensorflow is really messing up something here. Could you try in a basic Python installation?

**Comment by Romit-Maulik** [comment] 2020-07-30 19:27
Hi @YannickJadoul - thanks for your comment. `tensorflow_cpu` is just the name of the module - within this environment we have a numpy package that I am trying to access. This package is numpy 1.17.0. Using a `sys.version` (whether from the Python module or the C++ code) results in the exact same output. If I leave out the import numpy statements and do whatever else it is I want within the python model (which is not really of any use) - my executable runs as expected. 
```
3.6.9 |Intel Corporation| (default, Sep 11 2019, 16:40:08) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
```

**Comment by YannickJadoul** [comment] 2020-07-30 20:28
Alright, misread that then, sorry.
Still, could you perhaps try a fresh non-anaconda environment? As long as I'm not able to reproduce, I don't have a lot of guesses, I'm afraid... :-/

**Comment by Romit-Maulik** [comment] 2020-07-30 20:35
It's really quite baffling - because when I use the exact same compilers/environment variables but just my own CPP app - I cannot reproduce this issue.

**Comment by philipcardiff** [comment] 2021-05-27 21:19
Hello @Romit-Maulik  and @YannickJadoul,

I am seeing the same problem; coincidently (I think), I am also trying to use pybind11 with OpenFOAM.

For me, calling "py::module::import("test");" from the C++ main() function works fine, but it fails when I call it from a dynamically linked library.

Maybe that helps you reproduce the error; if not, I will try to create and share a simple example.

**Comment by Romit-Maulik** [comment] 2022-02-03 03:36
Hi @philipcardiff - for some reason I saw your comment and completely blanked on replying. Unfortunately, I have not been able to solve this problem (in the general sense). I suspect it may have something to do with the OpenFOAM and CPU architecture/instruction combinations because it flares up on some machines but doesn't on others. I tried building numpy from source without any optimization as well but it seems `import_array1(-1)` being called from C++ just breaks everything with a segfault. 

Did you make any progress in this direction?

**Comment by HenningScheufler** [comment] 2022-02-03 22:17
i have the same issue with an anaconda installation python version 3.9 calling
```
import numpy as np
```
did you get the same issue with pythonfoam  without pybind11?

**Comment by HenningScheufler** [comment] 2022-02-03 22:17
i have the same issue with an anaconda installation python version 3.9 calling
```
import numpy as np
```
did you get the same issue with pythonfoam  without pybind11?

**Comment by Romit-Maulik** [comment] 2022-02-03 22:19
@HenningScheufler - that is correct. But the issue is (atleast apparently) related to hardware. On Bebop at Argonne, I do not get any issue for on Theta (and my laptop) I get this issue. So its rather frustrating.

**Comment by philipcardiff** [comment] 2022-02-03 23:17
> Hi @philipcardiff - for some reason I saw your comment and completely blanked on replying. Unfortunately, I have not been able to solve this problem (in the general sense). I suspect it may have something to do with the OpenFOAM and CPU architecture/instruction combinations because it flares up on some machines but doesn't on others. I tried building numpy from source without any optimization as well but it seems `import_array1(-1)` being called from C++ just breaks everything with a segfault.
> 
> Did you make any progress in this direction?

Hi @Romit-Maulik, thanks for your reply!

Although I have not made any progress towards determining the cause, the workaround in OpenFOAM posted here [https://github.com/pybind/pybind11/issues/2485#issuecomment-693225253](url) avoids the problem, which is good enough for me!

**Comment by Romit-Maulik** [comment] 2022-02-04 02:34
HI @philipcardiff - that's great. I am not sure I am familiar with the `argList` solution there. Is it implying that the main function of a solver should be modified from 
```
int main(int argc, char *argv[])
```
to something like
```
int main(int argc, char *argv[], bool checkArgs=true, bool checkOpts=true, bool initialise=false)
```
Sorry if this is a naive question.

**Comment by HenningScheufler** [comment] 2022-02-04 08:26
I could successfully reproduce and my application ran without error 

But initialise=false also turn off 
```
        sigFpe::set(bannerEnabled());
        sigInt::set(bannerEnabled());
        sigQuit::set(bannerEnabled());
        sigSegv::set(bannerEnabled());
```

If you turn them on back on in interFoam you get the same problem:

```

#include "fvCFD.H"
#include "dynamicFvMesh.H"
#include "CMULES.H"
#include "EulerDdtScheme.H"
#include "localEulerDdtScheme.H"
#include "CrankNicolsonDdtScheme.H"
#include "subCycle.H"
#include "immiscibleIncompressibleTwoPhaseMixture.H"
#include "incompressibleInterPhaseTransportModel.H"
#include "turbulentTransportModel.H"
#include "pimpleControl.H"
#include "fvOptions.H"
#include "CorrectPhi.H"
#include "fvcSmooth.H"

#include "sigFpe.H"
#include "sigInt.H"
#include "sigQuit.H"
#include "sigSegv.H"
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

int main(int argc, char *argv[])
{
    argList::addNote
    (
        "Solver for two incompressible, isothermal immiscible fluids"
        " using VOF phase-fraction based interface capturing.\n"
        "With optional mesh motion and mesh topology changes including"
        " adaptive re-meshing."
    );

    #include "postProcess.H"

    #include "addCheckCaseOptions.H"
    #include "setRootCaseLists.H"
    #include "createTime.H"
    #include "createDynamicFvMesh.H"
    #include "initContinuityErrs.H"
    #include "createDyMControls.H"
    #include "createFields.H"
    #include "createAlphaFluxes.H"
    #include "initCorrectPhi.H"
    #include "createUfIfPresent.H"

    sigFpe::set((::Foam::infoDetailLevel > 0));
    sigInt::set((::Foam::infoDetailLevel > 0));
    sigQuit::set((::Foam::infoDetailLevel > 0));
    sigSegv::set((::Foam::infoDetailLevel > 0));
```
Sadly this is a risky workaround

**Comment by philipcardiff** [comment] 2022-02-04 10:08
Indeed. It is just masking the problem.

**Comment by HenningScheufler** [comment] 2022-02-04 11:39
But the following solution works with numpy.

```
#include "fvCFD.H"
#include "pyInterp.H"

#include "sigFpe.H"
#include "sigInt.H"
#include "sigQuit.H"
#include "sigSegv.H"
namespace py = pybind11;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

int main(int argc, char *argv[])
{
    #include "setRootCase.H"
    #include "createTime.H"

    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

    runTime.printExecutionTime(Info);

    pyInterp::New(runTime);
    sigFpe::unset(true);

    py::object pyC = py::module_::import("testing").attr("Testing");

    sigFpe::set(true);

    pyC("Hello");

    Info<< "End\n" << endl;

    return 0;
}

```

https://github.com/DLR-RY/ECI4FOAM/blob/feature-supportnumpy/application/test/test-pythonNumpy/test-pythonNumpy.C
https://github.com/DLR-RY/FMU4FOAM

I have no idea why a float point exception is raised in numpy.  A possibility is that numpy.NaN is loaded which might causes the error. The following solution also works with shared libaries and requires no modification of the solver. This solution might be acceptable as python should throw errors in the python modules

**Comment by timheb** [comment] 2023-11-24 15:23
I had a similar problem with numpy and pybind11 embedded. I have a executable that dynamically load a library that uses pybind11 and is therefore linked against Python. I had to dynamically load my library with the option RTLD_GLOBAL.

found the solution here: https://stackoverflow.com/a/70390749
