### ISSUE TITLE
Strange linking error on Mac when trying to bind std::basic_istream::gcount method

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#830] opened 2017-05-03 22:24 UTC
Dear Pybind11 Developers, I noticed that on Mac(apple clang) platform attempts to bind any of `std::basic_*stream::gcount` methods lead to a linking error `illegal text reloc`. Interestingly attempts to bind any other methods of these class group seems to work just fine. 

Also, this error is only appears on Mac+clang and the code works just fine on Linux. 

Any idea of what might be wrong here?

Thanks,

Minimal example to reproduce:
```C++
// Require Mac OS X + Clang to reproduce
#include <pybind11/pybind11.h>
#include <iostream>

namespace py = pybind11;

PYBIND11_PLUGIN(example)
{
    py::module m("example", "pybind11 example plugin");

	pybind11::class_<std::basic_istream<char,std::char_traits<char>> > cl(m, "basic_istream_char_std_char_traits_char_t", "");

	//cl.def("gcount", &std::basic_istream<char, std::char_traits<char> >::gcount);
	// uncommenting the line above will lead to ld error: illegal text reloc in '_initexample' to '__ZNKSt3__113basic_istreamIcNS_11char_traitsIcEEE6gcountEv' for architecture x86_64

	cl.def("get", (int (std::basic_istream<char,std::char_traits<char>>::*)()) &std::basic_istream<char, std::char_traits<char> >::get);

    return m.ptr();
}
```

**Comment by jagerman** [comment] 2017-05-04 01:53
It's not Mac-specific, but apparently libc++ specific: I can reproduce it on Linux with clang using `-stdlib=libc++`.

**Comment by jagerman** [comment] 2017-05-04 01:56
The linux error:

```
$ clang++-4.0 -stdlib=libc++ i830.cpp `python3-config --includes --ldflags` -I../include -std=c++14 -fPIC -shared -o i830.so
/tmp/i830-4bd139.o: In function `pybind11_init()':
i830.cpp:(.text+0x23a): undefined reference to `std::__1::basic_istream<char, std::__1::char_traits<char> >::gcount() const'
/usr/bin/ld: /tmp/i830-4bd139.o: relocation R_X86_64_PC32 against undefined hidden symbol `_ZNKSt3__113basic_istreamIcNS_11char_traitsIcEEE6gcountEv' can not be used when making a shared object
/usr/bin/ld: final link failed: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jagerman** [comment] 2017-05-04 02:06
`libc++` declares `gcount()` with `_LIBCPP_INLINE_VISIBILITY` [here](https://github.com/llvm-mirror/libcxx/blob/master/include/istream#L246), which I'm guessing is the issue.

You ought to be able to work around it easily enough with a lambda wrapper:
```C++
cl.def("gcount", [](std::basic_istream<char, std::char_traits<char> > &is) { return is.gcount(); })`
```
but this seems like a libc++ issue.

**Comment by lyskov** [comment] 2017-05-04 15:21
Hmm... the undefined error might be a different thing: i did get it if i did not supply `-undefined dynamic_lookup` command line flags on Mac (it is not `gcount` specific, seems to appear for most of std classes). @jagerman could you please try to add `-undefined dynamic_lookup` to you command line and see if it goes away?

**Comment by lyskov** [comment] 2017-05-04 15:27
And yes, i can confirm that lambda work around is indeed solve this for me, - thank you! I was just hopping there is a Clang command-line option solution because in my project all these is auto generated so replacing functions with lambda is kind of problematic...

**Comment by jagerman** [comment] 2017-05-04 15:28
I'm pretty sure that's an OS X-only option.

**Comment by dean0x7d** [comment] 2017-07-06 19:28
I was just watching a C++Now talk by Marshall Clow and he happened to mention this very issue: https://youtu.be/U3jGdnRL3KI?t=33m40s -- link is timestamped to start at the relevant part and it lasts about a minute and a half. (The entire talk is also great.)

TL;DW Taking the address of standard library function is not portable. Implementations are allowed to have an overload set where you would not expect one or mark a function `always_inline`. The only portable way to get a pointer is to wrap the `std` function in a lambda.

The relevant part of the C++14 standard seems to be [17.6.5.5](https://timsong-cpp.github.io/cppwp/n4140/conforming#member.functions).

**Comment by lyskov** [comment] 2017-07-06 19:31
Wow... thats very interesting/educational - thank you for sharing this @dean0x7d !

**Comment by jagerman** [comment] 2017-07-23 04:24
In light of @dean0x7d 's answer, I'm going to close this as not something pybind can do anything about.

**Closed by jagerman** 2017-07-23 04:24 UTC
