### ISSUE TITLE
polymorphism in "def_property" write function

### ISSUE THREAD

**Issue by amastrobera** [pybind/pybind11#1840] opened 2019-07-15 13:53 UTC
Dear Pybind, 

I defined a property with a read function and write function, like in your [examples](https://pybind11.readthedocs.io/en/stable/classes.html?highlight=def_property). 

**How can I define a second write function for the same property ?** 

C++ class
```
//simplifying: a point is 3D or 2D (z is optional)
struct Point {
    double x, y;
    std::optional<double> z;
};

class MyObject {
public:
       //...
       Point getPosition() const;
       void setPosition(std::pair<double,doble> pt2d);
       void setPosition(std::tuple<double, double, double> pt3d);
};
```

Python 
```
py::class_<MyObject>(m, "MyObject")
      .def_property(
          "position",
          [=](MyObject const& ob) {
            //return 2d coordinate;
          },
          [](MyObject& ob, std::pair<double, double> args) { 
                     return ob.setPosition(args.first, args.second); }, 

//?--> [](MyObject& ob, std::tuple<double, double, double> args) {
                        return ob.setPosition(
                           std::get<0>(args), std::get<1>(args), std::get<2>(args)); }
         // doesn't compile
       )
```

... I noticed that if I define twice that property, it compiles. **is this the right way to do it ?**

```
      // with 2D point
      .def_property(
          "position",
          [=](MyObject const& ob) {
            //return 2d coordinate;
          },
          [](MyObject& ob, std::pair<double, double> args) { 
                     return ob.setPosition(args.first, args.second); })

      // with 3D point
      .def_property(
          "position",
          [=](MyObject const& ob) {
            //return 2d coordinate;
          },
         [](MyObject& ob, std::tuple<double, double, double> args) {
                        return ob.setPosition(
                           std::get<0>(args), std::get<1>(args), std::get<2>(args)); }
       )
```

**Comment by sizmailov** [comment] 2019-09-01 20:17
duplicate of https://github.com/pybind/pybind11/issues/191

**Comment by bstaletic** [comment] 2020-07-07 14:05
Closing as duplicate.

**Closed by bstaletic** 2020-07-07 14:05 UTC
