### ISSUE TITLE
PYBIND11_MODULE broken 

### ISSUE THREAD

**Issue by jeremyvillalobostaste** [pybind/pybind11#890] opened 2017-06-06 21:22 UTC
Make sure you've completed the following steps before submitting your issue -- thank you!
You can remove this template text afterward.

1. Check if your question has already been answered in the [FAQ](http://pybind11.readthedocs.io/en/latest/faq.html) section.
2. Make sure you've read the [documentation](http://pybind11.readthedocs.io/en/latest/). Your issue may be addressed there.
3. If those resources didn't help and you only have a short question (not a bug report), consider asking in the [Gitter chat room](https://gitter.im/pybind/Lobby).
4. If you have a genuine bug report or a more complex question which is not answered in the previous items (or not suitable for chat), please fill in the details below.
5. Include a self-contained and minimal piece of code that reproduces the problem. If that's not possible, try to make the description as clear as possible.

#### Issue description
compiling the code on 

http://pybind11.readthedocs.io/en/master/classes.html

produces the following error

example.cpp:20:16: error: expected constructor, destructor, or type conversion before ‘(’ token
 PYBIND11_MODULE( the_mod , m){

If I work around  PYBIND11_MODULE by using PYBIND11_PLUGIN, the code compiles and I am able to use the C++/Python class binding

Not sure I am missing anything with the workaround.  I assume it is just a convenient function.

(Provide a short description, state the expected behavior and what actually happens.)

#### Reproducible example code

G++ 4.8.4
python 2.7.11

Create the file as instructed by http://pybind11.readthedocs.io/en/master/classes.html
compbile as instructed on https://pybind11.readthedocs.io/en/stable/basics.html

(The code should be minimal, have no external dependencies, isolate the function(s) that cause breakage. Submit matched and complete C++ and Python snippets that can be easily compiled and run to diagnose the issue.)

**Comment by jagerman** [comment] 2017-06-06 22:11
Are you sure you're using the current `master` branch, and not the 2.1 release?  `PYBIND11_MODULE` is an addition for the next release (probably 2.2), but not present in the current stable release.

**Comment by jagerman** [comment] 2017-06-19 16:22
Closing due to lack of reply.  Feel free to reopen if the issue is still present.

**Closed by jagerman** 2017-06-19 16:22 UTC

**Comment by haolu23** [comment] 2019-04-24 22:14
I have the same issue with default ubuntu 18.04 setup.
pybind11-dev 2.0.1-4
g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Python 2.7.15rc1

**Comment by gsrujana89** [comment] 2019-05-18 00:05
same issue on pybind11 2.2.4..ubuntu18.04

**Comment by gst** [comment] 2019-10-10 15:23
Hi,

I encountered the same issue.

Cloned  `https://github.com/pybind/python_example`
then `apt install python3-pybind11`
then `pip install build` 

and get the error.

* python 3.6.8
* python3-pybind11 2.0.1-4

What should I do ?

**Comment by safijari** [comment] 2019-10-16 02:47
Having the same issue on Ubuntu 18.04 with pybind11 installed from apt

**Comment by rancheng** [comment] 2019-10-19 15:28
> Having the same issue on Ubuntu 18.04 with pybind11 installed from apt

Same issue on Ubuntu 18.04

**Comment by gst** [comment] 2019-12-20 18:57
Can this issue be reopen eventually ? 

I am still experiencing the problem.. :/

**Comment by NikolausDemmel** [comment] 2020-01-03 16:53
@jagerman, could you reopen, or should we file a new issue?

I'm having the same issue with sophuspy, leading to an error during install with pip:

````
$ pip3 install --user -U sophuspy

[...]

    Scanning dependencies of target sophuspy
    [ 50%] Building CXX object CMakeFiles/sophuspy.dir/sophus/sophuspy.cpp.o
    /tmp/pip-install-gzn3gvm0/sophuspy/sophus/sophuspy.cpp:9:16: error: expected constructor, destructor, or type conversion before ‘(’ token
     PYBIND11_MODULE(sophuspy, m)

[...]
```

This is ob Ubuntu 18.04. I have `pybind11-dev_2.0.1-4` from apt, python 3.6.10 from apt, and pybind11 2.4.3 from pip (installed with `--user`). I've also tried with `python3-pybind11` from apt, or indeed current master branch from source as [suggested above](https://github.com/pybind/pybind11/issues/890#issuecomment-544160220), but I get the same error.

Is the issue maybe the outdated pybind11-dev from apt?

**Comment by NikolausDemmel** [comment] 2020-01-03 17:11
Wait, I guess pybind11 from pip should be standalone and not depend on the pybind11-dev package from apt, right? Thing is, that if I don't have the pybind11-dev apt package installed, I get the following error when installing sophuspy with pip, even if pybind11 is installed from pip. Looks like pybind11 from pip cannot be found by cmake. Is that supposed to be this way? Should sophuspy be doing something differently?

```
$ pip3 install --user -U sophuspy
Collecting sophuspy
  Using cached https://files.pythonhosted.org/packages/dc/a1/afa83127d473c3d5eb0633b137154f80c9a7759fbadabc02af1eac453865/sophuspy-0.0.8.tar.gz
Requirement already satisfied, skipping upgrade: numpy in /usr/wiss/demmeln/bionic/.local/lib/python3.6/site-packages (from sophuspy) (1.17.4)
Requirement already satisfied, skipping upgrade: pybind11 in /usr/wiss/demmeln/bionic/.local/lib/python3.6/site-packages (from sophuspy) (2.4.3)
Installing collected packages: sophuspy
    Running setup.py install for sophuspy ... error

[...]

    CMake Error at CMakeLists.txt:10 (find_package):
      By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "pybind11",
      but CMake did not find one.
    
      Could not find a package configuration file provided by "pybind11" with any
      of the following names:
    
        pybind11Config.cmake
        pybind11-config.cmake
    
      Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
      "pybind11_DIR" to a directory containing one of the above files.  If
      "pybind11" provides a separate development package or SDK, be sure it has
      been installed.

[...]
```

**Comment by NikolausDemmel** [comment] 2020-01-03 17:23
Looks like a known issue with the pip install... https://github.com/pybind/pybind11/issues/1628
