### ISSUE TITLE
[BUG] TSAN error logs

### ISSUE THREAD

**Issue by rwgk** [pybind/pybind11#2754] opened 2020-12-29 06:46 UTC
TSAN logs as requested by @YannickJadoul here:

https://github.com/pybind/pybind11/pull/2746#issuecomment-751906066

Using `master` b7dfe5cc84ca1891b50e728e83c9b5b393cf5272
`+` #2409
`+` #2746 (https://github.com/YannickJadoul/pybind11/commit/727b3aeda951f40d7019d2b189edc3b1184764e0)
`+` 2 additional minor local patches.

`test -c dbg --config=tsan` (Google-internal toolchain)

Failing tests:
* `test_gil_scoped.py`
* `test_iostream.py` [**EDIT**: see PR #2995]: https://github.com/pybind/pybind11/blob/d587a2fd17dc89c0b2d4b6dc7715594bed45fb58/tests/test_iostream.cpp#L43

**Comment by rwgk** [comment] 2020-12-29 06:46
[test_gil_scoped_tsan_log.txt](https://github.com/pybind/pybind11/files/5749818/test_gil_scoped_tsan_log.txt)

**Comment by rwgk** [comment] 2020-12-29 06:47
[test_iostream_tsan_log.txt](https://github.com/pybind/pybind11/files/5749819/test_iostream_tsan_log.txt)

**Comment by YannickJadoul** [comment] 2020-12-29 12:03
To link up things:
- The `test_iostream` failure seems to be more info about https://github.com/pybind/pybind11/pull/2675#issuecomment-730014386

**Comment by YannickJadoul** [comment] 2020-12-30 01:22
I knew I'd seen the other one as well:
- The `test_gil_scoped` race condition is also shown in #2391

**Comment by bstaletic** [comment] 2021-01-01 13:18
I know this is the TSAN thread, but TSAN seems to be a major PITA to set up. I'm hoping no one would mind me submitting helgrind's analysis.

https://gist.github.com/bstaletic/98441d24b5e0010118051c31036ef2f8

Note: debug symbols for all dependency are necessary to get useful tracebacks.

Observation: `test_gil_scoped.py` doesn't seem to touch pybind11 as far as threading errors are concerned, but `test_iostream.py` does.

**Comment by YannickJadoul** [comment] 2021-01-01 15:34
The main issue with Helgrind (I've been playing around with it, a few days ago), is that it doesn't recognize C++'s `atomic`, etc?

Btw, the main issue (or one of the main issues) seems to lie in this line:

https://github.com/pybind/pybind11/blob/e612043d43e5382848466a5a6fe59e58edcf74fb/tests/test_iostream.cpp#L40

Apparently, `std::cout` is supposed to be thread-safe though (guaranteed by the standard, thread-safe; not garbled-output safe, but let's not care about that for now) ? However, I don't know if that's still the case for `std::cout` with the custom `streambuf`?

**Comment by rwgk** [comment] 2021-01-01 16:36
@henryiii did someone already try out this suggestion in the meantime?
https://github.com/pybind/pybind11/blame/master/include/pybind11/iostream.h#L41

**Comment by henryiii** [comment] 2021-01-01 16:42
The current implementation is exactly what is recommended. The "fully qualified virtual call" is at best the same, and possibly not really functional in forcing the correct call. Since it didn't fix the problem, I don't think there's any harm in moving to the fully qualified call, but there should not be a benefit.

**Comment by henryiii** [comment] 2021-01-26 17:07
Do you think we could add a mutex here, perhaps?

**Comment by rwgk** [comment] 2021-01-26 17:14
I really don't know, not knowing much about threading, but I'd be happy to try out ideas for you. If you point me to a branch with experimental changes it'll take me only a few minutes to try them out.

**Comment by YannickJadoul** [comment] 2021-01-26 18:07
@henryiii, @rwgk and I discussed this in a private chat, but we couldn't figure out who's job it is to have the mutex: the custom `streambuf` or the part of the program that's writing to `std::cout`?

According to https://berthub.eu/articles/posts/iostreams-unexpected/ (quoting the standard), writing to `std::cout` from different threads can garble up the output, but shouldn't be UB. So that kind of makes me think the synchronization needs to happen inside the custom `streambuf`. But at the same time, it seems a bit weird that a class that could perfectly be used in a singled-threaded environment needs to _always_ take care of synchronization?

**Comment by rwgk** [comment] 2021-01-26 18:20
Coincidentally I saw we're using the `WITH_THREAD` macro already.
(I don't know when and where it's defined.)

**Comment by henryiii** [comment] 2021-01-26 18:45
It's defined if Python was compiled with thread support. We could possibly add a mutex only if WITH_THREAD is defined? I tried to setup TSan, but getting it working on Python on macOS or in docker seems to be painful.

**Comment by YannickJadoul** [comment] 2021-01-26 18:53
> It's defined if Python was compiled with thread support. We could possibly add a mutex only if WITH_THREAD is defined? I tried to setup TSan, but getting it working on Python on macOS or in docker seems to be painful.

In principle, even if Python doesn't have threads, a user could still start threads in C++-only code? So that feels tricky

**Comment by rwgk** [comment] 2021-01-26 18:55
> I tried to setup TSan, but getting it working on Python on macOS or in docker seems to be painful.

I can give you very quick feedback (most of the time), using our internal tools. I know it's not ideal to have me in the loop, but probably most practical to get rid of that annoying flake.

> In principle, even if Python doesn't have threads, a user could still start threads in C++-only code? So that feels tricky

I'd say a problem for later. One at a time.

**Comment by YannickJadoul** [comment] 2021-01-26 19:03
> > In principle, even if Python doesn't have threads, a user could still start threads in C++-only code? So that feels tricky
> 
> I'd say a problem for later. One at a time.

This is part of figuring out the fix for our problem though. The actual issue in the tests is easy to fix: put a mutex around `std::cout << foo` in that multithreaded test. But we need to figure out whose responsibility it is to do that.
And if we do it only in some cases (e.g., `WITH_THREAD`) that not the correct scope, you're to some degree only making things worse and making future issues less consistent & harder to reproduce ;-)

**Comment by henryiii** [comment] 2021-01-26 19:25
We already have a mutex of sorts with the gil_scoped_aquire? Are we really worried about performance here? Could we add a lock_guard there as well, possibly / probably including the setp, and maybe later improve performance?

I haven't noticed the empty output error in a long while, roughly since the linked PR went in; this seems to have replaced it. :/

**Comment by henryiii** [comment] 2021-01-26 19:26
This is the same bug as in older versions, but instead of printing empty strings, it now hangs up...

**Comment by YannickJadoul** [comment] 2021-01-26 20:05
I believed I tried abusing the GIL as ad-hoc mutex, and that worked

**Comment by rwgk** [comment] 2021-01-27 18:20
@jbms provided this information to me, posting here with his permission:

In general iostream and streambuf objects are not thread-safe:
https://eel.is/c++draft/iostreams.requirements#iostreams.threadsafety

However, there is an exception for the standard streams:
https://eel.is/c++draft/iostream.objects#overview-7

if they are in "synchronized" mode:
https://eel.is/c++draft/ios.members.static

This is a bit of a weird guarantee, but that is what there is...

There doesn't seem to be any explicit language about thread safety in the case that a different streambuf has been associated with std::cout, but given the design of c++ iostreams, I think all the customization happens via virtual methods of streambuf --- ostream itself does not have any virtual methods.  Therefore it stands to reason that the synchronization logic happens in the default streambuf associated with std::cout, and if you change that, you also lose the synchronization.

Indeed, looking at libc++, here is the definition of the streambuf backing std::cout:

https://github.com/llvm/llvm-project/blob/90407b16b1d3e38f1360b6a24ceab801ab9cefc1/libcxx/include/__std_stream#L222

It appears that the way it achieves thread safety is by setting a buffer on the streambuf.  Since streambuf manipulates its internal buffer without locking, that isn't thread safe.  But by not setting a buffer, all writes are immediately sent to the `overflow` and `xsputn` virtual methods, which can then handle the write in a thread-safe manner.  The `sync` method of __stdoutbuf looks questionable to me as far as thread safety, since it does access the shared `*__st` value, but I think that may only be used for wide streams, and the thread-safety guarantee may not apply to those.

The pybind11 output redirect relies on this streambuf type:
https://github.com/pybind/pybind11/blob/9b7bfef833ca5af73db1bb8f31f194c2288a96da/include/pybind11/iostream.h#L24

It does set a buffer, which leads to streambuf manipulating the buffer in a thread-unsafe manner.

I think it might be possible to make that thread safe by eliminating the buffer, similar to __stdoutbuf.  I think the C++ standard still wouldn't guarantee thread safety in this case, but in practice it seems likely to work on all implementations --- I guess you could check what MSVC's standard library and libstdc++ do.  Eliminating the buffering may hurt performance.  Potentially there could be both a thread-safe and thread-unsafe pythonbuf implementation.

**Comment by rwgk** [comment] 2021-03-23 23:12
Coincidentally, while UBSAN testing PR #2917 locally (against the `smart_holder` branch), with `PYBIND11_USE_SMART_HOLDER_AS_DEFAULT` defined, `test_iostream.py` failed with:
```
libc++abi: terminating with uncaught exception of type std::runtime_error: Could not allocate string object!
```
NOTE: It is NOT certain that this UBSAN error is meaningful or related to the TSAN error, but I'm attaching the traceback JIC it's giving someone a useful clue.

[ubsan.txt](https://github.com/pybind/pybind11/files/6193249/ubsan.txt)

**Closed** 2022-10-30 15:57 UTC
