### ISSUE TITLE
Hi, I built caffe2 with 2017 developer command. it built successfully. I didn't find any file with this name caffe2_pybind11_state in all my hard. How can you help me?

### ISSUE THREAD

**Issue by HRubaye** [pybind/pybind11#1289] opened 2018-02-18 21:23 UTC
Make sure you've completed the following steps before submitting your issue -- thank you!

1. Check if your question has already been answered in the [FAQ](http://pybind11.readthedocs.io/en/latest/faq.html) section.
2. Make sure you've read the [documentation](http://pybind11.readthedocs.io/en/latest/). Your issue may be addressed there.
3. If those resources didn't help and you only have a short question (not a bug report), consider asking in the [Gitter chat room](https://gitter.im/pybind/Lobby).
4. If you have a genuine bug report or a more complex question which is not answered in the previous items (or not suitable for chat), please fill in the details below.
5. Include a self-contained and minimal piece of code that reproduces the problem. If that's not possible, try to make the description as clear as possible.

*After reading, remove this checklist and the template text in parentheses below.*

## Issue description

(Provide a short description, state the expected behavior and what actually happens.)

## Reproducible example code

(The code should be minimal, have no external dependencies, isolate the function(s) that cause breakage. Submit matched and complete C++ and Python snippets that can be easily compiled and run to diagnose the issue.)

**Comment by YannickJadoul** [comment] 2020-07-07 16:49
I don't get the problem from 3 sentences in the title of the issue only; that's what the body of the issue is for.
We need more details, but given that this is +2 years old, I'm closing this.

Reopen if necessary.

**Closed by YannickJadoul** 2020-07-07 16:49 UTC
