### ISSUE TITLE
Inheritance not working as expected when using holder

### ISSUE THREAD

**Issue by abergmeier** [pybind/pybind11#195] opened 2016-05-13 07:38 UTC
The following binding is not handling like I would expect:

    PYBIND11_DECLARE_HOLDER_TYPE(T, IntrusivePtr<T>);

    struct Foo : public RefCount {
      int id() const;
      void setId(int);
    };

    struct Bar : public Foo {
    };

    py::class_< Foo, IntrusivePtr<Foo> >( m, "Foo" )
      .def_property( "id", &Foo::id, &Foo::setId )
    ;

    py::class_< Bar, IntrusivePtr<Bar> >( m, "Bar", py::base<Foo> )
    ;

When I try to do the following in Python:

    bar = get_bar()
    bar_id = bar.id # Failing line

It raises:

    TypeError: Incompatible function arguments. The following argument types are not supported:
      1. (Foo) -> int

Is this a limitation or how should one handle these scenarios?

**Comment by wjakob** [comment] 2016-05-15 18:31
One general request: please submit *complete* test cases that I can compile and reproduce on my end. For instance, I don't have your ``IntrusivePtr`` class, etc..

What you reportec sounded pretty serious, so I tried to add the missing pieces. However, everything works fine here:

```
#include <pybind11/pybind11.h>

PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);

struct Foo : public std::enable_shared_from_this<Foo> {
    int id() const { return 0; };
    void setId(int) { };
};

struct Bar : public Foo {};

namespace py = pybind11;

PYBIND11_PLUGIN(test) {
    py::module m("test");

    py::class_<Foo, std::shared_ptr<Foo>>(m, "Foo")
        .def_property("id", &Foo::id, &Foo::setId);

    py::class_<Bar, std::shared_ptr<Bar>>(m, "Bar", py::base<Foo>())
        .def(py::init<>());
    return m.ptr();
}
```

```
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import test
>>> test.Bar()
<test.Bar object at 0x10197e2b0>
>>> test.Bar().id
0
```

**Comment by abergmeier** [comment] 2016-05-17 07:27
> One general request: please submit complete test cases that I can compile and reproduce on my end. For instance, I don't have your IntrusivePtr class, etc..

Sorry about that. Am trying to come up with a concise reproduction repo.

**Comment by wjakob** [comment] 2016-05-20 13:48
ping?

**Comment by abergmeier** [comment] 2016-05-20 14:01
Cannot repo yet with any simpler code. Only shows in our full bindings for whatever reason. Could perhaps give you the LLVM IR if that helps any!?

**Comment by wjakob** [comment] 2016-05-20 14:29
nope, sorry -- IR is not useful. I'll close this for now, but feel free to reopen when you have something that's reproducible on my end.

**Closed by wjakob** 2016-05-20 14:29 UTC

**Comment by abergmeier** [comment] 2016-05-23 14:58
Cannot for the love of me reproduce it simply.
That said - I added more error output and it has the `Bar` object twice in the `args_` tuple which seems fishy. No idea yet why, however.

**Comment by abergmeier** [comment] 2016-05-24 08:49
@wjakob Is there a way to extract `detail::type_record` from an instance of `object`?

**Comment by wjakob** [comment] 2016-05-24 10:35
``detail::get_type_info((PyTypeObject *) my_object.get_type())```

**Comment by abergmeier** [comment] 2016-05-24 11:46
The above code does not compile for me. I tried:

    auto ptobj = obj.get_type().ptr();
    auto isType = PyType_Check(ptobj);
    if(isType) {
      auto tobj = reinterpret_cast<PyTypeObject*>(ptobj);
      auto tinfo = detail::get_type_info(tobj);

which throws `std::runtime_error`:

    pybind11::detail::get_type_info: unable to find type object!

**Comment by abergmeier** [comment] 2016-05-27 09:17
Ok, the `runtime_error` seems gone in the latest master. Looking at `type_info` it seems like the base class is set up correctly.

**Comment by abergmeier** [comment] 2016-05-27 15:05
@wjakob When I have the following:

    py::class_< Foo, AE3::IntrusivePtr<Foo> >( m, "Foo" )
        .def_property( "id", &Foo::id
    ;

    py::class_< Bar, AE3::IntrusivePtr<Bar> >( m, "Bar", py::base<Foo>() )
    ;

Is `Bar` supposed to be a subtype of `Foo` in Python or does it get implicitly converted?

For the error cast, `PyType_IsSubtype` returns `false` and no `implicit_conversions` are defined.

**Comment by wjakob** [comment] 2016-05-29 11:52
This code explicitly marks Bar as a subtype of Foo when the classes are registered on the Python side. All of this happens independently of the holder types, thus it's rather surprising if you get a cast error.

**Comment by abergmeier** [comment] 2016-05-30 12:21
`Bar` is indeed "marked" as a subtype of `Foo` but it seems like it does not directly test for this.
With the `PyType_IsSubtype` implementation:

    int
    PyType_IsSubtype(PyTypeObject *a, PyTypeObject *b)
    {
        PyObject *mro;

        mro = a->tp_mro;
        if (mro != NULL) {
            /* Deal with multiple inheritance without recursion
               by walking the MRO tuple */
            Py_ssize_t i, n;
            assert(PyTuple_Check(mro));
            n = PyTuple_GET_SIZE(mro);
            for (i = 0; i < n; i++) {
                if (PyTuple_GET_ITEM(mro, i) == (PyObject *)b)
                    return 1;
            }
            return 0;
        }
        else
            /* a is not completely initilized yet; follow tp_base */
            return type_is_subtype_base_chain(a, b);
    }

The line `if (PyTuple_GET_ITEM(mro, i) == (PyObject *)b)` always fails. I need to read up on what `mro` actually does.

**Comment by wjakob** [comment] 2016-05-30 12:23
Just to understand: is it the case that the subclass relationship works fine UNTIL you add your custom intrusive pointers? This (to me) is really the interesting part, because the ref-counting class ("holder type" in pybind11) is not even considered during the type inference.

**Comment by abergmeier** [comment] 2016-05-30 12:50
Good point. I rebuilt the code to work without custom pointer and the issues is the same.
Thus it does not work no matter what.

**Comment by wjakob** [comment] 2016-05-30 12:52
So then something else is fishy with your example, which is not part of the example you posted. Inheritance is used in a ton of projects depending on pybind11, and it works perfectly for everyone else.

**Comment by abergmeier** [comment] 2016-05-30 13:09
So logging the memory addresses of the types, it seems like there are multiple class instances of the `Foo` class in memory.

Logging the mro code in `PyType_IsSubtype`:

    1. Testing 0x258dd88 == 0x2592f98    <- Bar compare
    2. Testing 0x258d828 == 0x2592f98    <- Foo compare
    3. Testing 0xa389c0 == 0x2592f98    <- object compare

`0x2592f98` is the `Foo` type it compares against. And `0x258d828` seems to be another `Foo` type instance.

**Comment by wjakob** [comment] 2016-05-30 13:10
Are you using multiple extension modules compiled with pybind11 at the same time?

**Comment by abergmeier** [comment] 2016-05-30 13:15
Not that I am aware of (so possibly).
I am currently running a unittest:

    class TestBar(unittest.TestCase):
      from mymodule import core
      def test_construction_of_one(self):
        self.inst = self.core.Bar()
        self.inst.id

**Comment by wjakob** [comment] 2016-05-30 13:16
Ok, you will have to post complete and self-contained examples before I can help you any more with this.

**Comment by abergmeier** [comment] 2016-05-30 15:21
Found it. Reason is I am a moron.
Somewhere in the bindings there was the class registration duplicated thus adding `Foo` twice.
Would be great if you could add this as a failure case.

**Comment by wolfv** [comment] 2016-05-31 02:23
hey @abergmeier,

i had the same issue at some point. Maybe you can check if what I wrote back in the day would have worked for you: https://github.com/pybind/pybind11/issues/152

Maybe it can be reconsidered to include such a check.

**Comment by abergmeier** [comment] 2016-05-31 07:35
@wjakob Added an repro in https://github.com/pybind/pybind11/pull/218
