### ISSUE TITLE
[QUESTION] How to use the py file imported with tensorflow

### ISSUE THREAD

**Issue by wangwenchao-job** [pybind/pybind11#2446] opened 2020-08-29 08:48 UTC
### Two Question
I have two questions. The first is how to call a py file through C++. This py file contains deep learning libraries such as tensorflow. The second question is about the use of pybind11

#### First Question

My directory structure：
─test
    └─net
	   └─mynet.py
	└─main.cpp

Need to use the mynet.py file in net in main.cpp。

I can use the built-in packages such as os and sys normally, and perform functions similar to adding paths，but I don’t know how to use tensorflow。

Below is my main code：
```
int main() {
	py::scoped_interpreter guard{};

	py::print("Hello, World!");

	py::module sys = py::module::import("sys");
	py::module os = py::module::import("os");

	std::string buildDir = (os.attr("getcwd")()).cast<std::string>();

	std::string mainDir = (os.attr("path").attr("dirname")(buildDir)).cast<std::string>();

	std::string dsvddDir = (os.attr("path").attr("join")(mainDir, "dsvdd")).cast<std::string>();
	std::cout << dsvddDir << std::endl;
	sys.attr("path").attr("append")(dsvddDir);

	std::string kerasDir = "D:\\anaconda\\envs\\tf14\\lib\\site-packages\\tensorflow\\python\\keras\\api\\_v1\\keras";
	std::string kerasModelsDir = "D:\\anaconda\\envs\\tf14\\lib\\site-packages\\tensorflow\\python\\keras\\api\\_v1\\keras\\models";
	std::string vggDir = "D:\\anaconda\\envs\\tf14\\lib\\site-packages\\tensorflow\\python\\keras\\api\\_v1\\keras\\applications\\vgg16";
	sys.attr("path").attr("append")(kerasDir);
	sys.attr("path").attr("append")(kerasModelsDir);
	sys.attr("path").attr("append")(vggDir);

	std::string tfDir1 = "D:\\anaconda\\envs\\tf14\\python37.zip";
	std::string tfDir2 = "D:\\anaconda\\envs\\tf14\\DLLs";
	std::string tfDir3 = "D:\\anaconda\\envs\\tf14\\lib";
	std::string tfDir4 = "D:\\anaconda\\envs\\tf14";
	std::string tfDir5 = "C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python37\\site-packages";
	std::string tfDir6 = "D:\\anaconda\\envs\\tf14\\lib\\site-packages";
	std::string tfDir7 = "D:\\anaconda\\envs\\tf14\\lib\\site-packages\\win32";
	std::string tfDir8 = "D:\\anaconda\\envs\\tf14\\lib\\site-packages\\win32\\lib";
	std::string tfDir9 = "D:\\anaconda\\envs\\tf14\\lib\\site-packages\\Pythonwin";
	sys.attr("path").attr("append")(tfDir1);
	sys.attr("path").attr("append")(tfDir2);
	sys.attr("path").attr("append")(tfDir3);
	sys.attr("path").attr("append")(tfDir4);
	sys.attr("path").attr("append")(tfDir5);
	sys.attr("path").attr("append")(tfDir6);
	sys.attr("path").attr("append")(tfDir7);
	sys.attr("path").attr("append")(tfDir8);
	sys.attr("path").attr("append")(tfDir9);

	py::print(sys.attr("path"));

	py::module tf = py::module::import("tensorflow");
	py::print(tf.attr("__path__"));
}
```

I tried to add the tensorflow path in the virtual environment, but it didn't work。

#### Second Question
This question is about the use mechanism of pybind11。
There are various functions in my py file, all with complete implementation code, can I directly use one of these functions when calling C++? Still need to reorganize the functions in C++ in the form of pybind11?

**Comment by YannickJadoul** [comment] 2020-08-30 14:52
> I tried to add the tensorflow path in the virtual environment, but it didn't work。

What goes wrong? I have absolutely no clue what the problem is, with the little amount of information you give.

> This question is about the use mechanism of pybind11。
> There are various functions in my py file, all with complete implementation code, can I directly use one of these functions when calling C++? Still need to reorganize the functions in C++ in the form of pybind11?

I don't know what you mean here, either.
Yes, you can call Python functions from C++ in the embedded Python interpreter. That's more or the whole point of Python and pybind11's embedding functionality.

For things that aren't issues with pybind11, there's the [https://gitter.im/pybind/Lobby](Gitter chat), by the way, which is often easier (as mentioned in the issue template).

**Comment by wangwenchao-job** [comment] 2020-09-02 14:19
> > I tried to add the tensorflow path in the virtual environment, but it didn't work。
> 
> What goes wrong? I have absolutely no clue what the problem is, with the little amount of information you give.
> 
> > This question is about the use mechanism of pybind11。
> > There are various functions in my py file, all with complete implementation code, can I directly use one of these functions when calling C++? Still need to reorganize the functions in C++ in the form of pybind11?
> 
> I don't know what you mean here, either.
> Yes, you can call Python functions from C++ in the embedded Python interpreter. That's more or the whole point of Python and pybind11's embedding functionality.
> 
> For things that aren't issues with pybind11, there's the [https://gitter.im/pybind/Lobby](Gitter chat), by the way, which is often easier (as mentioned in the issue template).

Thank you very much for your reply. I have added the relevant paths of tf to the working path. Now it is possible to import tf, but when from xxx import xxx exists in the py file, the import will fail (the import is a certain file in the current folder). Files)

**Comment by YannickJadoul** [comment] 2020-09-02 14:33
> Thank you very much for your reply. I have added the relevant paths of tf to the working path. Now it is possible to import tf, but when from xxx import xxx exists in the py file, the import will fail (the import is a certain file in the current folder). Files)

As replied [on Gitter](https://gitter.im/pybind/Lobby?at=5f4fa8f7ec534f584fdac6a0):

> What do you want to do? What code doesn't work?
> I've never encountered problems with this
> Do you have a minimal reproducing example?

What `from xxx import xxx` doesn't work? Where is it written? In which folder is that file? Where is the module you're trying to import? Etc.
Please show me/us some concrete code that fails for you, because we still can't do anything we this vauge information.

**Comment by wangwenchao-job** [comment] 2020-09-02 15:04
> > Thank you very much for your reply. I have added the relevant paths of tf to the working path. Now it is possible to import tf, but when from xxx import xxx exists in the py file, the import will fail (the import is a certain file in the current folder). Files)
> 
> As replied [on Gitter](https://gitter.im/pybind/Lobby?at=5f4fa8f7ec534f584fdac6a0):
> 
> > What do you want to do? What code doesn't work?
> > I've never encountered problems with this
> > Do you have a minimal reproducing example?
> 
> What `from xxx import xxx` doesn't work? Where is it written? In which folder is that file? Where is the module you're trying to import? Etc.
> Please show me/us some concrete code that fails for you, because we still can't do anything we this vague information.

Sorry I did not clarify my question. The previous from import problem has been solved. The same is the issue of paths. Now there is a question, how do I pass parameters to the constructor, the following is the code

.py
```
class DeepSVDD:
    def __init__(
        self,
        keras_model,
        input_shape=(28, 28, 1),
        objective="one-class",
        nu=0.1,
        representation_dim=32,
        batch_size=64,
        lr=1e-4,
    ):
```

.cpp
```
py::module own_net = py::module::import("own_net");
	py::print(own_net.attr("creatcnn")());
	py::object keras_net = own_net.attr("creatcnn")();

	py::module DeepSVDD = py::module::import("deepSVDD");
	py::object svdd = DeepSVDD.attr("__init__")(keras_net, (28, 28, 1), "one-class", 0.1, 32, 64, 1e-4);
```

err:

![image](https://user-images.githubusercontent.com/57739867/92000902-a5ae3900-ed70-11ea-8610-aabcc5476028.png)

**Comment by YannickJadoul** [comment] 2020-09-02 15:20
I hope it's not a surprise to you that I can't read that error?

But you just do exactly the same as in Python:
- Import the module: `py::module deepSVDD_module = py::module::import("deepSVDD");`
- Get the class: `py::object DeepSVDD = deepSVDD_module.attr("DeepSVDD");`
- "Call" the class to create an object: `py::object svdd = DeepSVDD(keras_net, (28, 28, 1), "one-class", 0.1, 32, 64, 1e-4);`

I'm closing this issue, as the original question seems to have been answer. For questions like this, please come to Gitter (and stick around when @bstaletic, I, or anyone else answers or asks for more details).

**Closed by YannickJadoul** 2020-09-02 15:20 UTC
