### ISSUE TITLE
[BUG]:  PyCapsule_SetName segfault

### ISSUE THREAD

**Issue by tylerjereddy** [pybind/pybind11#4420] opened 2022-12-24 18:34 UTC
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

2.10.2

### Problem description

A detailed analysis of the situation that caused a hold-up of the SciPy release process on Windows is in this issue: https://github.com/scipy/scipy/issues/17644#issuecomment-1364370090

Our testsuite can't even start with `pybind11` `2.10.2` -- it literally segfaults during the `pytest` collection phase, and more specifically `import scipy.stats` segfaults, and `scipy.fft` import will fail as desribed here: https://github.com/scipy/scipy/issues/17644#issuecomment-1364345960

### Reproducible example code

Unfortunately, I probably don't have the bandwidth to excise an isolated reproducer, but I bet the `pybind11` folks will benefit from my DLL analysis over here: https://github.com/scipy/scipy/issues/17644#issuecomment-1364370090

### Is this a regression? Put the last known working version here if it is.

2.10.1

**Comment by matthew-brett** [comment] 2022-12-25 15:08
For convenience, here's some information ported over from https://github.com/scipy/scipy/issues/17644#issuecomment-1364370090 and similar.

Scipy has a compiled module `scipy.fft.pypocketfft`.   This module compiles and runs fine on all platforms with Pybind 2.10.1.

With Pybind 2.10.2, on Windows only, the compiled `pypocketfft` module segfaults on import during test collection.

[Tyler's investigation revealed](https://github.com/scipy/scipy/issues/17644#issuecomment-1364345960) this was due a new missing dependency.  Direct import generates the following:

```python
>>> import scipy.fft
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\treddy\python310_venv_windows\lib\site-packages\scipy\fft\__init__.py", line 92, in <module>
    from ._helper import next_fast_len
  File "C:\Users\treddy\python310_venv_windows\lib\site-packages\scipy\fft\_helper.py", line 3, in <module>
    from ._pocketfft import helper as _helper
  File "C:\Users\treddy\python310_venv_windows\lib\site-packages\scipy\fft\_pocketfft\__init__.py", line 3, in <module>
    from .basic import *
  File "C:\Users\treddy\python310_venv_windows\lib\site-packages\scipy\fft\_pocketfft\basic.py", line 6, in <module>
    from . import pypocketfft as pfft
ImportError: DLL load failed while importing pypocketfft: A dynamic link library (DLL) initialization routine failed.
```

[Further investigation revealed](https://github.com/scipy/scipy/issues/17644#issuecomment-1364370090) that there was a difference in declared imports between Pybind 2.10.1 and 2.10.2 - the 2.10.2 binary no longer imported `Function PyCapsule_SetName` (with `Import from module python310.dll`).

@rgommers [wondered whether](https://github.com/scipy/scipy/issues/17644#issuecomment-1364537985) this might be due to https://github.com/pybind/pybind11/pull/4254 .

**Comment by rwgk** [comment] 2022-12-26 07:35
I left a comment here: https://github.com/scipy/scipy/issues/17644#issuecomment-1364961305

**Comment by tylerjereddy** [comment] 2022-12-26 18:32
I excised the reproducer from SciPy so that you now have a standalone project with a single C++ source file, 1 C++ header file, and a build file: https://github.com/tylerjereddy/pybind_repro

The `README` there has a short description of reproducing on `2.10.2` vs. success with `2.10.1`. It could probably be cut down to an even simpler reproducer that is test-suite appropriate, but that probably gets into the weeds of C++ that are better dealt with by `pybind11` team.

At the very least, this should completely uncouple your debugging cycles from SciPy, which is going to save a ton of time most likely.

**Comment by Lalaland** [comment] 2022-12-27 19:00
This turned out to not be a pybind11 issue as it was a bug within scipy.  See #17662

We should fix have better error logging within pybind11 though. See #4426

**Comment by rgommers** [comment] 2022-12-28 12:52
Thanks a lot for getting to the bottom of this @Lalaland!

> This turned out to not be a pybind11 issue

Given that this went into a bug fix rather than a minor release, and caused issues in SciPy and PyTorch already, it may still be wise to yank this release? You can argue that going from "working in practice but UB" to "hard to debug segfault" is not a pybind11 bug technically, but it's still pretty impactful. It even defeated SciPy's fairly careful pinning for the last already released version (`"pybind11>=2.4.3,<2.11.0"`, [here](https://github.com/scipy/scipy/blob/maintenance/1.9.x/pyproject.toml#LL15C5-L15C31)). Yanking is a cheap safety measure here.

**Comment by Lalaland** [comment] 2022-12-28 14:09
@rgommers Yeah, I think I agree with you. This is not acceptable for a bug fix change and it should probably be revered and added back with better error reporting in the next minor release. Super sorry for all the work this caused on your part.

**Comment by rwgk** [comment] 2022-12-28 14:21
I'm sorry, too, that the failure reporting is so unobvious on some platforms.

But what is "yanking"?

I was thinking we make a 2.10.3 release with the better error reporting asap. Should we to do something else?

**Comment by rwgk** [comment] 2022-12-28 14:22
I forgot to add: only debug builds are affected.

**Comment by matthew-brett** [comment] 2022-12-28 15:03
Yanking is a process you can do on Pypi to remove the release so it does not appear as a candidate for installation.

**Comment by rwgk** [comment] 2022-12-28 15:08
Thanks! Sounds great to me.
@henryiii do you know how to do that?

**Comment by henryiii** [comment] 2022-12-28 17:11
Okay, I've yanked it. Let's get a 2.10.3 out ASAP since anyone relying on the Windows ARM support added in 2.10.2 is now broken (unless they request >=2.10.2, which is not likely just to add a single modern platform).

**Comment by henryiii** [comment] 2022-12-28 17:13
From what I understand, we revert the UB -> error behavior for 2.10.3, and make it an error with better error reporting in 2.11?

**Comment by rgommers** [comment] 2022-12-28 17:45
> Super sorry for all the work this caused on your part (especially during this time of the year).

No worries at all, and thanks for your help in resolving the issue!

**Comment by rwgk** [comment] 2022-12-28 23:53
I wrote down my thoughts here: https://github.com/pybind/pybind11/pull/4432#issuecomment-1366985491

**Comment by henryiii** [comment] 2022-12-29 03:21
Could you verify the UB was actually working as intended in SciPy (and/or PyTorch)? (The `py::none` defined was actually correctly an instance of `None` after Python initialized). If that's the case, I think we should have this new check (added in 2.10.2) disabled by default in 2.10.3 (and enabled in master / 2.11). If not, I think it was exposing a real issue and was fine for a patch release.

**Comment by Lalaland** [comment] 2022-12-29 04:31
@henryiii I highly doubt the UB in SciPy did anything wrong. Calling inc_ref on a none object is unlikely to break anything. Still worth fixing though.

**Comment by rgommers** [comment] 2022-12-29 06:29
Agreed - and no bug reports in ~3 years related to this for heavily used functionality in `scipy.fft`.

**Closed** 2023-01-06 18:42 UTC
Labels: triage
