### ISSUE TITLE
[QUESTION] binding std::vector<cv::Mat> problem

### ISSUE THREAD

**Issue by thancaocuong** [pybind/pybind11#2627] opened 2020-10-28 08:25 UTC
when binding std::vector<cv::Mat>, I use combine the NdarrayConverter that works for cv::Mat and 
stl. But I've got some error like
```
what it do
py::bind_vector<std::vector<cv::Mat>>(m, "CvMat");
```
error
```
/usr/include/c++/7/bits/predefined_ops.h:241:20: error: cannot convert ‘cv::MatExpr’ to ‘bool’ in return
/usr/include/c++/7/bits/stl_algobase.h:800:10: error: no match for ‘operator!’ (operand type is ‘cv::MatExpr’)
```

**Comment by YannickJadoul** [comment] 2020-10-28 11:15
This is a duplicate of #2627.

Currently, `bind_vector` expects a return value of `bool` from the `operator==`. A workaround is to not use the utility function, but manually expose the methods of this `std::vector` you want to expose to Python. `bind_vector` doesn't do anything more than `py::class_` and `.def`.

**Closed by YannickJadoul** 2020-10-28 11:15 UTC
