### ISSUE TITLE
help()/pydoc fails when a module has classes

### ISSUE THREAD

**Issue by wojdyr** [pybind/pybind11#728] opened 2017-03-14 20:10 UTC
This must be a regression as http://pybind11.readthedocs.io/en/master/classes.html#overloaded-methods has an example of `help()` and this example doesn't work with the current master.

I can get a a traceback if I call an internal function directly:
```
>>> print pydoc.text.docmodule(example, 'example')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/pydoc.py", line 1140, in docmodule
    inspect.getclasstree(classlist, 1), name)]
  File "/usr/lib/python2.7/inspect.py", line 739, in getclasstree
    return walktree(roots, children, None)
  File "/usr/lib/python2.7/inspect.py", line 708, in walktree
    classes.sort(key=attrgetter('__module__', '__name__'))
AttributeError: __module__
```

I started pdb and it seems that it's `pybind11_object_48` that is missing `__module__`:

```
(Pdb) 
> /usr/lib/python2.7/inspect.py(739)getclasstree()
-> return walktree(roots, children, None)
(Pdb) p roots
[<class 'pybind11_object_48'>]
(Pdb) p children
{<class 'pybind11_object_48'>: [<class 'example.Pet'>]}
(Pdb) s
--Call--
> /usr/lib/python2.7/inspect.py(705)walktree()
-> def walktree(classes, children, parent):
(Pdb) n
> /usr/lib/python2.7/inspect.py(707)walktree()
-> results = []
(Pdb) n
> /usr/lib/python2.7/inspect.py(708)walktree()
-> classes.sort(key=attrgetter('__module__', '__name__'))
(Pdb) p classes
[<class 'pybind11_object_48'>]
(Pdb) p classes[0].__class__
<class 'pybind11_type'>
(Pdb) p classes[0].__module__
*** AttributeError: AttributeError('__module__',)
(Pdb) p classes[0].__name__
'pybind11_object_48'
```

I don't understand how all this works, so that's all I can tell.

**Comment by jagerman** [comment] 2017-03-14 20:21
Cc @dean0x7d 

We intentionally don't have a `__module__` there, because this is the common base type for all wrapped classes, independent of the class's module.  We might be able to set it to `None` to avoid this.

**Comment by jagerman** [comment] 2017-03-14 20:22
Thanks for the report and debugging efforts: from your debugging it's immediately obvious where the problem is.

**Comment by wojdyr** [comment] 2017-03-14 20:39
> We might be able to set it to `None` to avoid this.

maybe empty string, None can't be compared with string in Py3

**Comment by dean0x7d** [comment] 2017-03-14 23:41
Indeed, it was a regression. Should be fixed in #729.

**Comment by wojdyr** [comment] 2017-03-15 00:59
Thanks for quick fixing.
Is there a trick to hide documentation of `pybind11_builtins.pybind11_object_*`?
Now every class has:
```
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from pybind11_builtins.pybind11_object_48:
     |  
     |  __new__ = <built-in method __new__ of pybind11_type object>
     |      T.__new__(S, ...) -> a new object with type S, a subtype of T
```

**Comment by dean0x7d** [comment] 2017-03-15 10:57
There's no way to hide it as far as I know. Pydoc is [hardcoded](https://github.com/python/cpython/blob/6f0eb93183519024cb360162bdd81b9faec97ba6/Lib/pydoc.py#L1319) to skip over `builtins.object` bases, so we can't opt into the same behavior.

**Closed** 2017-03-15 14:38 UTC
