### ISSUE TITLE
Passing by reference: Error

### ISSUE THREAD

**Issue by nyckmaia** [pybind/pybind11#2140] opened 2020-03-23 15:11 UTC
I would like to know if is possible to do that:

**C++ Side:**
```
void my_func(int& x, int& y, int& z)
{
    x++;
    y++;
    z++;
}
```
**Python Side:**
```
a = 0
b = 0
c = 0
my_module.my_func(a, b, c)

# Print Python variables:
print(a)
print(b)
print(c)

# The output should be:
1
1
1
```

But I got this output below:
```
0
0
0
```

**How can I fix it?**

Obs.: I Already tried add the `py::return_value_policy::reference`...but it didn't worked.

**Comment by termi3** [comment] 2020-03-23 17:54
no idea, but try to debug step by step and check where the value changes or does not changes. Thonny https://thonny.org/ is good in this

**Comment by carlsonmark** [comment] 2020-03-24 03:08
This seems like a duplicate of https://github.com/pybind/pybind11/issues/134

**Comment by nyckmaia** [comment] 2020-03-24 03:34
Thank you @carlsonmark ...
If I understood #134 well....this is impossible. Right?

**Comment by carlsonmark** [comment] 2020-03-24 03:53
Yeah, I think the Python equivalent would be to return a tuple of the modified values instead of modifying them in place. You can do something like this:
```
m.def("my_func",
      [](int x, int y, int z)
      {
          my_func(x, y, z);
          return std::make_tuple(x, y, z);
      });
```

Then, in Python:
```
x, y, z = my_func(x, y, z)
```

Hopefully you find a solution that works for you.

**Comment by nyckmaia** [comment] 2020-03-24 14:20
Thank you @carlsonmark ! **That's perfect!**

**Closed** 2020-03-24 14:21 UTC
