### ISSUE TITLE
Support for custom exception types

### ISSUE THREAD

**Issue by maxbelanger** [pybind/pybind11#140] opened 2016-03-21 07:26 UTC
Currently using `pybind11` and loving it! That said, I've hit a snag with a custom exception type used to wrap an `HRESULT` on Windows. My current fix is to make the exception a sub-class of `std::system_error` and then patching `pybind11` to support it. Is there a more elegant solution? Are there plans to support either `std::system_error` or the ability to add custom exception types?

**Comment by wjakob** [comment] 2016-03-21 08:26
Supporting custom exceptions is very messy..  there is no plan to do that. Supporting ``std::system_error`` would be a possibility -- please submit a PR in that case.

**Comment by wjakob** [comment] 2016-03-23 07:23
Closing this issue because this was more of a question and not a bug report.

**Closed by wjakob** 2016-03-23 07:23 UTC

**Comment by earonesty** [comment] 2023-01-09 18:00
i think it doesn't have to be too messy, if u jus allow the create of a class to modify bases to contain an exception type
