### ISSUE TITLE
Tests fail on i686 and some other architectures

### ISSUE THREAD

**Issue by susilehtola** [pybind/pybind11#694] opened 2017-02-23 20:47 UTC
I'm trying to package pybind11 in Fedora, since I need it to update the Psi4 program package.

While the tests run nicely through on x86_64, armv7hl and ppc64le, they fail on i686 and ppc64. i686 build log attached.

[build.txt](https://github.com/pybind/pybind11/files/797694/build.txt)

**Comment by jagerman** [comment] 2017-02-23 20:51
PR #619 fixed this (on master, not in 2.0.1), at least for i386 (I don't know whether that also fixed ppc64).

**Comment by susilehtola** [comment] 2017-02-23 21:01
It does indeed fix the issue on i686. However, now the tests crash on x86_64!

[build.txt](https://github.com/pybind/pybind11/files/797731/build.txt)

**Comment by susilehtola** [comment] 2017-02-23 21:04
Looks like some memory issue, the crash occurs only intermittently.

**Comment by jagerman** [comment] 2017-02-23 21:26
Is the crash with just #619 cherry-picked into 2.0.1?  It might depend on other things in master.  You're probably better off just disabling the test_numpy_dtypes.py test on i386: it wasn't a bug in pybind11 itself, but rather one in the assumptions made in the test strings.

**Comment by susilehtola** [comment] 2017-02-24 14:06
Well, given that the crash is intermittent, I can't actually say that it's related to #619. It could be some dormant issue.

I'd like to run the tests through valgrind to check for memory violations, but I'm not sure how to do that.

**Comment by jagerman** [comment] 2017-02-24 14:09
Build normally, then: `cd tests; valgrind python3 -m pytest` should work.

**Comment by susilehtola** [comment] 2017-02-24 14:45
There seems to be another problem on ppc64 in test_numpy_array.py:96.
[build.txt](https://github.com/pybind/pybind11/files/799594/build.txt)

**Comment by jagerman** [comment] 2017-02-24 21:37
Those failures don't look harmless.  I can't reproduce this on ppc64le (via QEMU) in either 2.0.1 or current master.  Perhaps an endian issue?

**Comment by susilehtola** [comment] 2017-02-25 14:13
Probably, since it succeeds on ppc64 also on the Fedora build system. It's only ppc64le that fails.

**Comment by jagerman** [comment] 2017-02-25 14:48
Did you mean that the other way around?  My build in a QEMU ppc64le worked fine.

**Comment by susilehtola** [comment] 2017-02-25 15:02
.. Yes.
https://koji.fedoraproject.org/koji/taskinfo?taskID=18032794

**Comment by jagerman** [comment] 2017-02-25 20:42
I've reproduced it with a ppc64 QEMU image.  The failures are bugs in the test suite, not pybind; I'll have a fix shortly.

**Comment by jagerman** [comment] 2017-02-25 20:43
(The 20+ minute compile time for pybind running under QEMU/ppc64 is kind of a nuissance).

**Comment by jagerman** [comment] 2017-02-25 21:47
Fixed in #699.  The fixes are only in the test suite, i.e. the failures are all false positives.

**Closed** 2017-02-26 21:59 UTC
