### ISSUE TITLE
Python3.5 incompatibility: undefined symbol

### ISSUE THREAD

**Issue by 0Xellos** [pybind/pybind11#1637] opened 2018-12-17 11:06 UTC
I have some bindings. When I build them against python2, everything is fine. When I build them against python3 and try to import the resulting module, I get `undefined symbol: _Py_ZeroStruct`. This symbol doesn't exist in python3, apparently.

How can this be fixed?

**Comment by EricCousineau-TRI** [comment] 2018-12-18 03:48
It may help to post the smallest reproduction example you have, and a little more information about your system:
- What command line stuff did you execute?
- What system are you using? (Linux, Mac, Windows)
- Are you using a system-distributed version of Python? (e.g. `/usr/bin/python3`)

Example compilation steps:
https://pybind11.readthedocs.io/en/stable/basics.html#linux-macos
For my system (Ubuntu 16.04, CMake, Python 3.5), the following works for me:
```sh
$ cd pybind11
$ mkdir build && cd build
$ cmake .. -DPYTHON_EXECUTABLE=/usr/bin/python3
$ make -j pytest
... 315 passed, 3 skipped in 4.11 seconds ...
```

You may also want to consider looking at the Gitter channel for more specific questions like this:
https://github.com/pybind/pybind11/issues/574#issuecomment-269703420

**Comment by jingnanshi** [comment] 2019-11-22 16:56
Just for future reference: I encountered the same error when compiling with pybind11 and PCL. It turns out that the VTK dependency used by PCL exports `/usr/include/python2.7` to the global include directories target. I manually removed the python 2.7 include from my build target include directories target and everything works afterwards.

**Comment by soulslicer** [comment] 2020-05-01 17:59
> Just for future reference: I encountered the same error when compiling with pybind11 and PCL using CMake. It turns out that the VTK dependency used by PCL exports `/usr/include/python2.7` to the global include directories target. I manually removed the python 2.7 include from my build target include directories target and everything works afterwards.

I tried it and it still doesnt work! Please send me an example!

**Comment by soulslicer** [comment] 2020-05-01 18:28
Ok i figured it out you must add before find PCL

```
find_package(PythonLibs 3)
include_directories(${PYTHON_INCLUDE_DIRS})
```

**Comment by 0Xellos** [comment] 2020-05-21 12:49
Back then, in the end I "solved" it by simply using an Anaconda environment created with Python 3 and forgot about it. The error appeared because the environment I used before contained Python 2 by default with Python 3 installed later.

If I remember right, it happened when I was setting `PYBIND11_PYTHON_VERSION` in CMake; include directories were set properly. Seems like the existence of libpython2.7.so still overrode it, so it wasn't used to set the linked Python library. I can try `find_package(PythonLibs 3)` and see if doesn't happen then.

**Comment by bstaletic** [comment] 2020-07-07 14:18
At this point, this issue seems like a mashup of different environment problems, stretching back two years. I'll close the issue now and whoever has a problem should open a new issue instead. Or better yet, come to gitter.

**Closed by bstaletic** 2020-07-07 14:18 UTC
