### ISSUE TITLE
FindPythonLibsNew.cmake not working with MSYS Python interpreter

### ISSUE THREAD

**Issue by fteicht** [pybind/pybind11#1406] opened 2018-05-22 17:05 UTC
FindPythonLibsNew.cmake tests for windows system (CMAKE_HOST_WIN32 is true) then it assumes that the Python interpreter works with windows-like directories hierarchy (lines 141-143).
However, it does not work when using MSYS' python interpreter which assumes a Unix-like directories hierarchy.
Note that compiling python bindings with MSYS' mingw compiler requires to use MSYS' python interpreter. For instance, anaconda's interpreter's include files do not need to be compatible with MSYS' compiler due to version mismatch.

**Comment by xiaowen64** [comment] 2019-02-04 23:02
this doesn't work on MSYS2

CMake Error at tools/FindPythonLibsNew.cmake:158 (message):
  Python libraries not found
Call Stack (most recent call first):
  tools/pybind11Tools.cmake:16 (find_package)
  CMakeLists.txt:33 (include)

**Comment by samuelpmish** [comment] 2019-02-09 07:09
same issue-- my underlying C++ code gets about a 2x speedup when compiling with gcc (via MinGW) versus visual studio, but I can't generate python bindings for it, because of these errors and incompatibility with MinGW.

What would need to change to support the MinGW toolchain on Windows?

**Comment by wojdyr** [comment] 2019-06-10 13:55
FTR MSYS2 is now packaging patched pybind11
https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-pybind11
(but it still doesn't work out of the box for me)

**Comment by wjakob** [comment] 2019-07-21 08:19
@wojdyr , @samuelpmish , @xiaowen64, @fteicht : would you be able to test @kanonet's PR #1851 and provide feedback on whether the issue is completely resolved after that?

**Comment by kanonet** [comment] 2019-08-04 01:23
What will happen if they do not answer? Will my fix get released? Is there anything I can do?

**Comment by wjakob** [comment] 2019-08-13 19:42
closed via #1851

**Closed by wjakob** 2019-08-13 19:42 UTC
