### ISSUE TITLE
why pybind11 is slower than Python and boost python; the benchmark does not include performance test?

### ISSUE THREAD

**Issue by Dalaba** [pybind/pybind11#1825] opened 2019-07-02 04:17 UTC
pybind11 example:
#include<pybind11/pybind11.h>
namespace py = pybind11;
int test(int t) {
	return t * t;
}
PYBIND11_MODULE(pybindexample, m) {
	m.def("testFunc", &test);
}
then export as .pyc

Python example:
from pybindexample import testFunc
def pytestFunc(arg):
	return arg * arg

final results:
t1 = timeit.Timer('pytestFunc(10)', 'from __main__ import pytestFunc')
print t1.timeit()
t1 = 0.07

t2 = timeit.Timer('testFunc(10)', 'from __main__ import testFunc')
print t2.timeit()
t2 = 0.26

**Comment by molpopgen** [comment] 2019-08-10 02:06
This is a duplicate of #1227. Take a look there.

**Comment by YannickJadoul** [comment] 2020-07-11 22:48
Thanks for answering this, @molpopgen!

I don't see a Boost.Python example, so I can't compare if pybind11 is slower.

**Closed by YannickJadoul** 2020-07-11 22:48 UTC
