### ISSUE TITLE
Child Class Method Not Being Called as Expected, Base Class Method Called Instead

### ISSUE THREAD

**Issue by bgoodman44** [pybind/pybind11#1552] opened 2018-10-04 12:33 UTC
Hello,

I have a simple test case for polymorphism that isn't working quite right..  I have two C++ classes, Client and Dispatcher.  Dispatcher has a method called  "Dispatch" that takes a Client* as an input, and calls the the clients virtual ProcessEvent() method.  I've made both of these classes available to python using the code below.  I've derived from the Client class as the python class SomeClient, and overridden its ProcessEvent function.  When I call "Dispatch" from anywhere EXCEPT inside the SomeClient::ProcessEvent method, everything works as expected, i get a report from the child class.  But when I call Dispatch from within SomeClient::ProcessEvent, the base classes ProcessEvent is called.  Any ideas what could be going wrong here?  I expect to get an infinite recursion that results in SomeClient::ProcessEvent being called forever.

C++:
```
#include <iostream>
#include "pybind11/pybind11.h"

namespace py = pybind11;
class Dispatcher;
class Client
{
public:
    Client(Dispatcher* disp): PtrD(disp)
    {
        std::cout << "In Client::Client\n";
    }
    virtual ~Client(){};
    virtual void ProcessEvent()
    {
        std::cout << "THIS SHOULDN'T HAPPEN --In Client::ProcessEvent\n";
    }
    Dispatcher* PtrD;
};
```
```
class Dispatcher
{
public:
    Dispatcher()
    {
        std::cout << "In Dispatcher::Dispatcher\n";
    }
    virtual ~Dispatcher(){};

    void Dispatch(Client* client)
    {
        std::cout << "Dispatcher::Dispatch called by " << client << std::endl;
        client->ProcessEvent();
    }
};
```
```
class DispatcherTrampoline : public Dispatcher
{
public:
    using Dispatcher::Dispatcher;
};
```
```
class ClientTrampoline : public Client
{
public:
    using Client::Client;

    void ProcessEvent() override
    {
        PYBIND11_OVERLOAD(void,Client,ProcessEvent,);
    }
};
```
```
PYBIND11_MODULE(libTestCase,mod)
{
    py::class_<Client,ClientTrampoline> cli(mod,"Client");
    cli.def(py::init<Dispatcher* >());
    cli.def("ProcessEvent",&Client::ProcessEvent);
    cli.def_readwrite("PtrD",&Client::PtrD);

    py::class_<Dispatcher,DispatcherTrampoline> dsp(mod,"Dispatcher");
    dsp.def(py::init< >());
    dsp.def("Dispatch",&Dispatcher::Dispatch);
}

```

Python Test:

```
from build.libTestCase import Client,Dispatcher

class SomeClient(Client):
    def __init__(self,d):
        print("In SomeClient::__init__")
        super().__init__(d);

    def ProcessEvent(self):
        print("in SomeClient::ProcessEvent,about to call self.ProcessEvent")
        self.PtrD.Dispatch(self);

if __name__ == "__main__":
    dd = Dispatcher()
    cl = SomeClient(dd)
    dd.Dispatch(cl)
```

TERMINAL OUTPUT:
```
In Dispatcher::Dispatcher
In SomeClient::__init__
In Client::Client
Dispatcher::Dispatch called by 0x20bb270
in SomeClient::ProcessEvent,about to call self.ProcessEvent
Dispatcher::Dispatch called by 0x20bb270
THIS SHOULDN'T HAPPEN --In Client::ProcessEvent
```

**Comment by bgoodman44** [comment] 2018-10-05 18:40
I'll pay actual money for a solution to my problem!!

https://www.upwork.com/job/Fix-bug-Simple-Python-PyBind11-Module_~01155fc34bd0078416/

**Comment by bgoodman44** [comment] 2018-10-08 11:53
Opened up a stackoverflow question as well:

https://stackoverflow.com/questions/52648465/pybind11-virtual-child-class-method-not-being-called-during-
recursion-base-call?noredirect=1#comment92297440_52648465

**Comment by bgoodman44** [comment] 2018-10-08 11:57
Uploaded project sources and CMakeList file.  Also included a version written in pure python to show how it should work.

[Files.zip](https://github.com/pybind/pybind11/files/2455776/Files.zip)

**Comment by cmdawson** [comment] 2018-10-09 02:20
In `get_overload_type` there is a check on the current `PyFrameObject` to ensure it's not resolving an overload from within an overload with the same name. 
```
(std::string) str(frame->f_code->co_name) == name
```
(both sides of this are `ProcessEvent` in the second call). It looks like this precludes any recursive calls to a virtual function overloaded in python.

**Comment by EricCousineau-TRI** [comment] 2020-12-29 23:05
Possibly relates:
- #1333 (slicing)
- #1922 (the overload cache), which could be addressed by #2092

**Comment by EricCousineau-TRI** [comment] 2021-01-07 23:01
FYI Rather than #2092, you can try the later PR, #2772

**Comment by EricCousineau-TRI** [comment] 2021-01-22 15:42
Trying out repro - can reproduce your issue on latest master:
https://github.com/pybind/pybind11/compare/master...EricCousineau-TRI:issue-1552-repro

**Comment by EricCousineau-TRI** [comment] 2021-01-22 15:51
I think it was because you relied on an odd recursive dispatch between `Client.ProcessEvent()` and `Dispatcher.Dispatch()`. (That doesn't appear to be double-dispatch, b/c you're not really resolving to concrete overloads on the first virtual call)

I simplified your example, and could make it work: 597752aa
```sh
$ cd pybind11
$ mkdir build && cd build && cmake .. && env PYTEST_ADDOPTS="-s -x" make pytest
../../tests/test_issue1552.py In Dispatcher::Dispatcher
...
In SomeClient::__init__
In Client::Client
Dispatcher::Dispatch called by 0x1491850
Python ProcessEvent
```

For more details on how to configure the tests, please see:
https://github.com/pybind/pybind11/blob/08bca374fdcf3831e8ad15246fbd3b2d5675b4a5/.github/CONTRIBUTING.md

Closing for now.

**Closed by EricCousineau-TRI** 2021-01-22 15:51 UTC
Labels: holders
