### ISSUE TITLE
Can I use the NTL's function in it?

### ISSUE THREAD

**Issue by Huelse** [pybind/pybind11#1901] opened 2019-08-31 13:11 UTC
I'm trying write a lib which I can use the NTL's func in the Python.

But when I use the `ZZ` define a data (a kind of custom big integer from NTL), the lib in Python will must be core dump even I did nothing.

here is a example:
```
#include <pybind11/pybind11.h>
#include <iostream>
#include <NTL/ZZ.h>

namespace py = pybind11;

using namespace std;
using namespace NTL;

ZZ a = 10;

PYBIND11_MODULE(NTLTest, m)
{
	m.doc() = "pybind11 example plugin";
}
```

It't can be compile with cmake or setuptools, then `import NTLTest`
```
$ python test.py
Segmentation fault (core dumped)
```
If anyone could help me? Thanks a lot!

**Comment by Huelse** [comment] 2019-09-01 06:34
If anyone can give me a answer!

**Comment by mmodenesi** [comment] 2019-09-01 12:02
Have you seen https://pybind11.readthedocs.io/en/master/faq.html#the-python-interpreter-immediately-crashes-when-importing-my-module ?

**Comment by Huelse** [comment] 2019-09-01 12:16
@mmodenesi 
Yes I know. But I think it's neither ImportError nor NameError. 
If delete `ZZ a = 10;` this line.  The module can run successfully.
like this:
```
import NTLTest
print(dir(NTLTest))

$> python3 test.py
$> ['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']
```

**Comment by sizmailov** [comment] 2019-09-01 13:18
@Huelse does next program segfaults as well?

```C++
#include <iostream>
#include <NTL/ZZ.h>
using namespace std;
ZZ a = 10;
int main(){
   cout << "hello" << endl;
}
```

**Comment by Huelse** [comment] 2019-09-01 13:51
@sizmailov 
Absoultly it could.
This is a famous library for doing Number Theory [](https://www.shoup.net/ntl/)

**Comment by sizmailov** [comment] 2019-09-01 15:51
>  Absoultly it could. 

@Huelse That's why I'm asking. Please go and check. If error is still here then the error is not related to pybind11, otherwise it _might_ be related. 

I cannot reproduce segfault on ubuntu 18.04 with gcc-7 with NTL (11.3.2). Your example compiles and runs fine.

Note, to build with pybind11, I had to change `src/DoConfig` from NTL dist to enable fPIC build:
```Perl
%MakeFlag = (
'SHARED'  => 'on', # <- turned on 
'NATIVE'  => 'on',
);
```

By the way `int` cannot be assigned to `NTL::ZZ` without cast, so `ZZ a = 10;` won't compile, but `ZZ a{10};` will. 

<details>

<summary>            CMakeLists.txt to build your example (with mentioned fix);

</summary>

```Cmake

cmake_minimum_required(VERSION 3.14)
project(NTL)

set(CMAKE_CXX_STANDARD 14)

find_package(PythonInterp REQUIRED)
find_package(PythonLibs "${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}" REQUIRED )
if (PYTHONLIBS_FOUND)
    include_directories(${PYTHON_INCLUDE_DIRS})
    message("Using default python version: " ${PYTHONLIBS_VERSION_STRING})
endif()

# add pybind11
add_subdirectory(external/pybind11)
include_directories(SYSTEM external/pybind11/include)

# Create NTLTest module
pybind11_add_module(NTLTest main.cpp)

# Add NTL dependency to NTLTest
target_link_libraries(NTLTest PUBLIC ntl gmp pthread)
target_link_directories(NTLTest PUBLIC ./local/lib)
target_include_directories(NTLTest PUBLIC ./local/include)
```

</details>

**Comment by Huelse** [comment] 2019-09-01 17:36
@sizmailov 
Thank you. I had found my problems.

First, I didn't make install it, just used the lib in the src folder.

Secenod, [NTLExample](https://www.shoup.net/ntl/doc/tour-ex1.html) tell me `int` can be assigned to `NTL::ZZ`, maybe I misunderstood it.

Forgive my folly, have a nice day! Thanks again.

**Comment by sizmailov** [comment] 2019-09-01 18:21
Well yes, you can assign, but cannot initialize, and it's explicitly mentioned on the example page you linked:

>  One can also assign a value of type long to a ZZ:
> 
>   ZZ x;
>   x = 1;
>
> Note that one cannot write
>
>   ZZ x = 1;  // error

Please close the issue if you find it solved

**Closed** 2019-09-02 01:31 UTC
