### ISSUE TITLE
[BUG]: Cannot cast function as C-style function pointer

### ISSUE THREAD

**Issue by mvadari** [pybind/pybind11#4538] opened 2023-02-28 16:56 UTC
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

2.10.1

### Problem description

I'm trying to cast a Python function as a C-style function pointer. This doesn't seem to be working properly - it compiles fine, but at runtime I get the following error:
```
libc++abi: terminating with uncaught exception of type pybind11::cast_error: Unable to cast Python instance of type <class 'function'> to C++ type 'void ()'
```

### Reproducible example code

```cpp
typedef void (*funcPtr)();
funcPtr
get_function_from_python(std::string pathToFile)
{
    py::scoped_interpreter guard{}; // start the interpreter and keep it alive
    py::object sys = py::module_::import("sys");
    py::object pathAppend = sys.attr("path").attr("append");
    pathAppend(pathToFile.c_str());
    py::object plugin = py::module_::import("plugin");
    return plugin.attr("dummy").cast<funcPtr>();
};
get_function_from_python("./plugin.py")
```

plugin.py:
```py
def dummy():
    print("HII")
```

Error is above.

### Is this a regression? Put the last known working version here if it is.

Not a regression

**Comment by Lalaland** [comment] 2023-03-02 21:58
You generally can't convert python functions to function pointers. 

However, pybind11 does have a feature to convert python functions to std::function objects. See https://pybind11.readthedocs.io/en/stable/advanced/cast/functional.html

Note that you need to include that header file to enable this feature.

I'm going to close this as not a bug, but feel free to re-open if you run into any other issues.

**Closed by Lalaland** 2023-03-02 21:58 UTC
Labels: triage
