### ISSUE TITLE
Custom C++ Exception not being registered

### ISSUE THREAD

**Issue by newling** [pybind/pybind11#1576] opened 2018-10-24 01:32 UTC
I've been using pybind11 for 3 weeks now and am extremely impressed; thanks to all involved.

## Issue description
A custom C++ Exception is only being used in certain cases after being registered:

In file `quu.hpp` the custom Exception class is defined
```c++
namespace quu{
  class error : public std::runtime_error { ... };
  void bar{ throw error(""); }
} 
```

In the pybind11 binding file, the Exception is registered,
```c++
#include <pybind11/pybind11.h>
#include <quu.hpp>

void foo(){ throw quu::error(""); }

PYBIND_MODULE(pyquu, m){
  m.def("foo", &foo);
  m.def("bar", &quu::bar);
  py::register_exception<quu::error>(m, "QuuException");
}

```

And then when it is used, 
```python
import pyquu
pyquu.foo()  # throws QuuException (yay!)
pyquu.bar()  # throws RuntimeError
```

the function defined in the same translation unit as the PYBIND_MODULE has its Exception correctly converted to the custom QuuException, but the function defined externally has its Exception mapped to the generic Python RuntimeError. 

How can I get pyquu.bar() to throw a QuuException? I suspect my problem is related to this sentence from the documentation

> When a C++ exception is thrown, the registered exception translators are tried in reverse order of registration

but can't figure it out how exactly.

## Reproducible example code

If the above description is insufficient i can provide compilable code.

**Comment by bstaletic** [comment] 2020-07-09 08:07
I can't reproduce this at all.

```
>>> from pyquu import *
>>> foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyquu.QuuException
>>> bar()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyquu.QuuException
```

That's coming from this extension module:

```c++
#include <stdexcept>
#include <pybind11/pybind11.h>

namespace quu{
  class error : public std::runtime_error { using std::runtime_error::runtime_error; };
  void bar(){ throw error(""); }
} 

void foo(){ throw quu::error(""); }

PYBIND11_MODULE(pyquu, m){
  m.def("foo", &foo);
  m.def("bar", &quu::bar);
  pybind11::register_exception<quu::error>(m, "QuuException");
}
```

Since this issue is from 2018, I'm going to close it. If there's still a problem, feel free to reopen.

**Closed by bstaletic** 2020-07-09 08:07 UTC
