### ISSUE TITLE
std::vector member of boost::optional struct is emptied if any members of the struct are accessed

### ISSUE THREAD

**Issue by steinmig** [pybind/pybind11#2280] opened 2020-07-07 06:28 UTC
Hi,

I am totally confused by this behavior and after running around in circles, I hope you guys can help me. <br />
I have a hierarchical data structure of 3 structs in C++, which I renamed in my minimum working example (mwe) House, Room, and Objects. Room is a boost::optional type and has a std::vector<Object> member containing all Objects in this room. The Objects are just a container for some numbers.<br />
I am aware that this is  overly complex for such information, but it is necessary in the original code and cannot be changed easily. I tried to change it into a std::experimental::optional since we do not use c++17, but this broke some parts in our c++ code.<br />

In C++, I have no issues at all and the boost::optional and all member variables work perfectly. But after binding everything I run into the weird problem that the std::vector objects is emptied as soon as I access any member variables of the Room. This can be either the length, width, area or the objects itself as shown in the python example. If the objects are accessed for the first time, they are actually returned normally, but when trying the second access they are gone as if the had been moved. The same behavior applies if you perform x = myHouse.kitchen.objects.copy(). The list is in x and can even be accessed multiple times, but the information in kitchen is immediately lost. Weirdly, this also only applies to the objects and all other double members can be accessed indefinitely.<br />
For convenience of compiling everything for the mwe, I stuffed everything into a single cpp file, which is obviously not the case in the original code. The mwe is included as a zip file and is executed with the .py file. The c++ code is compiled and included via cppimport, but also manual compilation does not change anything. <br />
Here is the complete code, if you don't want to download the zip: <br/>
mwe.cpp: <br />

```cpp

#include <boost/optional.hpp>
#include <iostream>
#include <map>
#include <string>
#include <vector>
#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

/* implementing structs */
struct Object {
  Object() = default;
  Object(double price, double height) : price(price), height(height) {
  };

  double price = 0.0;
  double height = 0.0;
};

struct Room {
  Room() = default;

  double length;
  double width;
  std::vector<Object> objects; // this is the buggy vector

  double area() const {
    return length * width;
  };
};

struct House {
  House() = default;

  boost::optional<Room> bedroom;
  boost::optional<Room> kitchen;
  boost::optional<Room> livingroom;

  std::map<std::string, std::vector<Object>> getObjects() {
    std::map<std::string, std::vector<Object>> out;
    if (bedroom) {
      out.insert(std::make_pair("bedroom", bedroom->objects));
    }
    if (kitchen) {
      out.insert(std::make_pair("kitchen", kitchen->objects));
    }
    if (livingroom) {
      out.insert(std::make_pair("livingroom", livingroom->objects));
    }
    return out;
  };
};

/* everything works fine in C++ -> get data this way to have complete object map */
House initSomethingInCpp() {
  auto myHouse = House();
  myHouse.bedroom = Room();
  myHouse.kitchen = Room();

  myHouse.bedroom->length = 10.0;
  myHouse.bedroom->width = 2.0;
  myHouse.kitchen->length = 5.0;
  myHouse.kitchen->width = 3.0;

  std::vector<Object> bedroomObjects;
  std::vector<Object> kitchenObjects;

  Object closet = Object(100.0, 2.5);
  Object bed = Object(200.0, 1.0);
  Object oven = Object(500.0, 1.5);
  Object table = Object(50.0, 1.5);

  bedroomObjects.push_back(closet);
  bedroomObjects.push_back(bed);
  kitchenObjects.push_back(oven);
  kitchenObjects.push_back(table);

  myHouse.bedroom->objects = bedroomObjects;
  myHouse.kitchen->objects = kitchenObjects;

  return myHouse;
};

namespace pybind11 {
/* taking care of boost type */
namespace detail {
/* boost::optional */
template<typename T>
struct type_caster<boost::optional<T>> : optional_caster<boost::optional<T>> {};
} // namespace detail
} // namespace pybind11


/* binding structs */
void init_house(pybind11::module& main) {
  pybind11::class_<House> house(main, "House");
  house.def(pybind11::init<>());

  house.def_readwrite("bedroom", &House::bedroom);
  house.def_readwrite("kitchen", &House::kitchen);
  house.def_readwrite("livingroom", &House::livingroom);
  house.def("get_objects", &House::getObjects);
};

void init_room(pybind11::module& main) {
  pybind11::class_<Room> room(main, "Room");
  room.def(pybind11::init<>());
  room.def_readwrite("length", &Room::length);
  room.def_readwrite("width", &Room::width);
  room.def_readwrite("objects", &Room::objects);
  room.def_property_readonly("area", &Room::area);
};

void init_objects(pybind11::module& main) {
  pybind11::class_<Object> object(main, "Object");
  object.def(pybind11::init<>());
  object.def(pybind11::init<double, double>());

  object.def_readonly("price", &Object::price);
  object.def_readonly("heigth", &Object::height);
};

/* define module and bind init_in_cpp function */
PYBIND11_MODULE(mwe, m) {
 init_house(m);
 init_room(m);
 init_objects(m);
 m.def("init_something_in_cpp", &initSomethingInCpp);
};
```

<br />
execute.py: <br />

```python
import cppimport
#cppimport.set_quiet(False)
#cppimport.force_rebuild()
mod = cppimport.imp('mwe')

# get data
myHouse = mod.init_something_in_cpp()

print("\n")
print("all data is here")
objs = myHouse.get_objects()
print(objs)
print(myHouse.kitchen.area) # by accessing kitchen members, the objects list is emptied
print("\n")

print("kitchen objects are now missing")
objs = myHouse.get_objects()
print(objs)
print("but area still works:")
print(myHouse.kitchen.area) # everything but objects still works
print("\n")

print("also works directly with same variable")
print("bedroom objects are accessed:")
print(myHouse.bedroom.objects)
print("bedroom objects are accessed again:")
print(myHouse.bedroom.objects)
```

<br />
The execution gives the following output:<br />

all data is here
{'bedroom': [<mwe.Object object at 0x7fbc9c2a43f0>, <mwe.Object object at 0x7fbc9c2a4670>], 'kitchen': [<mwe.Object object at 0x7fbc9c2a4c30>, <mwe.Object object at 0x7fbc9c2a4df0>]}
15.0
<br />

kitchen objects are now missing
{'bedroom': [<mwe.Object object at 0x7fbc9c2a4e70>, <mwe.Object object at 0x7fbc9c2a4eb0>], 'kitchen': []}
but area still works:
15.0
<br />

also works directly with same variable
bedroom objects are accessed:
[<mwe.Object object at 0x7fbc9c2a4c30>, <mwe.Object object at 0x7fbc9c2a4df0>]
bedroom objects are accessed again:
[]
<br />

[mwe.zip](https://github.com/pybind/pybind11/files/4882801/mwe.zip)

**Comment by YannickJadoul** [comment] 2020-07-07 15:47
What Python and pybind11 versions are you using? I can't reproduce this example, somehow :-(

```
yannick@Athenai:~/tmp/sandbox/build$ python3.8
Python 3.8.0 (default, Oct 28 2019, 16:14:01) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import example
>>> example
example
>>> example.
example.House(                  example.Object(                 example.Room(                   example.init_something_in_cpp(
>>> example.myHouse = mod.init_something_in_cpp()
KeyboardInterrupt
>>> myHouse = example.init_something_in_cpp()
>>> print("\n")


>>> print("all data is here")
all data is here
>>> objs = myHouse.get_objects()
>>> print(objs)
{'bedroom': [<example.Object object at 0x7f63ea16a730>, <example.Object object at 0x7f63ea16a8f0>], 'kitchen': [<example.Object object at 0x7f63ea16a970>, <example.Object object at 0x7f63ea16a9b0>]}
>>> print(myHouse.kitchen.area) # by accessing kitchen members, the objects list is emptied
15.0
>>> print("\n")


>>> print("kitchen objects are now missing")
kitchen objects are now missing
>>> objs = myHouse.get_objects()
>>> print(objs)
{'bedroom': [<example.Object object at 0x7f63ea16a9f0>, <example.Object object at 0x7f63ea16aa70>], 'kitchen': [<example.Object object at 0x7f63ea16aaf0>, <example.Object object at 0x7f63ea16ab30>]}
>>> print("but area still works:")
but area still works:
>>> print(myHouse.kitchen.area) # everything but objects still works
15.0
>>> print("\n")


>>> print("also works directly with same variable")
also works directly with same variable
>>> print("bedroom objects are accessed:")
bedroom objects are accessed:
>>> print(myHouse.bedroom.objects)
[<example.Object object at 0x7f63ea16a930>, <example.Object object at 0x7f63ea16a730>]
>>> print("bedroom objects are accessed again:")
bedroom objects are accessed again:
>>> print(myHouse.bedroom.objects)
[<example.Object object at 0x7f63ea16a970>, <example.Object object at 0x7f63ea16a730>]
>>> 
```

**Comment by YannickJadoul** [comment] 2020-07-07 15:50
Same if I execute your `mwe.zip` example (thanks for the nice self-contained example, btw!) directly:

```
yannick@Athenai:~/mwe$ python3 execute.py 


all data is here
{'bedroom': [<mwe.Object object at 0x7f939d312dc0>, <mwe.Object object at 0x7f939d312df8>], 'kitchen': [<mwe.Object object at 0x7f939d312e68>, <mwe.Object object at 0x7f939d312ea0>]}
15.0


kitchen objects are now missing
{'bedroom': [<mwe.Object object at 0x7f939d312f10>, <mwe.Object object at 0x7f939d312f48>], 'kitchen': [<mwe.Object object at 0x7f939d312fb8>, <mwe.Object object at 0x7f939d2ab030>]}
but area still works:
15.0


also works directly with same variable
bedroom objects are accessed:
[<mwe.Object object at 0x7f939d312e68>, <mwe.Object object at 0x7f939d312e30>]
bedroom objects are accessed again:
[<mwe.Object object at 0x7f939d312ea0>, <mwe.Object object at 0x7f939d312e30>]
```

**Comment by steinmig** [comment] 2020-07-07 17:34
@YannickJadoul That is very strange. I used python 3.7.7, and pybind11 2.5.0. I just tried it with python3.8, but still no luck. <br />
The gcc in /usr/bin is 9.3.0, but Anaconda apparently uses gcc 7.3.0. I am not sure whether this is the reason. I'll try to upgrade it

**Comment by YannickJadoul** [comment] 2020-07-07 17:45
I don't know what I used, but ...

Can you make sure that the `pybind11` that is found by `cppimport` really is 2.5.0, maybe by printing `PYBIND11_VERSION_MAJOR`, `PYBIND11_VERSION_MINOR`, and `PYBIND11_VERSION_PATCH`? I just really want to be sure this wasn't resolved at some point, but `cppimport` is not picking up on some weird old hidden version on your machine.

**Comment by YannickJadoul** [comment] 2020-07-07 17:47
The main problem is that apart from not being able to reproduce the issue, I also can't think which part would be so fishy that this happens.

Another thing to try: can you print some stuff in the constructors (including copy ctr and move ctr) and destructors of your classes?

**Comment by steinmig** [comment] 2020-07-07 18:09
I also compiled it in the command line with 
```
g++` -O3 -Wall -shared -std=c++11 -fPIC `python3 -m pybind11 --includes` mwe.cpp -o mwe`python3-config `--extension-suffix`
```
and then imported the .so file, so I don't think cppimport is the issue here. I cout the version in the module definition and got 2.5.0 both with and without cppimport.<br />

Sorry, I am not sure, what do you mean with the copy and move ctr?

**Comment by YannickJadoul** [comment] 2020-07-07 18:14
> I cout the version in the module definition and got 2.5.0 both with and without cppimport.

OK, thanks, then at least that's ruled out!

> Sorry, I am not sure, what do you mean with the copy and move ctr?

Sorry, the copy and move constructors. But maybe the constructor and destructor are good enough to start. I'd like to know if objects get destructed or moved, somehow.

**Comment by YannickJadoul** [comment] 2020-07-07 18:16
Another thing to try: what happens if you try the same code with `std::optional`? I read that you can't use it in your project, but you could use it in the minimal example, right? So I'm curious to see if it behaves the same or not.

**Comment by steinmig** [comment] 2020-07-07 18:23
> Another thing to try: what happens if you try the same code with std::optional? I read that you can't use it in your project, but you could use it in the minimal example, right? So I'm curious to see if it behaves the same or not.

I actually tried that after posting it and forgot to update it. Same behavior here.<br>
I'll try that with the constructors

**Comment by steinmig** [comment] 2020-07-07 18:30
I only inserted something for the Object struct, since this is disappearing. Here is the output, I added some print functions to split the c++/python part in a way:<br>
```
using bound init_something_in_cpp function
Object is constructed
Object is constructed
Object is constructed
Object is constructed
Object is destructed
Object is destructed
Object is destructed
Object is destructed
Object is destructed
Object is destructed
Object is destructed
Object is destructed
Object is destructed
Object is destructed


finished now getting objects
all data is here
Object is destructed
Object is destructed
Object is destructed
Object is destructed
{'bedroom': [<mwe.Object object at 0x7f1622736a70>, <mwe.Object object at 0x7f1622742770>], 'kitchen': [<mwe.Object object at 0x7f16227427f0>, <mwe.Object object at 0x7f1622742830>]}
Object is destructed
Object is destructed
15.0


kitchen objects are now missing
Object is destructed
Object is destructed
Object is destructed
Object is destructed
Object is destructed
Object is destructed
{'bedroom': [<mwe.Object object at 0x7f16227428b0>, <mwe.Object object at 0x7f16227428f0>], 'kitchen': []}
but area still works:
15.0


also works directly with same variable
bedroom objects are accessed:
[<mwe.Object object at 0x7f1622736c70>, <mwe.Object object at 0x7f16227427f0>]
Object is destructed
Object is destructed
bedroom objects are accessed again:
[]
Object is destructed
Object is destructed


```

**Comment by YannickJadoul** [comment] 2020-07-07 18:38
Alright. I managed to reproduce. Something changed between `v2.5.0` and the current `master`.

**Comment by YannickJadoul** [comment] 2020-07-07 18:46
Aha. Duplicate of #1919! And there is a fix on `master` (#2134), but it's not been released.

**Comment by YannickJadoul** [comment] 2020-07-07 18:50
For what it's worth, it broke somewhere between 2.2.3 and 2.2.4.

Can you use `master` until a new version is released? I think the master branch should be reasonably stable.

**Comment by YannickJadoul** [comment] 2020-07-07 18:55
At any rate, there's not much more we can do, except for getting out a release (hopefully soon enough, but we're currently cleaning up the issues/PRs, so it would be good to make a patch release after all that). All is explained in #1919 and #2134, if you want to apply some manual patches, rather than use `master`.

**Comment by YannickJadoul** [comment] 2020-07-07 18:56
Thanks for all your debugging feedback, btw, @steinmig, and for the great minimal example!

**Closed by YannickJadoul** 2020-07-07 18:55 UTC

**Comment by steinmig** [comment] 2020-07-07 18:57
Ah great, thanks a lot!<br>

On a side note:
I just tried to clone your repo, the build went fine, but when trying to compile my cpp file I get the missing python.h issue: https://github.com/pybind/pybind11/issues/1728 <br>

I have python3-dev installed, so not sure what the reason behind this is. Is there anything else I can read concerning this problem?

**Comment by YannickJadoul** [comment] 2020-07-07 19:10
>  I just tried to clone your repo, the build went fine, but when trying to compile my cpp file I get the missing python.h issue: #1728

With CMake, or with `python -m pybind11 --includes`? And that `python3-dev` is the same Python version as the one detected by CMake?

**Comment by steinmig** [comment] 2020-07-07 19:21
I used cmake for your repo and tried to compile the mwe.cpp with the command mentioned above. That's when I got the error. I also tried different version specifications for the cmake of your repo since this was mentioned in the issue. <br>

But I guess this is actually easier to fix in our project since we already clone your repo in our workflow, so I don't want to open another discussion here.<br>

Thanks a lot again for the help!

**Comment by YannickJadoul** [comment] 2020-07-07 19:23
> I used cmake for your repo and tried to compile the mwe.cpp with the command mentioned above. That's when I got the error. I also tried different version specifications for the cmake of your repo since this was mentioned in the issue.

Then CMake probably detected another Python version than the one for which you installed the headers with `python3-dev`? Have a look at the output from running CMake; it should tell you.
