### ISSUE TITLE
binding to api that that overloads allocation/deallocation operators

### ISSUE THREAD

**Issue by kevinbombadil** [pybind/pybind11#206] opened 2016-05-22 20:47 UTC
I'm trying to create a python binding for libdar-2.5.4 - a c++11 library that creates archives in a similar manner to tar. Most of the classes I want to bind inherit from a class called on_pool - it uses the new [] operator to overload the construction 
http://dar.sourceforge.net/doc/html/classlibdar_1_1on__pool.html
you can see the code here:
http://dar.sourceforge.net/doc/html/on__pool_8hpp_source.html
]
I'm having trouble knowing how to bind to classes that inherit from on_pool - or whether in fact its a smart thing to do. For example, if I bind bool_mask:
py::class_<libdar::bool_mask>(m, "bool_mask").def(py::init<bool>());
 .. I'll get this error
pybind11.h:978:67: error: no matching function for call to 'libdar::bool_mask::operator new(sizetype, libdar::bool_mask*&)
Currently I'm thinking of writing sibling classes for the on_pool-inherited classes I want to bind and copy from one to the other - its not as efficient but will get around the problem. It would be nice to know whether its possible/sane to attempt to bind directly when the constructor overloading stuff is going on.

**Comment by wjakob** [comment] 2016-05-22 20:49
If you'd like somebody to take a look, please provide a minimal reproducible example that illustrates the issue and does not depend on this library. With the instructions you provided, it's simply hard to say.

**Comment by kevinbombadil** [comment] 2016-05-22 22:58
Thanks for the quick reply - I'll need some time to put that together - will post it back here soon.

**Comment by wjakob** [comment] 2016-05-24 22:14
I'll close this for now since there is nothing actionable -- please comment when you have an example, and I'll reopen.

**Closed by wjakob** 2016-05-24 22:14 UTC

**Comment by kevinbombadil** [comment] 2016-05-25 04:03
Thanks wjakob - a colleague has solved this one for me. Its turns out the libdar library was at fault - he's got a fix to post for them and now my pybind11 binding is working fine.
