### ISSUE TITLE
lister_caster did not be called constructed function(using Debug build)

### ISSUE THREAD

**Issue by wanghuancoder** [pybind/pybind11#2323] opened 2020-07-24 02:13 UTC
## Issue description
Hello!
We used pybind11(v2.2.4) in Paddle(https://github.com/PaddlePaddle/Paddle). And there is crash when using Debug build（Release OK）。
1.
The crash is triggered at:
https://github.com/pybind/pybind11/blob/v2.2.4/include/pybind11/stl.h#L144
a1be85f
`144                    value.clear();`

Due to struct list_caster did not be called constructed function, thus the vector 'value' did not be called constructed function eather.
Thus, vector 'value' size is big whitout of initialization。value.clear() triggered the crash.

The list_caster is holded by variable 'argcasters' of 'argument_loader' at:
https://github.com/pybind/pybind11/blob/v2.2.4/include/pybind11/cast.h#L1877
a1be85f
`1877               std::tuple<make_caster<Args>...> argcasters;`
2.
When crashed，
'std::tuple<make_caster<Args>...> argcasters;' is:
std::tuple<pybind11::detail::type_caster<paddle::operators::reader::OrderedMultiDeviceLoDTensorBlockingQueue, void>, pybind11::detail::type_caster<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >, void> > argcasters;
(Provide a short description, state the expected behavior and what actually happens.)

## Reproducible example code
Please see #https://github.com/PaddlePaddle/Paddle/issues/24863
(The code should be minimal, have no external dependencies, isolate the function(s) that cause breakage. Submit matched and complete C++ and Python snippets that can be easily compiled and run to diagnose the issue.)

EDIT (@YannickJadoul): *After reading, remove this checklist and the template text in parentheses below.*

**Comment by YannickJadoul** [comment] 2020-07-24 17:57
v2.2.4 is quite old (almost 2 years). Does this still happen with v2.5.0?

**Comment by YannickJadoul** [comment] 2020-07-24 17:59
I also don't really find a minimal example in PaddlePaddle/Paddle#24863. Would you mind copy-pasting the relevant code, here, such that I can compile and try myself?

**Comment by wanghuancoder** [comment] 2020-07-27 01:45
> v2.2.4 is quite old (almost 2 years). Does this still happen with v2.5.0?

v2.2.4 and v2.5.0 are incompatible。I could not run successfully with v2.5.0. But it's not about this issue。

**Comment by wanghuancoder** [comment] 2020-07-27 01:57
> I also don't really find a minimal example in [PaddlePaddle/Paddle#24863](https://github.com/PaddlePaddle/Paddle/issues/24863). Would you mind copy-pasting the relevant code, here, such that I can compile and try myself?

Unfortunately，it's a complex environment. I tried to provide a minimal example, but failed.
You can compile as follows：
https://www.paddlepaddle.org.cn/documentation/docs/en/install/compile/compile_CentOS_en.html
OrderedMultiDeviceLoDTensorBlockingQueue defined at:
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/reader/lod_tensor_blocking_queue.h#L73
LoDTensor defined at:
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/lod_tensor.h#L104
This may take some compilation time.

**Comment by YannickJadoul** [comment] 2020-07-27 10:22
> v2.2.4 and v2.5.0 are incompatible。I could not run successfully with v2.5.0. But it's not about this issue。

Well, try updating? v2.5.0 should still work, and contains a lot of fixes. If this is still an issue, and we figure out how to fix it, it will be fixed in v2.5.1 or v2.6.0. v2.2.4 is too old to backport to. Lots of things have been fixed over the last few years, so v2.5.0 might just solve the problem.

> Unfortunately，it's a complex environment. I tried to provide a minimal example, but failed.

Well, if it's too complex for you, how do you wish me to wade through all of this?
If it can't be simplified, it's more likely that something else is going wrong in your code. But we really don't have the time to understand a whole new code base. Also, this is an open source project, so none of us is paid to provide support and you can use the project freely, so please be so kind as to make things as simple as possible for us.
Please reconsider and try to simplify your code to demonstrate what goes wrong, or we cannot help you.

> Due to struct list_caster did not be called constructed function, thus the vector 'value' did not be called constructed function eather.
> Thus, vector 'value' size is big whitout of initialization。value.clear() triggered the crash.

Besides, that's not true. `value` ought to be default-constructed.

**Comment by wanghuancoder** [comment] 2020-07-29 10:56
I tried to provide a minimal example, but failed.
When an error occurs, the constructor function cannot be called, which makes me feel very strange.
I mainly want to see if you have encountered the same problem.
**In addition, I would like to ask. In terms of performance, how does V2.5.0 compare to V2.2.4?**

**Comment by YannickJadoul** [comment] 2020-07-29 14:11
> I tried to provide a minimal example, but failed.
> When an error occurs, the constructor function cannot be called, which makes me feel very strange.

Well, without context, I have absolutely no idea how to answer that.
If it's such a complex environment, and simple minimal examples do no reproduce, it still seems more likely that that complex environment is to blame?

I'd just continue debugging as you'd do normally with any problem: make a copy of the code base, and keep simplifying and removing complexity until suddenly things work. Like that, you can deduce what factor or combination of factors cause the problem.

> I mainly want to see if you have encountered the same problem.

No, it's not really clear what the problem is.

>  **In addition, I would like to ask. In terms of performance, how does V2.5.0 compare to V2.2.4?**

No idea. I don't expect it to be much worse. Try it out, do some benchmarks, and it performance drastically went down, please file a bug!

**Closed by YannickJadoul** 2020-07-29 14:11 UTC
