### ISSUE TITLE
certain numpy code hangs in embed python

### ISSUE THREAD

**Issue by zhouw** [pybind/pybind11#2344] opened 2020-07-30 09:20 UTC
## Issue description

I was trying to execute embedded python script in a multi-threaded C++ application. Certain numpy operations hang if not executed from the main thread. I suspect these numpy operations may mess up with GIL in underlying c++ module.

C++17, MSVC 2017 x64, Python 3.7 x64, numpy 1.18.4

## Reproducible example code

```
int main()
{
    py::scoped_interpreter interpreter{};
    
    py::exec("import numpy as np;print(np.nan < np.random.rand(1,50));");   // this works
    
    auto fut = std::async(std::launch::async, [] {
        py::exec("import numpy as np; print(np.random.rand(1,50));");  // this works
        py::exec("print(np.nan < np.random.rand(1,50));");             // this hangs
    });
    fut.wait();
}
```

**Comment by bstaletic** [comment] 2020-07-30 13:04
I could not reproduce. Here's the output:

```
[[False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False]]
[[0.9470238  0.97444239 0.28820817 0.08754372 0.20916838 0.63592549
  0.91802784 0.69666873 0.47978343 0.65300857 0.49806182 0.75817122
  0.82862357 0.15896557 0.8952582  0.09460167 0.3456044  0.11692763
  0.05539014 0.24386128 0.35702528 0.31967093 0.81360297 0.86312872
  0.56072559 0.02132552 0.68055416 0.97786789 0.53283853 0.89739446
  0.06287967 0.45115204 0.68751815 0.59741597 0.96524973 0.30152018
  0.28613141 0.69153519 0.97715048 0.21948479 0.28459745 0.10724598
  0.59191545 0.40979988 0.14312513 0.57364176 0.56132034 0.89828199
  0.02081919 0.38600143]]
[[False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False]]
```

Though on Linux, python 3.8 and numpy 1.19.1.

**Comment by zhouw** [comment] 2020-07-30 14:01
@bstaletic This is so weird. I tested the code on Mac and there was no problem either (Sierra, Python 3.7, numpy 1.19). It seems only happen on windows.

**Comment by zhouw** [comment] 2020-07-30 14:08
I happened to test this code on windows and it worked. No hang whatsoever.

```
int main()
{
    auto fut1 = std::async(std::launch::async, [] {
        py::initialize_interpreter();
        py::exec("import numpy as np;print(np.nan < np.random.rand(1,50));");   
    });
    fut1.wait();
    
    auto fut = std::async(std::launch::async, [] {
        py::exec("print(np.random.rand(1,50));");  
        py::exec("print(np.nan < np.random.rand(1,50));");   
    });
    fut.wait();
}
```

**Comment by YannickJadoul** [comment] 2020-07-30 14:14
@zhouw Could you try rewriting the original code to nót use pybind11? If this also hangs, then pybind11 is (unfortunately/fortunately) not to blame, and this would be a numpy or CPython bug.

**Comment by zhouw** [comment] 2020-07-30 14:48
@YannickJadoul I tested the following code without pybind11 and it worked fine on Windows. 

```
int main()
{
    Py_Initialize();
    PyEval_InitThreads();

    py::exec("import numpy as np");
    
    PyThreadState* mainPyThread = PyEval_SaveThread();

    auto fut = std::async(std::launch::async, [] {
        PyGILState_STATE gstate;
        gstate = PyGILState_Ensure();

        py::exec("print(np.random.rand(1,50));"); 
        py::exec("print(np.nan < np.random.rand(1,50));"); 
        
        PyGILState_Release(gstate);
    });
    fut.wait();
}
```

**Comment by bstaletic** [comment] 2020-07-30 14:59
Right... You're not managing the gill in the original snippet. Try this:

```c++
int main()
{
    py::scoped_interpreter interpreter{};
    
    py::exec("import numpy as np;print(np.nan < np.random.rand(1,50));");   // this works
    {
        py::gil_scoped_release g;
        auto fut = std::async(std::launch::async, [] {
            py::gil_scoped_acquire g;
            py::exec("import numpy as np; print(np.random.rand(1,50));");  // this works
            py::exec("print(np.nan < np.random.rand(1,50));");             // this hangs
        });
        fut.wait();
    }
}
```

**Comment by zhouw** [comment] 2020-07-30 15:03
@bstaletic cool, it works!

It's just weird that why the initial code does not work on Windows but on Mac/Linux. Perhaps numpy handles the operations in different ways on different platforms.

**Comment by bstaletic** [comment] 2020-07-30 15:17
> It's just weird that why the initial code does not work on Windows but on Mac/Linux. Perhaps numpy handles the operations in different ways on different platforms.

The problem might be in the implementation of `std::async`. From what I've heard, only MSVC backs it with an actual thread pool.

The "we got async wrong" is a part of the motivation for C++ introducing [Executors](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p0443r13.html). @YannickJadoul will like the number of authors of the paper.

> By the way, is there anyway to release/acquire gil manually without "scoped"?

You could use the CPython API for that. Check the documentation for managing the GIL, because I believe `PyGILState_Ensure()` is deprecated.

Reasons to avoid non-RAII backed GIL management tools is that it is unsafe in face of exceptions. If an exception is thrown, you won't restore the state to what it was before. I.e. if you explicitly acquired the GIL you won't let go of it and vice versa. This is especially bad when you think how often python uses exceptions that pybind translates into actual C++ exceptions.

Anyway, the issue is resolved, so I'll close it. Feel free to hop over to [gitter](https://gitter.im/pybind/Lobby) for questions that aren't bugs or feature requests.

**Closed by bstaletic** 2020-07-30 15:17 UTC

**Comment by stellarpower** [comment] 2024-12-09 01:54
I am reproducing an issue like this. I keep the interpreter in its own thread, and then executing everything within that thread by pushing a std::function into a queue from other threads.

What's interesting is everything was previously fine, but then a rebuild involving unrelated code (the header include order may well have changed as part of this) and now it's consistently hanging every time it tries to import numpy (directly or indirectly). I have a small test program that's isolated from the rest of my application but still uses the same class for pushing into a background hread, and that's still working fine. I see a whole load of extra threads spin up after the import, and `PyImport_ImportModule(name)` just goes into a black hole (will grab the sources and try to see where). It happens when I exec the import statement, instead of doing it programmatically, so it's possible it's a bug within Python/numpy or at least it's closer to the GIL/lower-level logic rather than `py::module::import()`.

**Comment by stellarpower** [comment] 2024-12-09 02:59
Okay, maybe my comment is invalid. For anyone else looking, some numerically-intensive python modules can hang for really, really long time when debugging. I have had this issue before with the likes of TensorFlow, when I'd need to allocate a good half an hour or so on a very fast machine if I needed to debug my extension natively. Given I'm using threads, thought this was a synchronisation issue, but in fact it's now looking that I simply started setting breakpoints before the import happened, and if you step over it, I think the sheer volume of C libraries that are dynamically loaded in by the module causes the debugger to take a very long time in performing the import. Some comments online also mentioned seeing changes between debug and release builds - although wasn't sure if this meant the packages themselves or their code in which they embed the interpreter. It seems a bit sporadic if it happens or not, but would advise anyone finding import issues with numpy and similar large and complex libraries that use a lot of bindings to native dynamic libs suddenly crop up to sanity-check if you see the same behaviour when just starting without a debugger attached and.or if you are able, to move the imports earlier in the process (I would have, but, reasons.)
