### ISSUE TITLE
type_caster<std::basic_string<...>>::cast crashes

### ISSUE THREAD

**Issue by alexeyt820** [pybind/pybind11#713] opened 2017-03-09 01:23 UTC
#### Issue description
* python 2.7.11
* MSVC 2015, gcc 4.8.5
When setting dictionary item value to const char *, assignment uses type_caster<std::string>::cast(), which crashes. 

Crash happens inside PyUnicode_Decode method when called with with encoding="utf8", it looks like python bug, however if PyUnicode_Decode invoked with encoding utf-8 it uses 'fast path' and call PyUnicode_DecodeUTF8 instead of dealing with codecs, also PyUnicode_FromStringAndSize uses PyUnicode_DecodeUTF8  as well, so fix maybe just change encoding to "utf-8" and it will be faster, consistent with PyUnicode and will not crash

#### Reproducible example code
```c++
#include <pybind11/pybind11.h>
namespace py = pybind11;

int main()
{
	py::dict dict;
	dict["a"] = "b"; //crash here
        return 0;
}
```

**Comment by jagerman** [comment] 2017-03-09 06:53
Does this crash occur with the current master branch?  I can't see how changing "utf8" to "utf-8" is going to have any effect--Python documentation suggests these are simply aliases for each other.

**Comment by jagerman** [comment] 2017-03-09 07:51
I have a strong suspicion that the issue is actually the inline constexpr encoding string.  Can you try out PR #714 and see whether that fixes it for you?

**Comment by alexeyt820** [comment] 2017-03-09 15:49
I was using master branch.

Regarding utf8 vs utf-8, from python source code utf-8 handled by PyUnicode_Decode differently from {utf8,utf_8}, see snippet below:
```c++
PyUnicode_Decode(...)
{
   if (encoding == NULL)
       encoding = PyUnicode_GetDefaultEncoding();

   /* Shortcuts for common default encodings */
   if (strcmp(encoding, "utf-8") == 0)
       return PyUnicode_DecodeUTF8(s, size, errors);
   else if (strcmp(encoding, "latin-1") == 0)
        return PyUnicode_DecodeLatin1(s, size, errors);
   else if..
   ...
    /* Decode via the codec registry */
  ...
       unicode = _PyCodec_DecodeText(buffer, encoding, errors);
...
}
```
when encoding is utf-8 then PyUnicode_DecodeUTF8 is called, when encoding is utf8 or utf_8, then _PyCodec_DecodeText is called.

**Comment by alexeyt820** [comment] 2017-03-09 16:07
I've tried PR#714, result same => segmentation fault in 
```
		handle s = PyUnicode_Decode(buffer, nbytes,
			UTF_N == 8 ? "utf8" : UTF_N == 16 ? "utf16" : "utf32",
			nullptr);
```

**Comment by jagerman** [comment] 2017-03-09 16:15
Python 3 indeed treats utf8/utf-8/utf_8 identically (as well as similarly fast-pathing utf16/32).

I've no problem changing it to utf-8, but I'm a bit concerned that there is also a bug here for the others (utf16/32).

**Comment by jagerman** [comment] 2017-03-09 16:42
Give #715 a try.  I bypassed the PyUnicode_Decode entirely in favour of just directly calling the appropriate UTF decoder (which should be a "faster" path than Python's fast path).

**Comment by alexeyt820** [comment] 2017-03-09 16:42
Do we need to support anything besides char and wchar_t ? If not then we can use PyUnicode_FromStringAndSize/PyUnicode_FromWideChar, which seems available in python 2 and 3. Or switch to PyUnicode_DecodeUTF(8|16|32). Btw for Windows it maybe more useful to use PyUnicode_DecodeMBCS instead of PyUnicode_FromStringAndSize/PyUnicode_DecodeUTF8, because if you get char from stdin it will be MBCS not UTF8, as far as I know MSVCRT uses MBCS for char.

**Comment by jagerman** [comment] 2017-03-09 16:50
Yes; it also supports `char16_t` and `char32_t` (the `std::u16string`/`std::u32string` underlying character types); and `wchar_t` can be either 16 or 32-bits (16 on Windows and 32 pretty much everywhere else).  But yes, I've switched it to direct DecodeUTF(8|16|32) calls.

**Comment by alexeyt820** [comment] 2017-03-09 16:50
#715 works find for me

**Comment by jagerman** [comment] 2017-03-12 15:19
Fixed in master now.

**Closed by jagerman** 2017-03-12 15:19 UTC
