### ISSUE TITLE
Deprecated declarations warnings

### ISSUE THREAD

**Issue by aldanor** [pybind/pybind11#777] opened 2017-04-05 09:33 UTC
I'm compiling an empty module with `-Wall` with the latest pybind11 (82ece94, Linux / GCC 5.2 / both C++11 and C++14) and I get a ton of deprecated declarations warnings:

```cpp
In file included from ../include/pybind11/cast.h:13:0,
                 from ../include/pybind11/attr.h:13,
                 from ../include/pybind11/pybind11.h:36,
                 from test_module.cpp:10:
../include/pybind11/pytypes.h:190:7: warning: ‘pybind11::object::borrowed’ is deprecated: Use of the `borrowed` static variable is deprecated; use `borrowed_t{}' instead [-Wdeprecated-declarations]
 class object : public handle {
       ^
../include/pybind11/pytypes.h:241:33: note: declared here
     static constexpr borrowed_t borrowed{};
                                 ^
../include/pybind11/pytypes.h:190:7: warning: ‘pybind11::object::stolen’ is deprecated: Use of the `stolen` static variable is deprecated; use `stolen_t{}' instead [-Wdeprecated-declarations]
 class object : public handle {
       ^
../include/pybind11/pytypes.h:243:31: note: declared here
     static constexpr stolen_t stolen{};
                               ^
../include/pybind11/pytypes.h:190:7: warning: ‘pybind11::object::borrowed’ is deprecated: Use of the `borrowed` static variable is deprecated; use `borrowed_t{}' instead [-Wdeprecated-declarations]
 class object : public handle {
       ^
../include/pybind11/pytypes.h:241:33: note: declared here
     static constexpr borrowed_t borrowed{};
                                 ^
../include/pybind11/pytypes.h:190:7: warning: ‘pybind11::object::stolen’ is deprecated: Use of the `stolen` static variable is deprecated; use `stolen_t{}' instead [-Wdeprecated-declarations]
 class object : public handle {
       ^
../include/pybind11/pytypes.h:243:31: note: declared here
     static constexpr stolen_t stolen{};
```

Source:

```cpp
#include <pybind11/pybind11.h>

PYBIND11_PLUGIN(test_warnings) { return pybind11::module("test_warnings").ptr(); }
```

**Comment by aldanor** [comment] 2017-04-05 14:38
(same when just running the test suite)

**Comment by jagerman** [comment] 2017-04-05 14:40
Smells like a gcc 5 bug.  Is this on plain `master`?

**Comment by aldanor** [comment] 2017-04-05 14:41
Yep, just did a clean clone to double check. Plain master with `-Wall -Wextra`.

**Comment by aldanor** [comment] 2017-04-05 14:42
(Oh, `-Wall -Wextra` is the default; so just the defaults then really)

**Comment by aldanor** [comment] 2017-04-05 14:44
Just compiled it with GCC 4.8, no warnings.

**Comment by wojdyr** [comment] 2017-04-06 16:15
I get the same warnings with GCC 6.2

```
[  3%] Building CXX object tests/CMakeFiles/pybind11_tests.dir/test_callbacks.cpp.o
cd /home/wojdyr/fresh/pybind11/build/tests && /usr/bin/g++-6   -Dpybind11_tests_EXPORTS -I/home/wojdyr/fresh/pybind11/include -I/usr/include/python2.7  -Os -DNDEBUG -fPIC   -std=c++14 -flto -fno-fat-lto-objects -fvisibility=hidden -Wall -Wextra -Wconversion -Wcast-qual -o CMakeFiles/pybind11_tests.dir/test_callbacks.cpp.o -c /home/wojdyr/fresh/pybind11/tests/test_callbacks.cpp
In file included from /home/wojdyr/fresh/pybind11/include/pybind11/cast.h:13:0,
                 from /home/wojdyr/fresh/pybind11/include/pybind11/attr.h:13,
                 from /home/wojdyr/fresh/pybind11/include/pybind11/pybind11.h:36,
                 from /home/wojdyr/fresh/pybind11/tests/pybind11_tests.h:2,
                 from /home/wojdyr/fresh/pybind11/tests/test_callbacks.cpp:10:
/home/wojdyr/fresh/pybind11/include/pybind11/pytypes.h:190:7: warning: ‘pybind11::object::borrowed’ is deprecated: Use of the `borrowed` static variable is deprecated; use `borrowed_t{}' instead [-Wdeprecated-declarations]
 class object : public handle {
       ^~~~~~
/home/wojdyr/fresh/pybind11/include/pybind11/pytypes.h:241:33: note: declared here
     static constexpr borrowed_t borrowed{};
                                 ^~~~~~~~
/home/wojdyr/fresh/pybind11/include/pybind11/pytypes.h:190:7: warning: ‘pybind11::object::stolen’ is deprecated: Use of the `stolen` static variable is deprecated; use `stolen_t{}' instead [-Wdeprecated-declarations]
 class object : public handle {
       ^~~~~~
/home/wojdyr/fresh/pybind11/include/pybind11/pytypes.h:243:31: note: declared here
     static constexpr stolen_t stolen{};
                               ^~~~~~
```

**Comment by jagerman** [comment] 2017-04-06 16:59
The warning seems to be fixed in g++ 6.3, but I could reproduce it with a Ubuntu 16.04 docker image.

We can drop the deprecated tags (or even drop them conditionally on GCC < 6.3), but I wonder if it wouldn't be easier to just drop the variables entirely.  They are `protected`, after all, so the only potential backwards compatibility issue would be someone inheriting from `object` (or one of the various `object` descendants) in an extra-pybind11 class and using them.  That seems fairly obscure to me--obscure enough to drop it.  @wjakob @dean0x7d thoughts?

**Comment by wjakob** [comment] 2017-04-06 17:44
I'm okay with deleting them.

**Comment by dean0x7d** [comment] 2017-04-06 20:26
I'm in favor of removing the variables completely since it does affect all GCC version from 5.1 to 6.2. It's a breaking change but should affect very few people and it's a quick fix: `borrowed` -> `borrowed_t{}` and `stolen` -> `stolen_t{}`.

That said, heads up to @SylvainCorlay and @JohanMabille, as it looks like [xtensor-python](https://github.com/QuantStack/xtensor-python/blob/94e9f39ce9983532fb75531c464fb5943e284ad0/include/xtensor-python/pycontainer.hpp#L136) is affected. Note that making the change to the `_t{}` variant is backward compatible with pybind11 2.1 and 2.0, so it's a harmless change.

**Comment by SylvainCorlay** [comment] 2017-04-06 20:34
Thanks for the heads up!
We will move to the _t variants right away to be forward compatible.

**Comment by JohanMabille** [comment] 2017-04-06 20:37
@SylvainCorlay you beat me to it!
@dean0x7d thanks for pinging us.

**Comment by jagerman** [comment] 2017-04-06 20:46
Not quite as unlikely as I'd anticipated then.  Still, it's good: there's a potential for linkage failures with debug builds with it.

**Comment by jagerman** [comment] 2017-04-06 22:36
They're gone now, and the deprecation warnings with them.

**Closed** 2017-04-06 22:35 UTC
