### ISSUE TITLE
py36编译错误

### ISSUE THREAD

**Issue by darrenwang00** [pybind/pybind11#1714] opened 2019-03-02 08:33 UTC
ModuleNotFoundError: No module named 'pip.req'

**Comment by eacousineau** [comment] 2019-03-08 13:02
This seems very application-specific.

I would suggest migrating your question to either Gitter or StackOverflow and possibly closing this issue:
https://gitter.im/pybind/Lobby
https://stackoverflow.com/questions/tagged/pybind11

At a minimum, though, you should post some more details, like what checkout of `pybind11`, and what you ran to get this error, and what code (as minimal as possible) was used to reproduce this.

**Comment by robinpaulson** [comment] 2019-08-10 08:27
I get this too, when I'm installing pybind using pip. Pip is up-to-date (19.2.1), I'm using python3.6 on ubuntu 18.04.

My install command is:
pip install --user pybind

The full error message is:
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5xfs4pz6/pyangbind-brcd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5xfs4pz6/pyangbind-brcd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-5xfs4pz6/pyangbind-brcd/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5xfs4pz6/pyangbind-brcd/setup.py", line 2, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req

**Comment by blaiseli** [comment] 2019-12-18 12:48
Same issue for me with python 3.6, 3.7 and 3.8, on different machines.

3.6: Ubuntu workstation
3.7: Container based on debian
3.8: Centos computing cluster

**Comment by blaiseli** [comment] 2019-12-18 13:12
Update: thanks to @bstaletic who helped me finding the reason of this issue: I was installing `pybind`, and not `pybind11`. @robinpaulson you did the same mistake.

**Closed** 2020-07-07 14:06 UTC
