### ISSUE TITLE
Add attr() method to detail::accessor?

### ISSUE THREAD

**Issue by aldanor** [pybind/pybind11#265] opened 2016-07-03 21:09 UTC
This is a minor thing, but it would sure be nice to be able to do

```cpp
foo.attr("x").attr("y").attr("z")
```

without having to do all the unnecessary temporary casting. Or maybe allow `foo.attr("x", "y", "z")` although that's a less obvious syntax.

**Comment by wjakob** [comment] 2016-07-03 21:10
This sounds good to me (by adding an ``attr`` function to the helper object that is returned by handle::attr)

**Comment by aldanor** [comment] 2016-07-03 21:14
I would probably add the call operator too since it's such an extremely common case -- e.g., import module, call a function; or call a member method etc.

```cpp
module::import("numpy").attr("core").attr("empty")(...)
```

**Comment by wjakob** [comment] 2016-07-03 21:16
fair enough.

**Comment by aldanor** [comment] 2016-07-27 08:53
So, for `attr` and `operator[]` to be much nicer to use, we pretty much have to reimplement entire `handle` for it, this will result in a lot of copy/paste. The chances are, if you're reading an attribute / item, you will *always* cast it to `object`, since it's a pretty useless type otherwise.

I was thinking, why couldn't `accessor` just derive from `handle` (or even `object` actually), with the only difference being the overridden `operator=`? This way, `GetAttr` or `GetItem` would happen right away as you call the `attr` or `operator[]`. 

Also, why does the current code throw on a missing key / attribute when setting it, but not when getting it (e.g. in `operator object`?), instead silently setting `m_ptr` to `nullptr`? Wouldn't it make sense to throw in both cases for consistency purposes?

It would be also nice to be able to access `HasAttr` and `HasItem` in a more explicit way, e.g. by having `.hasattr()` and `.contains()` methods on `handle`.

A few hypothetical examples:

```cpp
// before
obj.attr("foo").cast<object>().attr("bar").cast<"object">();
// after
obj.attr("foo").attr("bar")();

// before
if (auto foo = obj.attr("foo"))
    foo.cast<object>();
// after
if (obj.hasattr("foo"))
    foo.attr("foo")();
// alternatively, if .attr() doesn't throw on missing attribute:
if (auto foo = obj.attr("foo")) // will have m_ptr = nullptr if missing
    foo();
```

Funnily enough, this wouldn't even break the current API much (worst case, you'll be casting object to object unnecessarily).

**Comment by jagerman** [comment] 2016-07-28 19:58
@aldanor — I assume the reason for not deriving from object and invoking `GetAttr` right away is that it's potentially expensive, but `if (obj.attr("foo")) ...` is a lightweight call (in that it invokes `HasAttr` rather than `GetAttr`): in other words, it *is* exactly your hypothetical `if (obj.hasattr("foo")) ...`.

So essentially `accessor` is a "pointer" class, in a loose sense, that doesn't do the heavy lifting until/unless you actually need it.  But following that, perhaps it would make sense to add dereference-like operators to it, such as:

```C++
object got;
object& operator*() { if (!got) { got = /* current code of operator object() */ } return got; }
object* operator->() { return &operator*(); }
// Backwards compatibility:
operator object() { return **this; }
template <typename T> T cast() const { return (*this)->cast<T>(); }
```
plus the operator() (and perhaps operator[]) overloads.  (Although it's not *quite* completely backwards compatible as the `operator object()` above isn't const—I suppose you could make them all const and change `got` to `mutable object got;`)

That seems a relatively easy way to get access to any named methods via `->` instead of `.`:

```C++
foo.attr("abc")->attr("def")->cast<MyType>();
```
without having to duplicate all the named methods of `object` (and wouldn't need any changes if new methods are added to `object`/`handle`).

You can call via:
```C++
(*foo.attr("abc")->attr("ghi"))("some", "args", "here");
```

Or if you add the forwarding-to-object operator() overloads:
```C++
foo.attr("abc")->attr("ghi")("some", "args", "here");
```

**Comment by aldanor** [comment] 2016-07-28 22:16
@jagerman Thanks for a detailed reply!

First, I've also considered suggesting overloading operators `*` and `->` since it's quite C++-esque (e.g., that's exactly what `std::optional` does). If the implementation stays as is, that's the most sensible option of course. I'll try to convene my point below :)

> @aldanor — I assume the reason for not deriving from object and invoking GetAttr right away is that it's potentially expensive, but if (obj.attr("foo")) ... is a lightweight call (in that it invokes HasAttr rather than GetAttr): in other words, it is exactly your hypothetical if (obj.hasattr("foo")) ....

> So essentially accessor is a "pointer" class, in a loose sense, that doesn't do the heavy lifting until/unless you actually need it. 

That's what I thought too initially... But then, come to ponder on it, what makes `__getattr__` and `__getitem__` so special that they deserve so much attention? 

It may sound like a contrived example, but why are those lazy and `__call__` isn't? After all, in most cases a function call would be more expensive than an attribute getter (which quite often is nothing but a lookup in the objects' `__dict__`). Following the same logic, to be consistent you would have to also have a `call_accessor` which would store its arguments and actually make the function call upon casting to object or dereferencing.

On the other hand, if laziness was the ultimate purpose, the current implementation is not as lazy as it could be -- e.g., if you chain a bunch of `.attr()` and `[]` -- all of them will be eagerly evaluated (with you having to use explicit casts or pointer syntax) except for the very last one.

Regarding cheap `hasattr` and `__contains__` checks, if there existed explicit methods `.hasattr()` and `.contains()`, wouldn't that solve the problem of `accessor` having to play three roles at the same time? (bool operator for hasattr/contains, object operator for getting the value, and assignment operator for setting it) If I can easily check if an attribute exists, why would I *not* expect to get an `object` back when using `.attr()`?

// Another unrelated random thought I had re: API niceness was adding a template argument to `.attr()` defaulting to `object` that would do a cast right away -- the chances are you would want to do it quite often:

```cpp
foo.attr("abc").attr<MyType>("def")
```

**Comment by jagerman** [comment] 2016-07-28 23:16
@aldanor What makes `accessor` different is, I think, that it's a class designed to be an interface into attribute/container manipulation, *not* a wrapper around an attribute value.  When you do `obj = otherobj;` with ordinary `py::object`s you essentially make `obj` reference whatever `otherobj` references, but don't change whatever `obj` (used to) point to.  That's quite different from `accessor`, however: its copy assignment is really about setting an underlying value, not about referencing a new value—and that makes it different enough from `object` that I'm not sure it's conceptually suitable to be an `object` subclass.  It feels a bit weird to me to have `attr::operator=(const object &)` mean something fundamentally different from `object::operator=(const object &)`.

Now that said, part of this is really coming about because of, as you mention, the triple-purpose: one of those three purposes really *is* suitable to be an object subclass when all you are doing is accessing the attribute (which is, quite frankly, the most common case).  So perhaps another alternative to consider is to separate the accessor object from the manipulation object, something like:

```C++
object.getattr("name"); // Returns a new (eager) object-derived attribute subclass
object.attr("name"); // Returns the attribute manipulator, as occurs now
```

though I think this would really just be a shortcut to `object.attr("name").operator object()`—or perhaps a modified version that throws for non-existent attributes.

**Comment by aldanor** [comment] 2016-07-29 08:50
> What makes accessor different is, I think, that two-thirds of its purpose is as a class designed to be an interface into attribute/container manipulation, not a wrapper around an attribute value

... however these two-thirds probably amounts to a very small % of use cases in practice. E.g., you're only likely to set attributes on objects in your own codebase, whereas getting attributes happens all the time.

I probably agree with you that having an `object` subclass where the assignment operator was doing something funky would be slightly weird (although still borderline ok). But all of this stems from trying to have objects that are too smart or have too many roles (like the current `accessor`) -- the result is the loss of ergonomics.

However, instead of having a specal subclass for just accessing the attribute maybe it can be done the other way around -- like, let `attr` return an `object` (don't really need a subclass then), but set attributes in some other way (be it another subclass or just a `.setattr()` function). The main reasoning is simple -- `getattr` can be chained (and most often is) which requires getting `object` values; `setattr` cannot be chained and is always just a single terminal call which doesn't return anything.

```
obj.attr("name"); // returns an object eagerly
obj.setattr("name", value); // sets the attribute, doesn't return anything, can't be chained
obj.attr("a").attr("b").setattr("c", value);
```

**Comment by wjakob** [comment] 2016-08-01 21:47
I'll try to chime a bit :)

I'm hesitant against changing the API to ``attr/setattr``, which will break many projects using this library. Another reason against this approach is that all of this doesn't just apply to ``attr()`` but also ``operator[]``, and there is no renaming trick that would work in this case.

Subclassing from object and immediately doing a ``GetAttr()`` is IMHO also a no-go. Since these basic functions are used throughout the library internals, any change here will lead to considerable bloat in the generated binaries. It's suprising how easy it is to add hundreds of KBs to the example project just by adding a function call into a hot template function.

That seems to leave just one option, which is what @aldanor suggested initially: make the ``detail::accessor`` interface more complete.

Off-topic: adding ``contains`` seems fine to me.

**Comment by dean0x7d** [comment] 2016-09-19 16:51
I've been tinkering with a solution for this using a curiously recurring mixin. WIP can be seen in  https://github.com/dean0x7d/pybind11/commit/3624708673658a2dc2ef59208890ea0650bc7020 and https://github.com/dean0x7d/pybind11/commit/088db874a9bdb2f415b2aab2bba6edcf167c1cbe. The basic idea is to extend `attr` and other accessors (item/tuple/list) with the `object_api` mixin. This approach extends the accessors without duplicating code and it preserves the current lazy evaluation of attributes/items.

Now, I ran into an issue here, which isn't actually related to the extended API but rather to the optional nature of `py::object`. The issue is that something like
```c++
obj.attr("value").attr("method")(1, 2, 3)
``` 
may return a `nullptr` at any point along the chain. This makes error handling and reporting very difficult. The existing implementation of `accessor` actually discards Python's original error message and just returns a `nullptr` in `py::object`. Because of this, the chained implementation requires additional `nullptr` checks in multiple places in `accessor`. The error messages also need to be recreated from scratch since the Python originals were discarded.

Adding lots of additional `nullptr` checking can work, but it's not exactly elegant. This brings me to a breaking change proposal. I know there are breaking changes in the pipeline for v2.0, but I'm not sure how soon this is planned to happen? In any case, here is the proposal.

#### Guarantee that `py::object` is never `nullptr`

Currently, any `py::object` (or derived) instance can have **two** invalid states: `nullptr` and `None`. This isn't ideal. While `None` is expected from Python and unavoidable, the `nullptr` state is not. `None` results in nice Python error messages, while `nullptr` results in anything from an internal Python C API error to undefined behavior. Removing the latter from user-facing code would be very beneficial.

A further compilation is that it's currently not very clear when a `nullptr` should be checked for. Not everything will return `nullptr` for an error: for example `py::make_tuple` will throw an exception instead of `nullptr` and `py::cast` can actually do either. It's currently more common that a `nullptr` will be returned. This is fine for internal code and for `py::handle`, but it would be nice if `py::object` was guaranteed to be non-`nullptr` or throw an exception otherwise. This would make the behavior consistent both within the library and with Python (`AttributeError` with a clear error message, rather than a `nullptr`).

`py::object` and derived classes would then become completely safe end-user types. For internal use an optionally `nullptr` type is still required. This is what it would look like:

 * `py::handle` -- remains unchanged: May be `nullptr`. Manual reference counting.
 * `py::owned_handle` -- new type: May be `nullptr`. Automatic ref counting. Intended for implementation machinery and expert users (can leak ref count or dereference `nullptr` if user is not careful).
 * `py::object` -- becomes stricter: Guaranteed never to be `nullptr`. Automatic ref counting. Intended as a safe user type.

Everything else would still derive from `py::object`, nothing from `py::owned_handle`. I've done some preliminary work and it wouldn't be difficult to convert `py::object` -> `py::owned_handle` where appropriate internally. The `py::object`s at interfaces would remain there -- they would just become safer.

The change is breaking, but only in one point: `py::object::operator bool()` will no longer be there. Overall, I think the change would be very much worth it and I can do the work if this seems reasonable.

**Comment by wjakob** [comment] 2016-09-19 17:02
This is a fairly significant design change, and I'm wondering if it may end up complicating the library internals (e.g. the difference between ``handle`` and ``object`` is already very confusing those who haven't used the Python C API. This adds yet another type.).

Being able to ``release()`` an ``object`` or move is very useful to interface with the C API. The ability to std::move() objects helps to prevent some useless inc/dec-refs (leaner codegen). How would this work with the proposed approach?

The alternative and less intrusive breaking change would be to do a pass over the API to ensure that functions like ``cast()`` and ``handle::operator[]`` and ``handle::attr()`` throw ``error_already_set`` rather than returning null pointers.

**Comment by dean0x7d** [comment] 2016-09-19 18:05
Release/move would leave behind `Py_None`. The codegen for moves balances out: `Py_None` would require and additional `++refcnt` in the move constructor/assignment, but the destructor of the move-out object would use the simpler `Py_DECREF` without the extra conditional of the `X` variant required for `nullptr`. While that just kind of balances out, regular copies and construction / destruction will definitely be leaner with the never-`nullptr` `object`, since it will always be able to use the regular `Py_INCREF/Py_DECREF` instead of their `X` variants. That would definitely benefit codegen and this `X` and non-`X` refcounting would be the main implementation difference between `object` and `owned_handle`.

Other than code size, there are two other benefits to having distinct types:

 * `object` can have a debug-only check for `nullptr` in its constructor.
 * Distinct types send a clear signal: always check for `nullptr` with one, never with the other. 

If there is only one type, these expectations need to be maintained some other way: either specifically documented or implied by the detail/interface separation. But that is an additional thing to think about or forget. `owned_handle` would be an implementation detail and a nice danger indicator.

**Comment by aldanor** [comment] 2016-09-19 21:36
Overall, I agree that the current approach is inconsistent (between `attr`, `cast`, `operator[]`) in that sometimes it fails early and sometimes silently passes a nullptr, it would be nice to have it done in one unified way.

@dean0x7d I'm not sure I fully understood this point:

> Currently, any py::object (or derived) instance can have two invalid states: nullptr and None. This isn't ideal. While None is expected from Python and unavoidable, the nullptr state is not. None results in nice Python error messages, while nullptr results in anything from an internal Python C API error to undefined behavior. Removing the latter from user-facing code would be very beneficial.

Are you suggesting that  failed `getattr` would set the pointer to `Py_None` instead of `nullptr`? But that could lead to many weird side-effects because `None` is a valid object, has proper type, etc.

Banning objects carrying `nullptr` is generally a good idea, I think. One way to do it, as I already suggested above, would be to just fail fast and eagerly in `operator[]` and `attr` instead of returning an object-like entity and having to hop around its possible invalidity :) This way, both of them just return `object`. As for the `cast`, I'm not sure as it's a bit more entangled.

**Comment by aldanor** [comment] 2016-09-19 21:37
@dean0x7d Also re: caching attributes: https://github.com/dean0x7d/pybind11/commit/088db874a9bdb2f415b2aab2bba6edcf167c1cbe#commitcomment-19086012

**Comment by dean0x7d** [comment] 2016-09-19 21:45
@aldanor I'm not suggesting that `attr` should return `None`. It should throw an `AttribureError` as expected in Python. 

My point was about `py::object` in general, wherever it comes from, it may be in two kind of invalid state: `None` or `nullptr`.

**Comment by aldanor** [comment] 2016-09-19 22:09
`Py_None` vs `nullptr` issue aside, all in all the suggested `object_api<>` change looks like a good quality of life improvement, and is probably about the best you can do if we don't make `attr` and `operator[]` eager.

// The price you pay for syntactic sugar `.attr("foo") = "bar"` is the implicit non-trivial behaviour for a trivial operation, i.e. the exception is thrown on first access to `.ptr()` instead on the line where the attribute is requested. This also greatly diverges with how you would expect it to work in Python (all attribute access is eager, if you want to cache it - you would do it manually; and in the majority of cases accessing an attribute is just a single dict lookup anyway). I would argue that having explicit behaviour beats syntactic sugar, but from the history of this thread it looks like I'm the only one :)

**Comment by dean0x7d** [comment] 2016-09-19 22:36
@aldanor The WIP implementation with the `throw` in `.ptr()` was my attempt to keep backwards compatibility, but it's pretty bad which is why I suggested banning `nullptr` and throwing early instead. It's a breaking change but it would help a lot (and not just for this issue). In the WIP implementation I had to add checks and `attribute_errors` in three places (+ the original skipped one). With the early error, that would go down to one (and no need to recreate Python error messages).

About the issues with lazy evaluation and proxy classes: actually the only real problem is with `auto` (this is the same one you pointed out in the other comment thread):
```c++
obj.attr("a") = 1;
auto b = obj.attr("a");
obj.attr("a") = 2;
b.cast<object>(); // expected 1, got 2
```
This is generally a problem with proxy classes and expression templates and `auto`. It was going to be addressed with `operator auto()` in C++17, but it got pushed back :(

I'm actually undecided if this is a major issue or just something to get used to (since it also affects some `std` library classes, like `std::vector<bool>`).

**Comment by aldanor** [comment] 2016-09-27 09:37
This should be probably closed (because #425)?

(There's a separate story of what to do with `nullptr` and `py::object`, but maybe that could be discussed separately if we want to go ahead with that.)

**Comment by wjakob** [comment] 2016-09-27 09:40
Ok, I'll close this then. As before, I'm not sure how useful preventing ``nullptr`` will be, I don't feel that it makes a dent in the "convenient to use" VS "pybind11 internal code simplicity" Pareto curve.

**Comment by wjakob** [comment] 2016-09-27 09:41
(However, we can definitely keep discussing if you want)

**Closed by wjakob** 2016-09-27 09:40 UTC
